rskj-core/src/main/java/co/rsk/core/bc/BlockUtils.java
rskj-core/src/main/java/org/ethereum/db/ByteArrayWrapper.java

Refactor to improve block already in blockchain detection. Given the block height, it avoids the read of the full blocks at that height, using directly the known hashes.

Refactor block in blockchain logic, to avoid reading the full blocks

---

rskj-core/src/main/java/co/rsk/net/handler/TxValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorAccountBalanceValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorAccountStateValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorGasLimitValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorIntrinsicGasLimitValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorMinimuGasPriceValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorNonceRangeValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorStep.java
rskj-core/src/test/java/co/rsk/TestHelpers/Tx.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorAccountBalanceValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorGasLimitValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorMinimumGasPriceValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorNonceRangeValidatorTest.java

This is a higher-level API and is simpler. It also prevents converting back and forth and creating multiple arrays/instances.

Use BigInteger in TxValidatorStep instead of byte[]

---

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java
rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/main/java/co/rsk/net/messages/BlockHeadersMessage.java
rskj-core/src/main/java/org/ethereum/core/Block.java
rskj-core/src/main/java/org/ethereum/core/BlockHeader.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderWrapper.java
rskj-core/src/main/java/org/ethereum/core/Genesis.java
rskj-core/src/main/java/org/ethereum/core/SealedBlockException.java
rskj-core/src/main/java/org/ethereum/core/SealedBlockHeaderException.java
rskj-core/src/main/java/org/ethereum/datasource/mapdb/Serializers.java
rskj-core/src/main/java/org/ethereum/net/eth/message/BlockHeadersMessage.java
rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java
rskj-core/src/test/java/co/rsk/core/BlockTest.java
rskj-core/src/test/java/co/rsk/peg/simples/SimpleBlock.java
rskj-core/src/test/java/co/rsk/remasc/RemascTestRunner.java
rskj-core/src/test/java/org/ethereum/TestUtils.java
rskj-core/src/test/java/org/ethereum/db/BlockQueueTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/EthashTestCase.java

When a block is sealed, it cannot be modified. The seal includes the header.
If an unsealed block is sent to the blockchain, a panic is logged.
The blocks that are created using RLP are sealed.
The blocks that are completed by MinerServerImpl are sealed before they are added to the system.}

Sealed block

---

rskj-core/src/main/java/co/rsk/config/RemascConfig.java

Original issue description:
"REMASC is punshing late inclusion with the 20% instead of 5%."
REMASC is applying 5%, the JSON conguration file use 20 as divisor (100/20 == 5%). The difference is in the default value in RemascConfig class: the field was initialized with 5 (100/5 == 20%).
This pull request change the default value, from 5 to 20, but it is not a hard fork: the testnet nodes are configured with a JSON file with divisor == 20

Change divisor (from 5 to 20)

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java

Now, a transaction with receiver account address 0x0000000000000000000000000000000000000000 is recognized as a contract creation one
Some code tests were added. Manual command line tests also passed (with to address in null and with to address filled with zeroes)

Fix Account Address for Contract Creation

---

rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java
rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java

Skip the genesis block processing when arrives from other node. The logic was added to MessageNodeHandler, with expected behavior new test
Tested locally (one miner, one no miner), and againts the testnet (one no miner, syncing from 0 blocks)

Fix genesis proc

---

rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java

It's only a baby step to avoid the permanent stop of top miner, in case of some incidents building the new block to mine (like uncatched exception executing a transaction).

Adding resilient code

---

rskj-core/src/main/java/co/rsk/config/RemascConfig.java
rskj-core/src/main/java/co/rsk/remasc/Remasc.java
rskj-core/src/main/resources/remasc.json

Instead of using "2 *" in REMASC selection rule, use a multiplier and divisor from configuration

Constant moved to config, multiplier and divisor

---

rskj-core/src/main/java/co/rsk/Start.java
rskj-core/src/main/java/co/rsk/rpc/OriginValidator.java
rskj-core/src/main/java/org/ethereum/rpc/JsonRpcNettyServer.java
rskj-core/src/main/java/org/ethereum/rpc/JsonRpcWeb3FilterHandler.java
rskj-core/src/main/java/org/ethereum/rpc/JsonRpcWeb3ServerHandler.java
rskj-core/src/test/java/co/rsk/rpc/OriginValidatorTest.java
rskj-core/src/test/java/org/ethereum/rpc/JsonRpcNettyServerTest.java

Checks that can help to make it harder for attackers to succeed implementing CSRF attacks but should not be considered enough because they assume correct web browser behavior:
- Check content type is json: application/json
- Check origin and referer headers match the whitelisted domain name for CORS.

Improving rpc

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java

RSK Addresses are a 20 byte hash of a public key (40 characters in hex)

Length should be 40. 

---

rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java
rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java
rskj-core/src/test/java/co/rsk/validators/BlockTimeStampValidationRuleTest.java

This PR replaces PR #102 since it was easier to create it again rather than fixing the other one after such a long time. Also some unit tests have been added.
@donequis shouldn't we consider validPeriodLength as in BlockTimeStampValidationRule ?

Validate block timestamp in comparison to parent timestamp

---

rskj-core/src/main/java/org/ethereum/core/AccountState.java
rskj-core/src/main/java/org/ethereum/db/TransactionInfo.java
rskj-core/src/test/java/co/rsk/remasc/RemascFederationProviderTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java
rskj-core/src/test/java/co/rsk/util/RLPTest.java
rskj-core/src/test/java/org/ethereum/core/AccountStateTest.java
rskj-core/src/test/java/org/ethereum/db/ReceiptStoreImplTest.java

RLP.decodeInt cannot be used over data obtained from a RLPList item
So, it was replaces by  BigIntegers.fromUnsignedByteArray
Some tests were added and marked as ignored, only to reveal the problem with RLP.decodeInt

Fixing decoding of integer in TransactionInfo and AccountState

---

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java

The generation of logs in Web3 was fixed. The expected log output was specified using two tests. It was validated againts a TestRPC instance

Fix duplicated logs

---

rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/main/java/co/rsk/peg/Federation.java
rskj-core/src/test/java/co/rsk/peg/FederationTest.java

1. Undo a change in `getPublicKeyIndex` because we didn't take into account that the new method also compared the private key.
2. Check sender instead of public key in `isFromFederateMember` because it is more reliable. `ReversibleTransactionExecutor` creates a transaction without signature and that would throw an `NPE` here.
3. Create `Federation.getRskPublicKeys`, which we use to verify federate member's RSK addresses.

Fix issue in bridge free transaction

---

rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/test/java/co/rsk/util/TestContract.java
rskj-core/src/test/java/org/ethereum/vm/ProgramTest.java

Fixed issue with CALL that wouldn't pass at least the minimum stipend when the remaining gas was lower than that.
Sorry there's no tests, but I couldn't reproduce it yet.

Fix issue where calleeGas would be less than the stipend

---

rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java

The tests failed randomly one out of 256 times when the random address turned out to be local (`127.XXX.XXX.XXX`).
I separated it into two tests: one that asserts failure and one that always passes.

Fix IPv4 tests that failed randomly

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeState.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/ReleaseRequestQueue.java
rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionBuilder.java
rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionSet.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStateTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/ReleaseRequestQueueTest.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionSetTest.java
rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java

Release BTC workflow was refactored so that several release BTC transactions can be signed simultaneously.
The idea is that we now wait for confirmations on the coin selection when releasing btc, thus being able to mark UTXOs as used early and do several coin selections without the need for signing and releasing first.
For this, the bridge has now got two new objects stored: a `ReleaseRequestQueue` and a `ReleaseTransactionSet`.
Flow is as follows: when requesting a release, an entry is added to the release request queue. 
Upon `updateCollections`, the release request queue is processed and coins are selected. Successful selections turn into BTC transactions that get into the release transaction set, where they will be waiting for enough confirmations. 
When enough confirmations are …

Feature/rfs 62 multiple release btc (plus rfs 43 & 54)

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java
rskj-core/src/test/java/co/rsk/test/DslFilesTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
rskj-core/src/test/resources/dsl/contracts03.txt
rskj-core/src/test/resources/dsl/create01.txt
rskj-core/src/test/resources/dsl/empty.sol
rskj-core/src/test/resources/dsl/opcode_revert1.txt
rskj-core/src/test/resources/dsl/opcode_revert2.txt

After checking the gas used in TestRPC and local geth nodes, we discovered our node produces a different gas used in those cases. The difference was 32000, in many tests. So, we added that gas amount in TransactionExecutor logic.
Some test had been modified, because the expected gas used is now different (in the same amount, 32000 gas units).
We don't find the corresponding logic in current EthereumJ.

Add creation gas cost when a contract is created from an transaction

---

rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java
rskj-core/src/main/java/org/ethereum/net/NodeManager.java
rskj-core/src/test/java/org/ethereum/config/SystemPropertiesTest.java
rskj-core/src/test/java/org/ethereum/net/NodeManagerTest.java

Rename bindIp method to getPeerDiscoveryBindAddress. 
Rename externalIp method to getExternalIp.
Remove socket implementation to get the ip if not configured. 
Reorder logger. 
Modify log message. 
Syncronize getExternalIp method to avoid double excecution. 
Try to resolve peer.discovery.external.ip to avoid exception in peer discovery when is not propertly configured. 
Add getMyPublicIpFromRemoteService as a separated method to resolve public ip using a remote service.

Modify bindIp and externalIp

---

rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/main/java/org/ethereum/net/server/ChannelManager.java
rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java
rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleChannelManager.java

Fix problem where block hashes where not relayed when a new block arrived

Channnel manager now takes block identifiers to broadcast block hash

---

rskj-core/src/main/java/co/rsk/trie/Trie.java
rskj-core/src/main/java/co/rsk/trie/TrieImpl.java
rskj-core/src/main/java/co/rsk/trie/TrieStore.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/test/java/co/rsk/trie/SecureTrieImplHashTest.java
rskj-core/src/test/java/co/rsk/trie/SecureTrieImplKeyValueTest.java
rskj-core/src/test/java/co/rsk/trie/SecureTrieImplMessageTest.java
rskj-core/src/test/java/co/rsk/trie/SecureTrieImplSaveRetrieveTest.java
rskj-core/src/test/java/co/rsk/trie/SecureTrieImplStoreTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplDeleteTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplHashTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplKeyValueTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplMessageTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplSaveRetrieveTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplSerializationTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplSnapshotTest.java
rskj-core/src/test/java/co/rsk/trie/TrieImplValueTest.java
rskj-core/src/test/java/co/rsk/trie/TrieStoreImplTest.java
rskj-core/src/test/java/org/ethereum/core/BlockTest.java

These changes are motivated by issue #265 
Now, long values (with MORE than 32 bytes) are serialized and deserialized using their hashes.
The changes alter the root hashes of the states, and they are oriented only to prevent a future hard fork. The use of a Partial Merkled Tree should be improved, but after planning meeting discussion, it was posponed: they is no use of that class, yet.
Any change out the initial scope, was avoided.
Additional tests was added, and local manual tests were executed, with success. A full devnet test cycle is still pending.

Change Trie Serialization/Deserialization

---

.gitignore
rskj-core/src/main/java/co/rsk/mine/BlockGasPriceRange.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/TestNetAfterBridgeSyncConfig.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java

- Renamed NewBlockMaxMinInTheFuture to correctly specify it's in seconds
- Changed BlockGasPriceRange calculation to use BigInteger
- Increased IndexedBlockStore cache

Changes in BlockGasPriceRange calculation and additional tiny changes

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java

Proposal: from web3 et_hbridgeState, in EthModule, use BridgeSupport instead of use the Bridge contract with call.
This new implementation avoid:
- Using Call, create a constant call, with gas, instantiate a Bridge contract, call the execute, convert the result to HRESULT, then parse the result again, etc..
And, if needed, the get state for debugging method in Bridge could be removed, avoiding to put a high cost only to avoid its call.

Get bridge status using BridgeSupport

---

rskj-core/src/main/java/co/rsk/core/RskAddress.java
rskj-core/src/main/java/co/rsk/remasc/RemascTransaction.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java

In mainnet we are encoding the Remasc transaction sender as the byte array with just one zero instead of the empty byte array. This prevents us from using the `RskAddress.nullAddress()` object.
@ajlopezrsk has an alternative solution which is also worth considering, but this one maintains strict checks in the `RskAddress` class.

Specify the Remasc sender as currently in mainnet so we don't hardfork

---

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java
rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/co/rsk/core/bc/PendingStateImpl.java
rskj-core/src/main/java/co/rsk/db/RepositoryImpl.java
rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/main/java/co/rsk/mine/MinerUtils.java
rskj-core/src/main/java/co/rsk/net/Metrics.java
rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java
rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java
rskj-core/src/main/java/org/ethereum/net/rlpx/FrameCodecHandler.java
rskj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java
rskj-core/src/main/java/org/ethereum/net/rlpx/MessageCodec.java
rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java
rskj-core/src/main/java/org/ethereum/net/submit/TransactionTask.java

Many logs were throw on info level and it makes hard to get what's happening on the node by reading logs.
Most of them were kept and demoted to trace so still can be used for debugging but are not useful for the regular user. 
Still there are some logs coming from external libraries that should be turned off or silenced from logback.
There are some minor fixes on string formats or incompatible protocol.

Reduce logging messages on info level

---

rskj-core/src/main/java/org/ethereum/rpc/JsonRpcNettyServer.java

See https://github.com/elastic/elasticsearch/issues/19834.
Example of a failing `cURL` request:
```bash
$ curl -X POST \
-H "Content-Type: application/json" \
-d '{"id":1,"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826","gas":"0x47e76c","gasPrice":"0x4a817c800","data":"0x6060604052341561000f57600080fd5b6040805190810160405280601281526020017f48656c6c6f20736d61727420776f726c642100000000000000000000000000008152506000908051906020019061005a929190610060565b50610105565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100a157805160ff19168380011785556100cf565b828001600101855582156100cf579182015b828111156100ce5782518255916020019190600101906100b3565b5b5090506100dc91906100e0565b5090565b61010291905b80821 …
```

Fix JsonRpcNettyServer pipeline order to fix issue with Expect header

---

rskj-core/src/main/java/co/rsk/Start.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/org/ethereum/cli/CLIInterface.java
rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java
rskj-core/src/main/java/org/ethereum/net/NodeManager.java
rskj-core/src/main/java/org/ethereum/net/message/StaticMessages.java
rskj-core/src/main/java/org/ethereum/net/p2p/HelloMessage.java
rskj-core/src/main/java/org/ethereum/net/rlpx/Node.java
rskj-core/src/main/java/org/ethereum/net/server/PeerServer.java
rskj-core/src/main/java/org/ethereum/net/server/PeerServerImpl.java
rskj-core/src/main/resources/config/rsk-sample.conf
rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java
rskj-core/src/test/java/co/rsk/net/discovery/UDPServerTest.java
rskj-core/src/test/java/org/ethereum/cli/ClIInterfaceTest.java
rskj-core/src/test/java/org/ethereum/config/ConfigTest.java
rskj-core/src/test/java/org/ethereum/config/SystemPropertiesTest.java
rskj-core/src/test/java/org/ethereum/net/NodeManagerTest.java
rskj-core/src/test/java/org/ethereum/rpc/Simples/SimplePeerServer.java
rskj-core/src/test/resources/test-rskj.conf

The goal is that all services integrated on the node now are binded to a unique interface defined at config on bind.ip property. The properties peer.bind.ip and rpc.host now dissapear. Peer discovery, rpc server and wire protocol now all use the same binding.

All net interfaces now bind to a unique address

---

rskj-core/src/main/java/co/rsk/mine/MinerUtils.java
rskj-core/src/main/java/co/rsk/net/handler/TxValidator.java
rskj-core/src/main/java/co/rsk/validators/TxsMinGasPriceRule.java
rskj-core/src/main/java/org/ethereum/core/ImmutableTransaction.java
rskj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java
rskj-core/src/test/java/co/rsk/core/ImmutableTransactionTest.java
rskj-core/src/test/java/co/rsk/validators/TxsMinGasPriceValidatorTest.java

Transactions now use a basic format tx=transaction-hash

Common format for transaction logging

---

rskj-core/build.gradle

It should only be a `testCompile` dependency.

Remove JUnit from compile dependencies

---

rskj-core/src/main/java/org/ethereum/core/BlockHeader.java

This would've produced a hardfork because the number zero was encoded as `[ 0 ]` in the genesis, but `BigInteger::toByteArray` would return it as `[-128]`.

Fix Block::minimumGasPrice encoding

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java

Previously we would convert `null`s to `[0]`, which ended up in a different serialization.

Fix Transaction::valueRaw storage

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/DevNetConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/FallbackMainNetConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetAfterBridgeSyncConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetBeforeBridgeSyncConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetFirstForkConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetAfterBridgeSyncConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetBeforeBridgeSyncConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetFirstForkConfig.java
rskj-core/src/main/java/org/ethereum/config/net/MainNetConfig.java
rskj-core/src/main/java/org/ethereum/config/net/TestNetConfig.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/test/java/co/rsk/peg/BridgeFromVMTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/performance/BtcBlockchainTest.java

Two main issues are addressed in this PR:
RFS-55: two new bridge methods were added: `getBtcBlockchainInitialBlockHeight` and `getBtcBlockchainBlockHashAtDepth`. This allows for the federate node to update the bridge's btc blockchain without using the -now deprecated- `getBtcBlockchainBlockLocator`. A special configuration was added to the blockchain constants to determine from which block the fork for rfs-55 applies.
RFS-90: fix to allow calling any bridge method from another contract. This is also treated as a hard fork, adding an analogue constant in the bridge constants. Essentially, if the fork has not been reached, the error condition (a `RuntimeException`) is simulated.

RFS-55 improve blockchain block locator and RFS-90 call bridge from contract

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java

Added `setSignature` method to `Transaction` to allow to externally set a transaction's signature.

RFS-60 - Allow manually setting signatures on transactions

---

rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java

This fixes a bug introduced when changing the type of a field in the `BlockInfo` class, which implements `Serializable`.
It adds `serialVersionUID` for safety.

Fix BlockInfo serialization

---

rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java
rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java

In regtest: timestamp block rule receives 0 value as period. With this value, a future block is accepted. 
With this change, truffle tests can send future blocks (tested with truffle OpenZeppelin tests)

Timestamp rule with 0 value period

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/config/VmConfig.java
rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java
rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTrace.java
rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTraceListener.java
rskj-core/src/test/java/co/rsk/peg/SamplePrecompiledContractTest.java
rskj-core/src/test/java/co/rsk/vm/PrecompiledContractTest.java
rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java
rskj-core/src/test/java/co/rsk/vm/VMPerformanceTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java
rskj-core/src/test/java/org/ethereum/vm/PrecompiledContractTest.java
rskj-core/src/test/java/org/ethereum/vm/ProgramMemoryTest.java
rskj-core/src/test/java/org/ethereum/vm/VMComplexTest.java
rskj-core/src/test/java/org/ethereum/vm/VMCustomTest.java
rskj-core/src/test/java/org/ethereum/vm/VMTest.java
rskj-core/src/test/java/org/ethereum/vm/VMUtilsTest.java

This fixes the performance issue encountered in the `VM` by repeatedly accessing the `RskSystemProperties` object, **with a focus on improving code quality** via refactoring.
Basically, removes the `RskSystemProperties` object from `Program` and `VM`, helping with maintenance and testability.
* creates a `VmConfig` class
* makes `PrecompiledContracts` a non-static component
* replaces the injected `RskSystemProperties` with those two components in `Program` and `VM`

Introduce a VmConfig class

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/DevNetConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetFirstForkConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetFirstForkConfig.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java

This is the hard fork implementation of #394

[RFS-94] Remove bridge method get state for debugging

---

rskj-core/src/main/java/co/rsk/core/RskFactory.java
rskj-core/src/main/java/co/rsk/rpc/netty/JsonRpcWeb3FilterHandler.java
rskj-core/src/main/java/co/rsk/rpc/netty/Web3HttpServer.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/resources/config/rsk-sample.conf
rskj-core/src/test/java/co/rsk/rpc/netty/Web3HttpServerTest.java

Header host is validated now. It checks that is accepted from rpc.address and if rpc.address is using a wildcard it uses a new param defined called rpc.host for the task.

Dns rebinding fix

---

rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeBtcWallet.java
rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/Federation.java
rskj-core/src/main/java/co/rsk/peg/FederationMember.java
rskj-core/src/main/java/co/rsk/peg/PendingFederation.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/test/java/co/rsk/net/handler/TxValidatorTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/FederationMemberTest.java
rskj-core/src/test/java/co/rsk/peg/FederationTest.java
rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java
rskj-core/src/test/java/co/rsk/peg/PendingFederationTest.java
rskj-core/src/test/java/co/rsk/peg/performance/ActiveFederationTest.java
rskj-core/src/test/java/co/rsk/peg/performance/FederationChangeTest.java
rskj-core/src/test/java/co/rsk/peg/performance/PendingFederationTest.java
rskj-core/src/test/java/co/rsk/peg/performance/RetiringFederationTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java

Refactor:
`Federation` and `PendingFederation` are now composed of a list of `FederationMember` instead of `BtcECKey`. Each `FederationMember` is composed of a pair of keys (one for BTC and one for RSK). Usages across the system have been updated as to use same keys for BTC and RSK.

RFS-95 - Federation key enhancement (RFS-109 - Part A)

---

rskj-core/src/main/java/co/rsk/cli/CliArgsParser.java
rskj-core/src/main/java/co/rsk/cli/OptionalizableArgument.java
rskj-core/src/main/java/co/rsk/cli/config/MigrationTool.java
rskj-core/src/main/java/co/rsk/cli/config/Migrator.java
rskj-core/src/main/java/co/rsk/cli/config/MigratorConfiguration.java
rskj-core/src/test/java/co/rsk/cli/config/MigratorTest.java

This is a simple CLI program for migrating configurations. This must be invoked with:
```
java -cp [jar] co.rsk.cli.config.MigrationTool -i original.config -m migration.properties [-o output.config] [--replace]
```
`migration.properties` is a [properties](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html) file which describes the mapping between the old and the new configuration. For example:
```properties
bind.address = bind_address
rpc.cors = rpc.providers.web.cors
rpc.enabled = rpc.providers.web.http.enabled
rpc.port = rpc.providers.web.http.port
rpc.bind_address = rpc.providers.web.http.bind_address
rpc.linger.time = rpc.providers.web.http.linger_time
```
By default you don't need to specify an output file, it'll create a new file in …

Tool for migrating configurations between versions

---

rskj-core/src/main/java/co/rsk/mine/MinerServer.java
rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/main/java/co/rsk/mine/MinerUtils.java
rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java

New methods to support submission of merged mining solution:
- submitBitcoinBlockTransactions
- submitBitcoinBlockPartialMerkle
Both receive less information than old submitBitcoinBlock method which is still available for backward compatibility reasons.

Feature/add submit bitcoin solution new  methods

---

rskj-core/src/main/java/co/rsk/net/BlockProcessor.java
rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java
rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/main/java/co/rsk/validators/BlockCompositeRule.java
rskj-core/src/main/java/co/rsk/validators/BlockParentCompositeRule.java
rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorTest.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java
rskj-core/src/test/java/co/rsk/net/simples/SimpleBlockProcessor.java

To avoid invalid blocks by invalid uncles

Skip advanced block in NodeMessageHandler

---

rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

@sirhill reported this issue in [Gitter](https://gitter.im/rsksmart/rskj?at=5a9d5f3df3f6d24c683c7dcf). It can be reproduced running the following code on `web3.js:1.0-beta30`:
```js
var Web3 = require('web3');
var web3 = new Web3('http://localhost:4444');
web3.eth.getTransaction('0x1b32ef862ace0ab9759775427dbb348dcb28b29152e8866eef56014d38b8d524')
.then(console.log);
```
This is caused because `web3.js` is performing a strict validation on the sender address (`from` field): https://github.com/ethereum/web3.js/blob/a4d592e8d6d89e531ace066018bfc004ef501f0c/packages/web3-utils/src/index.js#L247
This fixes the `Remasc` sender address serialization to be a valid address.

Fix TransactionResultDTO Remasc sender serialization

---

rskj-core/src/main/java/co/rsk/core/RskFactory.java
rskj-core/src/main/java/co/rsk/net/BlockProcessor.java
rskj-core/src/main/java/co/rsk/net/BlockSyncService.java
rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java
rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/test/java/co/rsk/net/BlockSyncServiceTest.java
rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorTest.java
rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorUnclesTest.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerUtil.java
rskj-core/src/test/java/co/rsk/net/OneAsyncNodeTest.java
rskj-core/src/test/java/co/rsk/net/SyncProcessorTest.java
rskj-core/src/test/java/co/rsk/net/TwoAsyncNodeTest.java
rskj-core/src/test/java/co/rsk/net/TwoNodeTest.java
rskj-core/src/test/java/co/rsk/net/simples/SimpleAsyncNode.java
rskj-core/src/test/java/co/rsk/net/simples/SimpleBlockProcessor.java
rskj-core/src/test/java/co/rsk/test/World.java

If the blocks are not close enough by block number when are relayed, then the block will be ignored. If it was a useful block it will be obtained later

Old blocks are ignored when processed

---

rskj-core/src/main/java/co/rsk/cli/config/Migrator.java
rskj-core/src/test/java/co/rsk/cli/config/MigratorTest.java

A new semantic has been added to the migration file. Now, if you prefix the key with `[new]`, it will be set in the destination configuration with the defined value. For example:
```properties
[new] rpc.host = ["localhost"]
```

Add support for new configuration keys with default value 

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java

This is the master backport of [#441](https://github.com/rsksmart/rskj/pull/441/) against `0.5.0`

[RFS-60] Refactored signing logic for both BTC and RSK transactions

---

rskj-core/src/main/java/org/ethereum/crypto/ECKey.java
rskj-core/src/test/java/co/rsk/crypto/ECKeyTest.java

This is the master backport of [#503](https://github.com/rsksmart/rskj/pull/503) against 0.5.0.

[RFS-91] HSM integration

---

rskj-core/build.gradle
rskj-core/src/main/java/co/rsk/config/RemascConfigFactory.java

This uses Jackson for the only production code usage of JsonSimple that we had, and leaves the dependency for tests only.

Remove JsonSimple from compile dependencies

---

rskj-core/src/main/java/co/rsk/DoPrune.java
rskj-core/src/main/java/co/rsk/Start.java
rskj-core/src/main/java/co/rsk/core/RskImpl.java
rskj-core/src/main/java/org/ethereum/facade/Ethereum.java
rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java
rskj-core/src/main/java/org/ethereum/net/server/PeerServer.java
rskj-core/src/main/java/org/ethereum/net/server/PeerServerImpl.java
rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java
rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleEthereum.java
rskj-core/src/test/java/org/ethereum/rpc/Simples/SimplePeerServer.java

As I was working on understanding the `PeerServerImpl`'s code, I discovered it wasn't honoring the `host` parameter (which is the `bind.address` configuration).
This PR:
* Fixes the bind address bug
* Moves the responsibility of starting the `PeerServer` to the `PeerServerImpl` class

Honor bind address in PeerServerImpl

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

Move call  to getLowestBlock() to getBtcBlockchainBlockLocator() where its used to avoid calling it if its not mandatory

RFS-174  Performance improvement in getLowestBlock() 

---

rskj-core/src/main/java/co/rsk/rpc/ExecutionBlockRetriever.java
rskj-core/src/main/java/org/ethereum/util/Utils.java
rskj-core/src/test/java/co/rsk/rpc/ExecutionBlockRetrieverTest.java
rskj-core/src/test/java/org/ethereum/util/UtilsTest.java

- Added retrieval of a block by its number on `ExecutionBlockRetriever`
- Covered cases with unit tests

Allowing contract method calls with explicit block numbers

---

rskj-core/build.gradle

This puts in the `rskj-core/build/reports/jacoco/test/html/` directory the HTML output of the coverage report. Let me know if Jenkins needs the output in a different format (available options: xml, csv)

Jacoco plugin

---

rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java

Some validation checks don't write a message on failure. By adding the missing logs might help debug these cases or diagnose other type of problems.

Add missing logs for proof of work failed validation checks

---

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java

`web3.js` assumes it's an integer, and the `eth_hashrate` RPC call fails if we return a decimal.
https://github.com/ethereum/web3.js/blob/c0e727eac7c16826c39fd43a03a4930b5ff6fff8/packages/web3-eth/src/index.js#L196
You can also see that `go-ethereum`'s API returns an integer:
https://github.com/ethereum/go-ethereum/blob/f9c456e02d6b8320389a7ea95c0eef3e10a87e2e/eth/api.go#L65

Make RPC's hashrate an integer value to be more compatible

---

rskj-core/build.gradle

cc @juli
This updates the configuration dependency to fix a bug with environment variables (see https://github.com/lightbend/config/issues/559)
I looked at the code changes and everything seems to be in order. I also re-built the code from scratch using the following Docker image and the diffoscope report shows no binary differences with the version published in Maven Central: [report](https://github.com/rsksmart/rskj/files/2064150/diffoscope.pdf).
```Dockerfile
FROM frolvlad/alpine-oraclejdk8:8.144.1-slim
RUN apk add --no-cache bash curl openrc git
RUN curl -sL "https://piccolo.link/sbt-1.1.6.tgz" | gunzip | tar -x -C /usr/local && \
ln -s /usr/local/sbt/bin/sbt /usr/local/bin/sbt
WORKDIR /code
RUN git clone https://github.com/lightbend/config.git
WORKDIR /code/config
RUN git checkout …
```

Update com.typesafe:config to 1.3.3

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

Two main enhancements:
1) Both the btc block store and btc blockchain components of the bridge support are now initialized in a lazy fashion.
2) Four of the five usages of the btc blockchain were to either gather the head or the head's height. Those calls were replaced with calls to the btc block store. Therefore, the btc blockchain is only used (and initialised) in the `receiveHeaders` method.

RFS-188 - BridgeSupport lazy component initialization

---

.gitignore

The following files are ignored:
rskj-core/java/nodeId.properties
rskj-core/java/state/CURRENT
rskj-core/java/state/LOCK
rskj-core/java/state/LOG
rskj-core/java/state/MANIFEST
rskj-core/java/details/CURRENT
rskj-core/java/details/LOCK
rskj-core/java/details/LOG
rskj-core/java/details/MANIFEST

Ignore rskj-core/java folder as it has Logs, Locks and Manifests that are local

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/net/eth/EthMessageSender.java
rskj-core/src/main/java/co/rsk/net/eth/RskMessage.java
rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/net/NodeManager.java
rskj-core/src/main/java/org/ethereum/net/eth/message/Eth62MessageFactory.java
rskj-core/src/main/java/org/ethereum/net/eth/message/TransactionsMessage.java
rskj-core/src/main/java/org/ethereum/net/p2p/P2pHandler.java
rskj-core/src/main/java/org/ethereum/net/server/Channel.java
rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/net/eth/RskMessageTest.java
rskj-core/src/test/java/co/rsk/net/eth/WriterMessageRecorderTest.java
rskj-core/src/test/java/org/ethereum/net/TransactionsMessageTest.java

- removed when not needed
- tidy up properties and values handled inside class

Cleanup rsk config properties

---

rskj-core/src/main/java/co/rsk/core/bc/PendingState.java
rskj-core/src/main/java/co/rsk/mine/MinerUtils.java
rskj-core/src/test/java/co/rsk/mine/MinerUtilsTest.java

- New algorithm to sort transactions by price, but taking into account sender and then each cluster is order by nonce.
This method first sorts list of getPendingTransactions into individual sender and sorts those lists by nonce. After the nonce ordering is satisfied, the results are merged back together by price in a heap to make it fast.
- Also added some test to check the correct behaviour of the new ordering.

New algorithm to sort pending transactions taking into account price

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java
rskj-core/src/main/resources/config/devnet.conf
rskj-core/src/main/resources/config/regtest.conf
rskj-core/src/main/resources/reference.conf

This maintains current behavior for all networks but allows configuration using environment variables and Java system properties.
This was necessary to speed up OpenZeppelin tests as seen [here](https://github.com/rsksmart/openzeppelin-solidity/blob/d7dc91f33eb1fc604064429c65a3de7a35c41f1c/.circleci/config.yml#L20):
```
docker run \
-e "miner.client.delayBetweenBlocks=500" \
-e "miner.client.delayBetweenRefreshes=500" \
-d --name rskj rsksmart/rskj --regtest
```

Move miner client delays configuration to the configuration file

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/bc/PendingState.java
rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/org/ethereum/core/TransactionSet.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java
rskj-core/src/test/java/org/ethereum/util/TransactionFactoryHelper.java

When a new transaction arrives from a sender that wants to replace another transaction not yet processed there is introduced a new rule to determine if it's paying enough gas to accept the new one.

Implemented a rule to accept a tx replacement on Transaction Pool

---

rskj-core/src/main/java/co/rsk/net/discovery/UDPChannel.java

We don't need to close the channel because UDP is connection-less.
There was a comment stating this, but someone ignored it at some point
in the EthereumJ codebase: https://github.com/ethereum/ethereumj/commit/65fd770e1ec821c3edcc6770f502e5731a90ac06#diff-364a0e29f783aa2c9c709bc8ae663b9dR60

Don't close UDP channel on exception

---

rskj-core/src/main/java/co/rsk/net/SyncProcessor.java

This fix checks an status is already there when a node is considered to be a candidate for syncing.
In a next version we should improve this code so peers without status information can't be counted as a possible candidate. No candidate should have incomplete information.

Need to check the if the registered node may not have a status yet

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/main/java/co/rsk/peg/FederationSupport.java
rskj-core/src/main/java/co/rsk/remasc/RemascFederationProvider.java
rskj-core/src/main/java/org/ethereum/config/BlockchainNetConfig.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/GenesisConfig.java
rskj-core/src/main/java/org/ethereum/config/net/AbstractNetConfig.java
rskj-core/src/main/java/org/ethereum/config/net/DevNetConfig.java
rskj-core/src/main/java/org/ethereum/config/net/RegTestConfig.java
rskj-core/src/main/java/org/ethereum/config/net/TestNetConfig.java
rskj-core/src/test/java/co/rsk/mine/MainNetMinerTest.java
rskj-core/src/test/java/co/rsk/mine/ParameterizedNetworkUpgradeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/FederationSupportTest.java

Confi example
```
blockchain.config.name = "regtest"
genesis_constants.federationPublicKeys = [
"02a364011ddf807157465ade342ba385753930921eecbeb5c675543c7e70f09f9b",
"0278a0128e398dbcd726f9b08eb0e5e0b98acce842cd7c585110b9f0d47353ed3b",
"02c173fc28b9b5d5c2599397ae2fd0bf05c6ec1b8c09a1627d3d6b72e1dae09ca1"
]
```

Allow setting the genesis federation in the config file for RegTest and DevNet

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/RskFactory.java
rskj-core/src/main/java/co/rsk/core/SnapshotManager.java
rskj-core/src/main/java/co/rsk/core/bc/FamilyUtils.java
rskj-core/src/main/java/co/rsk/mine/AutoMinerClient.java
rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java
rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransaction.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionDisabled.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionInstant.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWallet.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/SnapshotManagerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

The idea for this feature is mine a block every time an incoming transaction arrives to `MinerServer`. 
So, if the transaction is valid, we will get a new block with that transaction mined.
This new feature will be triggered both in `eth_sendTransaction` and `eth_sendRawTransaction`.
To turn on this feature you need to configure as follows:
* `miner.client.autoMine=true`
* `miner.client.enabled=true`.
For example, you can pass in a VM option like `-Dminer.client.autoMine=true`, or set it in the configuration file.
- To achieve this change was necessary to create a new `MinerClient` called `AutoMinerClient` which is simpler than `MinerClientImpl`, why ? it basically removes all the code its needed to mine a block every X time.
- Create a test set to check if the block was mined correctly …

Second iteration adding automine

---

rskj-core/src/main/java/co/rsk/mine/TxBuilder.java
rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/core/ImmutableTransaction.java
rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/main/java/org/ethereum/vm/program/InternalTransaction.java
rskj-core/src/test/java/co/rsk/core/ImmutableTransactionTest.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/co/rsk/net/SyncProcessorTest.java
rskj-core/src/test/java/co/rsk/net/utils/TransactionUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/simples/SimpleRskTransaction.java
rskj-core/src/test/java/co/rsk/test/builders/TransactionBuilder.java
rskj-core/src/test/java/co/rsk/validators/RemascValidationRuleTest.java
rskj-core/src/test/java/org/ethereum/db/ReceiptStoreImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Refactoring of Transaction class to avoid unnecessary recursion when parsing/encoding transaction from/to RLP.
To achieve this, the class was first refactored to a non-efficient version, where the RLP encoding/decoding and the hashing was computed every time, without caching any values. This made easy to remove all the lazy behavior of the class while preserving its interface. 
After checking all the existing tests passed against this version, a new simplified version of the lazy behavior was introduced. The only method that mutates the state of a transaction is the sign method, and it only affects the generation of the RLP representation of the transaction and the calculation of its hash. The raw hash (the hash of the transaction without its signature) and the raw RLP encoding (the …

Transaction refactored

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java

Config files are additive, that means that if more settings (not present in default config file) are needed to run a certain configuration those settings will override/add to the ones of the base config. For example, regtest.conf is the base config file while my_regtest.conf can be added with some custom settings.
The previous generates a problem because settings in regtest.conf can be overrided/added but not removed. For using `mining.reward.address` the setting `mining.coinbase.secret` should not exist (code validations check that). Since `mining.coinbase.secret` is set on regtest.conf there is no way to use `mining.reward.address` because both settings exist and validations fail.
This PR contemplates that special case in the settings validations so either `mining.coinbase.secret` or …

Fix to allow mining reward address setting to be used in regtest

---

rskj-core/src/main/java/co/rsk/mine/BlockToMineBuilder.java
rskj-core/src/main/java/co/rsk/mine/MinerClock.java
rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/main/java/co/rsk/mine/MinerUtils.java
rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java
rskj-core/src/test/java/co/rsk/mine/MainNetMinerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerClockTest.java
rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java

- remove global minimumAcceptableTime, now we just get that value from   blockStore.getBestBlock().getTimestamp()
- division should be between long. So we explicitly declare 100 as a long. It was lossing precision.
- Added the ability to clean IncreaseTime after submit to simulate what ganache does.
Changes in the fed integration test at *utils:fix-for-open-zeppelin*

Changes to make more zeppelin tests work

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/RskFactory.java
rskj-core/src/main/java/co/rsk/mine/AutoMinerClient.java
rskj-core/src/main/java/co/rsk/mine/MinerClient.java
rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java
rskj-core/src/main/java/co/rsk/mine/MinerClock.java
rskj-core/src/main/java/co/rsk/mine/MinerManager.java
rskj-core/src/main/java/co/rsk/mine/MinerServer.java
rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/main/java/co/rsk/rpc/modules/evm/EvmModuleImpl.java
rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/config/blockchain/FallbackMainNetConfig.java
rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java
rskj-core/src/test/java/co/rsk/mine/MainNetMinerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerClockTest.java
rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleMinerClient.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java

Since both networks have enabled RSKIP98, we will never again sign blocks with the fallback mechanism.

Remove fallback mining signing, but not validation

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/exception/RskJsonRpcRequestException.java

Return a JSON-RPC error when calling `eth_call` results in `revert`. We decided to return the same error code and message as Parity: https://github.com/paritytech/parity-ethereum/blob/7fb33796b17a474242f24d364522ebe5c8a5beef/rpc/src/v1/helpers/errors.rs#L44.
We know this is not a full implementation, but it enables us to run more tests from the OpenZeppelin suite, in particular the ones that check the revert status. We decided to stop here because there's an [ongoing discussion about the RPC interface](https://github.com/ethereum/EIPs/issues/1442), and it'll be best for us to spend the resources when the dust is settled.
Here are some interesting links I found when investigating how to implement this:
* https://github.com/trufflesuite/truffle/issues/976
* …

Return JSON-RPC error on eth_call revert

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWalletEnabled.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

This makes OpenZeppelin's `ECDSA` and `SignatureBouncer` tests pass (7 tests).

Make eth_sign compatible with Ethereum

---

rskj-core/src/main/java/co/rsk/net/discovery/message/PeerDiscoveryMessage.java
rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/main/java/org/ethereum/crypto/ECKey.java
rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/co/rsk/crypto/ECKeyTest.java
rskj-core/src/test/java/org/ethereum/core/TransactionTest.java
rskj-core/src/test/java/org/ethereum/crypto/ECKeyTest.java

The signatureToKey method in ECKey class expects a Base64 encoded signature. There are no uses that justify this encoding, which forces users of the class to encode the signature parameter just to be able to use the signatureToKey method. This pull request contains a refactor to remove the Base64 encoding from the method, the introduction of utility methods in ECDSASignature class to convert from / to Base64 in case it is needed and modifications to test cases to maintain compatibility with the existing test suite.

Removed unnecesary conversions between Base64 and ECDSA signatures

---

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/co/rsk/net/TransactionValidationResult.java
rskj-core/src/main/java/co/rsk/net/handler/TxPendingValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxNotNullValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorAccountBalanceValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorAccountStateValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorGasLimitValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorIntrinsicGasLimitValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorMinimuGasPriceValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorNonceRangeValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorNotRemascTxValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorStep.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/org/ethereum/core/TransactionPool.java
rskj-core/src/main/java/org/ethereum/core/TransactionPoolAddResult.java
rskj-core/src/main/java/org/ethereum/rpc/exception/RskJsonRpcRequestException.java
rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorAccountBalanceValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorAccountStateValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorGasLimitValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorIntrinsicGasLimitValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorMinimumGasPriceValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorNonceRangeValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorNotNullValidatorTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorNotRemascTxValidatorTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

**Motivation**
As of now, the addTransaction method in TransactionPoolImpl returns a boolean value indicating if the transaction was added or not. However, in case the transaction was not added, it does not provide any information about why the transaction was rejected.
This lack of information is most perceived when sending a transaction through either sendTransaction or sendRawTransaction. Current behaviour returns a normal RPC result with the transaction hash instead of an RPC error, regardless the transaction was added or not. This causes both confusion or uncertainty in the user since the tx won't show in the explorer and problems with tools such as Truffle, which considers a transaction added when its hash is returned and waits for it to be mined.
**Description**
This PR adds a …

Return an error when sendTransaction fails instead of the transaction hash

---

rskj-core/src/main/java/co/rsk/trie/TrieStore.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/test/java/co/rsk/trie/SecureTrieImplStoreTest.java
rskj-core/src/test/java/co/rsk/trie/TrieStoreImplTest.java

Replace `TrieStore::getSaveCount` and `::getRetrieveCount` with mockito validators. These methods were created just for testing, and are unnecessary in production code.

 Remove TrieStore::getSaveCount and ::getRetrieveCount

---

rskj-core/src/main/java/co/rsk/rpc/Web3TxPoolModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/txpool/TxPoolModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/txpool/TxPoolModuleImpl.java
rskj-core/src/test/java/co/rsk/rpc/modules/txpool/TxPoolModuleImplTest.java

Addresses #689.
* Fix escaped-string response by returning a Jackson `JsonNode` object instead of a String
* Fix serialization issues through the use of the `TypeConverter` class

Txpool module json responses

---

rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java

This fixes a bug that loaded a wrong genesis block when the node already had a database (i.e not a fresh start).
This regression was introduced in #765.

Fix corner case when loading the genesis

---

rskj-core/src/main/java/org/ethereum/core/BlockHeader.java
rskj-core/src/test/java/co/rsk/core/FreeBlockHeader.java

The bitcoin block header for merged mining is 80 bytes

btc block header length 80-byte

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/db/RepositoryImpl.java
rskj-core/src/main/java/co/rsk/trie/Trie.java
rskj-core/src/main/java/co/rsk/trie/TrieImpl.java
rskj-core/src/main/java/co/rsk/trie/TrieStore.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/main/java/org/ethereum/config/CommonConfig.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
rskj-core/src/main/java/org/ethereum/datasource/HashMapDB.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSource.java
rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java
rskj-core/src/main/java/org/ethereum/db/DetailsDataStore.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/trie/TrieImplSnapshotTest.java
rskj-core/src/test/java/org/ethereum/datasource/DataSourceWithCacheTest.java
rskj-core/src/test/java/org/ethereum/datasource/KeyValueDataSourceTest.java
rskj-core/src/test/java/org/ethereum/datasource/LevelDbDataSourceTest.java

A refactor for splitting the Trie and its underlying store is planned but not tackled by this PR. Having that in mind, I don't think integrating this changes should make that task harder

Performance improvements on Trie handling

---

rskj-core/src/main/java/co/rsk/trie/NodeReference.java
rskj-core/src/main/java/co/rsk/trie/TrieImpl.java

Moving the lazy behavior of the trie to `NodeReference` helps separate concerns and simplify the trie code. It was easier through a simplification of the trie, which was stripped to be a binary trie and not an n-ary trie anymore.
These changes reduced the `TrieImpl` class from 940 to 746 lines, which will help future generations in understanding it.
As a side bonus, we reuse the references when operating on the trie and do not allocate memory for the arrays we previously had.

Create a NodeReference abstraction for the trie

---

rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/main/java/org/ethereum/vm/trace/Op.java
rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTrace.java

If the VM trace is activated in configuration file using:
```
vm.structured {
trace = true
dir = vmtrace
compressed = false
initStorageLimit = 10000
}
```
the output of a contract execution is more aligned to geth debug transaction output (rename fields, new fields, etc):
```
{
"contractAddress" : "77045e71a7a2c50903d88e564cd72fab11e82051",
"initStorage" : {
"290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563" : "000000000000000000000000cd2a3d9f938e13cd947ec05abc7fe734df8dd826",
"0000000000000000000000000000000000000000000000000000000000000000" : "0000000000000000000000000000000000000000000000000000000000000003",
"290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e564" : "0000000000000000000000007986b3df570230288501eea3d890bd66948c9b79", …
```

Improve VM trace

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetSecondForkConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetSecondForkConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestSecondForkConfig.java
rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetSecondForkConfig.java
rskj-core/src/test/java/co/rsk/pcc/bto/DeriveExtendedPublicKeyPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/pcc/bto/ExtractPublicKeyFromExtendedPublicKeyPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/pcc/bto/GetMultisigScriptHashPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/pcc/bto/ToBase58CheckPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTestCase.java
rskj-core/src/test/java/co/rsk/peg/performance/GetBtcTransactionConfirmationsTest.java
rskj-core/src/test/java/co/rsk/peg/performance/IdentityPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/peg/performance/PrecompiledContractPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/peg/performance/ReceiveHeadersTest.java

This PR does four main things:
1. The Bridge now allows for dynamic gas cost calculation in any of its methods. This feature is used in #3 below.
2. The Bridge method `receiveHeaders` can now be called by anyone (up to now it was only callable by members of either the active or retiring federation). This is programmed as a network update.
3. The Bridge method `receiveHeaders` has now got a dynamic cost calculation, dependant upon the data input. This is also programmed as a network update, under the same flag as #2.
4. The `ReceiveHeadersTest` gas estimation tests were updated to consider different input conditions. This will be used later to come up with a final function to calculate the cost of a call depending on the input. That is, the final cost function will be set in an upcoming …

RFS-258 - Make receiveHeaders method public

---

rskj-core/src/main/java/co/rsk/trie/Trie.java

The cloneArray call is removed from private constructor, instead is moved to specific places where is needed. Looking at each use of the constructor, the call should be only used inside internalPut when the value comes as a parameter. #790

Move clone out of private constructor to required places

---

rskj-core/src/main/java/co/rsk/pcc/bto/DeriveExtendedPublicKey.java
rskj-core/src/main/java/co/rsk/pcc/bto/ExtractPublicKeyFromExtendedPublicKey.java
rskj-core/src/main/java/co/rsk/pcc/bto/GetMultisigScriptHash.java
rskj-core/src/main/java/co/rsk/pcc/bto/ToBase58Check.java
rskj-core/src/test/java/co/rsk/pcc/bto/GetMultisigScriptHashPerformanceTestCase.java
rskj-core/src/test/java/co/rsk/pcc/bto/GetMultisigScriptHashTest.java

This PR sets the gas costs for each of the four methods of the `BTOUtils` native contract.
Additionally, there's minor validation changes on the `BTOUtils::GetMultisigScriptHash` method (namely, now the minimum required number of keys is two rather than just one).

RFS-328 - BTOUtils gas costs

---

rskj-core/build.gradle

Now using [bitcoinj-thin 0.14.4-rsk-7](https://github.com/rsksmart/bitcoinj-thin/releases/tag/v0.14.4-rsk-7) that removes the version tally entirely. See [this PR](https://github.com/rsksmart/bitcoinj-thin/pull/13) for details.

RFS-332 - Remove version tally

---

rskj-core/build.gradle
rskj-core/src/test/java/co/rsk/TestHelpers/Tx.java
rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerUtil.java
rskj-core/src/test/java/co/rsk/net/SyncProcessorTest.java
rskj-core/src/test/java/co/rsk/peg/ABICallSpecTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/FederationTest.java
rskj-core/src/test/java/co/rsk/peg/PendingFederationTest.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java
rskj-core/src/test/java/co/rsk/rpc/EthSubscriptionNotificationEmitterTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/netty/RskJsonRpcHandlerTest.java
rskj-core/src/test/java/co/rsk/rpc/netty/Web3WebSocketServerTest.java
rskj-core/src/test/java/co/rsk/trie/TrieSnapshotTest.java
rskj-core/src/test/java/co/rsk/vm/MinerHelper.java
rskj-core/src/test/java/org/ethereum/datasource/DataSourceWithCacheTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/util/RskMockFactory.java

This is just a stepping stone in the long way of supporting Java 11. Dependencies weren't reproduced because they are test dependencies, but the hashes were updated anyway.

Upgrade to Mockito 2

---

rskj-core/src/main/java/org/ethereum/db/DetailsDataStore.java

New private method **getRSKAddress** added:
It will return RemascTransaction.REMASC_ADDRESS instead of new RskAddress when the input bytes match the bytes of the REMASC_ADDRESS.
This method is used to map the db keys to RskAddress instances when calling the keys() method. Otherwise, an exception informing an RSKAdress mismatch will be thrown when db.keys() contains Remasc addresses.

getRSKAddress mapping added to take into account REMASC addresses

---

rskj-core/src/main/java/co/rsk/pcc/bto/GetMultisigScriptHash.java
rskj-core/src/main/java/co/rsk/pcc/bto/ToBase58Check.java
rskj-core/src/test/java/co/rsk/pcc/bto/GetMultisigScriptHashTest.java
rskj-core/src/test/java/co/rsk/pcc/bto/ToBase58CheckTest.java

All numeric datatypes have been changed to `int256`.

RFS-334 - BTOUtils datatype changes

---

rskj-core/src/main/java/co/rsk/peg/bitcoin/MerkleBranch.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/MerkleBranchTest.java

As described in https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki
If not throws InvalidMerkleBranchException

Validate Hashes size to be lower than 256 (uint8)

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

Use the checkpoint itself to compare the initial height when using a Checkpoint in BridgeSupportTest.testInitialChainHeadWithBtcCheckpoints()
This way we don't have to change the test for each new checkpoint

Remove harcoded checkpoit test value in testInitialChainHeadWithBtcCheckpoints()

---

rskj-core/src/main/java/co/rsk/mine/MinerClock.java
rskj-core/src/main/resources/config/regtest.conf

**This PR has last master changes.** 
Now when Regtest is enabled and Automine is disabled, block timestamp will increase as used to.
Also timeAjustment won't be compute when Regtest is disabled

Increase block's timestamp when Automine=false

---

rskj-core/build.gradle

Upgrading to latest bitcoinj-thin version were version tally was removed.
See [here](https://github.com/rsksmart/bitcoinj-thin/pull/13) for more details.
:robot: **build using** *fed:bitcoinj-thin-0.14.4-rsk-7*

Upgrades bitcoinj-thin version to 0.14.4-rsk-7

---

.lgtm.yml

This configuration file allows the Java analysis on LGTM.com to succeed: https://lgtm.com/projects/g/rsksmart/rskj/logs/languages/lang:java

Add LGTM.com configuration

---

.circleci/config.yml
README.md
build.gradle

1. Use Gradle's SonarQube plugin so project settings are picked up automatically
2. Apply workaround that prevented analysis from running correctly on CircleCI: https://community.sonarsource.com/t/no-code-or-issue-found-in-pull-request-decorations-github-circleci/8496

Use Gradle's SonarQube

---

rskj-core/src/test/java/co/rsk/RskContextTest.java

Smoke test for NodeRunner now runs with Rsk Test Context

Avoid smoke test run using real db

---

rskj-core/src/main/java/co/rsk/db/MutableTrieCache.java
rskj-core/src/main/java/co/rsk/db/MutableTrieImpl.java
rskj-core/src/main/java/co/rsk/trie/MutableTrie.java
rskj-core/src/main/java/org/ethereum/db/MutableRepository.java
rskj-core/src/main/java/org/ethereum/db/TrieKeyMapper.java
rskj-core/src/test/java/co/rsk/db/MutableTrieCacheTest.java
rskj-core/src/test/java/co/rsk/db/RepositoryImplOriginalTest.java
rskj-core/src/test/java/co/rsk/db/RepositoryUpdateTest.java

MutableTrieCache changes the internal structure for a more simpler one where order of operations is not needed anymore. Deletions are marked and all this data can be committed to lower levels including Trie.
With this change introduced the implementation for storageKeys can be calculated merging the information from the trie and the current level of cache

Rework trie mutable cache to allow a newer implementation for storage keys

---

rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java
rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java

This class depends on the number of times its called. If executed in a different order makes the processMinersFeesWithOneSiblingBrokenSelectionRuleBlockWithLowerHash test fail
At some point we should  refactor the entire PegTestUtils class

Fix for random circle error that was originated by PegTestUtils createHash3

---

rskj-core/src/main/java/co/rsk/mine/ForkDetectionDataCalculator.java
rskj-core/src/test/java/co/rsk/mine/ForkDataDetectionCalculatorTest.java

The max uncle possible for a block was mistakingly assumed to be 7, when instead it was 10.
This PR addresses the issue by capping the total uncle count to 255

Fix uncle count alculation in ForkDetectionData

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/NetworkStateExporter.java
rskj-core/src/main/java/co/rsk/db/RepositoryLocator.java
rskj-core/src/main/java/org/ethereum/core/Repository.java
rskj-core/src/main/java/org/ethereum/db/MutableRepository.java
rskj-core/src/main/java/org/ethereum/vm/program/Storage.java
rskj-core/src/test/java/co/rsk/core/NetworkStateExporterTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/co/rsk/db/RepositoryImplOriginalTest.java
rskj-core/src/test/java/co/rsk/db/RepositoryLocatorTest.java
rskj-core/src/test/java/co/rsk/db/RepositoryTest.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
rskj-core/src/test/java/co/rsk/test/DslFilesTest.java
rskj-core/src/test/java/co/rsk/vm/BlockchainVMTest.java
rskj-core/src/test/java/co/rsk/vm/MinerHelper.java

The plan is to completely remove `Repository` from the context, and use the `RepositoryLocator` instead. This is a step towards that.
Next, we'll try to get rid of `Repository#syncToRoot`.

Get rid of MutableRepository#getSnapshotTo

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java
rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/org/ethereum/core/Repository.java
rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java
rskj-core/src/main/java/org/ethereum/db/MutableRepository.java
rskj-core/src/main/java/org/ethereum/vm/program/Storage.java
rskj-core/src/test/java/co/rsk/core/CallContractTest.java
rskj-core/src/test/java/co/rsk/core/SnapshotManagerTest.java
rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java
rskj-core/src/test/java/co/rsk/db/RepositoryImplTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascTestRunner.java
rskj-core/src/test/java/co/rsk/test/World.java
rskj-core/src/test/java/co/rsk/test/builders/AccountBuilder.java
rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java
rskj-core/src/test/java/co/rsk/test/builderstest/AccountBuilderTest.java
rskj-core/src/test/java/co/rsk/test/dsl/WorldDslProcessor.java
rskj-core/src/test/java/co/rsk/test/dsltest/WorldDslProcessorTest.java
rskj-core/src/test/java/co/rsk/vm/BlockchainVMTest.java
rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java
rskj-core/src/test/java/org/ethereum/rpc/LogFilterTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/util/ContractRunner.java

Remove  `Repository#syncToRoot` and use `RepositoryLocator#snapshotAt` instead. This forces the user of the repository to think about the `state root` on which to work, and gets us closer to removing `Repository` from the DI context.
*fed:repository_synctoroot*

Remove Repository#syncToRoot

---

rskj-core/src/main/java/co/rsk/rpc/ExecutionBlockRetriever.java

As of now, said component relies on the miner server to be updated. When the miner server is
disabled the component is not updated on new blocks which causes that when queried it returns
incomplete or inconsistent data.

Address issue where eth_call with 'pending' parameter would fail due to relying on an unupdated component

---

rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/resources/reference.conf

Fixes #633.
To verify the service response:
```
$ curl --header "X-Forwarded-For: 192.168.0.2" checkip.amazonaws.com                                                rskj/git/checkip_fix
192.168.0.2, <YOUR IP WILL BE HERE>
```

Support multiple addresses from Amazon checkip service

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/db/migration/OrchidToUnitrieMigrator.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/main/resources/config/main.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/db/IndexedBlockStoreTest.java

This is intended to be released in v1.0.2 to support the case where a miner keeps producing Orchid blocks after Wasabi activation.

Support unitrie migration after Wasabi activation

---

rskj-core/src/main/java/co/rsk/peg/Federation.java
rskj-core/src/main/java/co/rsk/peg/FederationMember.java
rskj-core/src/test/java/co/rsk/peg/FederationTest.java

Previously we used to check only for btcPublicKeys. Now that we have multiple keys, we are checking also rskPubKeys.
*fed:added-ismember*

Added method isMember on Federation class and unit tests for it.

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/db/BlocksIndex.java
rskj-core/src/main/java/co/rsk/db/MapDBBlocksIndex.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/test/java/co/rsk/core/CodeReplaceTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockForkTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/co/rsk/core/bc/FamilyUtilsTest.java
rskj-core/src/test/java/co/rsk/db/HashMapBlocksIndex.java
rskj-core/src/test/java/co/rsk/db/MapDBBlocksIndexTest.java
rskj-core/src/test/java/co/rsk/jsontestsuite/LocalStateTest.java
rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java
rskj-core/src/test/java/co/rsk/validators/BlockUnclesValidationRuleTest.java
rskj-core/src/test/java/org/ethereum/TestUtils.java
rskj-core/src/test/java/org/ethereum/core/TransactionTest.java
rskj-core/src/test/java/org/ethereum/db/IndexedBlockStoreTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java
rskj-core/src/test/java/org/ethereum/util/RskTestContext.java

This change allows having an index with an arbitrary sequential interval of blocks.
The BlockInfo class cannot be moved from IndexedBlockstore due to the index encoding. An index  migration is required to move it.

Add support for non genesis starting block index

---

rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java

Check if refreshWorkTimer is null at stop() to avoid a NPE
Mock the getParentHashJsonString() method as it should be @Notnull (test failing in some versions of intellij for this)

Mock the getParentHashJsonString() method as it should be @Notnull

---

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/Web3.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

This PR aims to include the merge mining related fields to the responses from rpc methods such as `eth_getBlockByHash` or `eth_getBlockByNumber`.
Said fields are:
* `bitcoinMergeMiningHeader`: the bitcoin header which serves as proof of work for the rsk block
* `bitcoinMergedMiningCoinbaseTransaction`: the bitcoin block coinbase transaction which links the btc block with the rsk block
* `bitcoinMergedMiningMerkleProof`: the bitcoin block coinbase's SPV
* `hashForMergedMining`: the rsk mining hash used to link the btc and rsk blocks through the coinbase
For more information about these fields refer to the [wiki](https://github.com/rsksmart/rskj/wiki/Merged-Mining)

Extend existing eth_getBlock methods to include merge mining fields

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/config/GarbageCollectorConfig.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/bc/GarbageCollector.java
rskj-core/src/main/java/co/rsk/trie/MultiTrieStore.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreFactory.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/bc/GarbageCollectorTest.java
rskj-core/src/test/java/co/rsk/trie/MultiTrieStoreTest.java
rskj-core/src/test/java/org/ethereum/util/RskTestContext.java

This is a v1 implementation of the state garbage collection feature. The full definition of the expected feature is in [RSKIP64](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP64.md). This v1 doesn't minimize the nodes stored in each epoch but when we decide to implement that it'll be retrocompatible with this implementation at storage level.
It's disabled by default, you have to opt-in through the `blockchain.gc.enabled` configuration flag.

State garbage collector v1

---

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/NetworkUpgrade.java
rskj-core/src/main/resources/reference.conf

The entry in the `referece.conf` file must be removed when the actual activation height gets defined for every network.
Also the name must be changed once the committee reaches consensus on it

Create Wasabi+1 network upgrade configuration

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java
rskj-core/src/main/java/co/rsk/core/bc/BlockFork.java
rskj-core/src/main/java/co/rsk/core/bc/BlockchainBranchComparator.java
rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/co/rsk/rpc/EthSubscriptionNotificationEmitter.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/BlockHeaderNotification.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/BlockHeaderNotificationEmitter.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeLogsParams.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeNewHeadsParams.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeParams.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeParamsDeserializer.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeParamsVisitor.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeTypes.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscriptionNotificationDTO.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscriptionParams.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/LogsNotification.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/LogsNotificationEmitter.java
rskj-core/src/main/java/co/rsk/rpc/modules/rsk/RskModuleImpl.java
rskj-core/src/main/java/co/rsk/rpc/netty/RskJsonRpcHandler.java
rskj-core/src/main/java/org/ethereum/db/ReceiptStore.java
rskj-core/src/main/java/org/ethereum/db/ReceiptStoreImpl.java
rskj-core/src/test/java/co/rsk/core/bc/BlockchainBranchComparatorTest.java
rskj-core/src/test/java/co/rsk/rpc/EthSubscriptionNotificationEmitterTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/BlockHeaderNotificationEmitterTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeRequestTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/LogsNotificationEmitterTest.java
rskj-core/src/test/java/co/rsk/rpc/netty/RskJsonRpcHandlerTest.java
rskj-core/src/test/java/org/ethereum/db/ReceiptStoreImplTest.java

This brings initial `eth_subscribe(logs)` support to the RSK node. For now, each and every log will be emitted - i.e there's now filtering support. The client will receive an error when passing parameters.

Support logs parameter in eth_subscribe

---

rskj-core/src/main/java/co/rsk/RskContext.java

This is to match MultiTrieStore constructor semantic
*fed: release_1.1.0.0*
*ci: release_1.1.0*
*fit: 1.1.0.0-snapshot*

Increase current epoch value read from disk

---

rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java
rskj-core/src/main/java/co/rsk/net/messages/MessageType.java
rskj-core/src/main/java/co/rsk/net/messages/MessageVisitor.java
rskj-core/src/main/java/co/rsk/net/messages/TransactionIndexRequestMessage.java
rskj-core/src/main/java/co/rsk/net/messages/TransactionIndexResponseMessage.java
rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java
rskj-core/src/test/java/co/rsk/net/messages/BlockReceiptsRequestMessageTest.java
rskj-core/src/test/java/co/rsk/net/messages/BlockReceiptsResponseMessageTest.java
rskj-core/src/test/java/co/rsk/net/messages/MessageTest.java
rskj-core/src/test/java/co/rsk/net/messages/MessageVisitorTest.java
rskj-core/src/test/java/co/rsk/net/messages/TransactionIndexRequestMessageTest.java
rskj-core/src/test/java/co/rsk/net/messages/TransactionIndexResponseMessageTest.java

Transaction Index Message (branch name is wrong, sorry)
Original Parity message:
// Request for transaction index based on hash.
Request::TransactionIndex {
ID: 2
Inputs:
Loose(H256) // transaction hash
Outputs:
U reusable_as(0) // block number
H256 reusable_as(1) // block hash
U // index in the block.
}
Our Request:
ID
Input: TransactionHash
Our Response:
ID
Input: BlockNumber, BlockHash, TransactionIndex

Light client transaction index message

---

rskj-core/src/main/java/co/rsk/remasc/Remasc.java
rskj-core/src/main/java/org/ethereum/db/BlockStore.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/test/java/org/ethereum/db/BlockStoreDummy.java

Remasc precompiled contract usually  retrieved 4000 blocks in mainchain, each time. Now, the retrieve of the execution block (current block - maturity aprox) was replaced by an algorithm using in other uses cases. The old method used was removed.

Improving remasc blocks retrieval; removing unused BlockStore method

---

rskj-core/src/test/java/co/rsk/validators/ForkDetectionDataRuleTest.java

Linux entropy pool gets emptied out pretty quickly, and honestly in tests there's no need to block waiting for randomness.

change random source in tests

---

README.md

They were pointing to 404 pages. The new links were taken from
http://www.rsk.co home page.

Fix whitepaper and blog URLs on README

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java

Defined a new BridgeConstant with the upper limit for the feePerKb for each network. Using said value in voteFeePerKbChange method, rejecting any value above it.
Confirmed it's not a hard fork using Blockchain verificator tool to check that voteFeePerKbChange method was never called in mainnet or testnet with a value above the maximum defined
*fit: rfs-420*

Set upper limit in voteFeeperKbChange

---

rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java
rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/co/rsk/core/bc/PendingState.java
rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/test/java/co/rsk/core/CallContractTest.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java
rskj-core/src/test/java/co/rsk/vm/MinerHelper.java
rskj-core/src/test/java/org/ethereum/core/TransactionTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java
rskj-core/src/test/java/org/ethereum/util/ContractRunner.java

In many places of the code, `TransactionExecutor` is invoked using
```
executor.init();
executor.execute();
executor.go();
executor.finalization()
```
Now, these calls were replaced by only one method  `executeTransaction`

Redesign TransactionExecutor interface, using executeTransaction

---

rskj-core/src/main/java/org/ethereum/rpc/LogFilterElement.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java

Changing log values based on ethereum specifications. Empty `data` should resolve to `0x` instead of `0x00`, same with `address`
*fed:version120* *fit:120*

Change log data and address format

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/mine/MinerServer.java
rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java
rskj-core/src/test/java/co/rsk/mine/MainNetMinerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java

This new protocol introduces a new format for saving information in the `extraData` field of the block. 
Data is stored RLP encoded and the protocol is based on the [following standard ](https://github.com/ethereum/wiki/wiki/Default-Extra-Data-Standard) with the sole difference that RSK starts the protocol versioning number on 1 instead of 0.
*fed:version120* *fit:120*

Extra Data Population Protocol

---

rskj-core/build.gradle
rskj-core/src/main/java/org/ethereum/net/p2p/P2pHandler.java
rskj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java
rskj-core/src/main/java/org/ethereum/net/rlpx/MessageCodec.java
rskj-core/src/test/java/org/ethereum/net/rlpx/HandshakeHandlerTest.java

Fixes https://github.com/rsksmart/rskj/issues/1039.
This PR adds snappy compression support by adding the Xerial snappy library (a JNI wrapper for the official library).
Following the [DevP2P EIP 706](https://eips.ethereum.org/EIPS/eip-706), this PR enables snappy compression after the hello message signals a p2pVersion of 5 or higher.
There is no configuration setting for allowing snappy compression - it's enabled if p2pVersion is 5 or more by default, in the same way framing is implemented.

Add snappy compression to RLPx when p2pVersion >= 5

---

rskj-core/build.gradle
rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/net/discovery/UDPServer.java
rskj-core/src/main/java/co/rsk/net/discovery/upnp/UpnpGatewayManager.java
rskj-core/src/main/java/co/rsk/net/discovery/upnp/UpnpProtocol.java
rskj-core/src/main/java/co/rsk/net/discovery/upnp/UpnpService.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/resources/config/main.conf
rskj-core/src/main/resources/config/regtest.conf
rskj-core/src/main/resources/config/testnet.conf
rskj-core/src/test/java/co/rsk/RskContextTest.java
rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java
rskj-core/src/test/java/co/rsk/net/discovery/UDPServerTest.java
rskj-core/src/test/java/co/rsk/net/discovery/upnp/UpnpGatewayManagerTest.java
rskj-core/src/test/java/co/rsk/net/discovery/upnp/UpnpServiceTest.java
rskj-core/src/test/resources/test-rskj.conf

Feature description:
- UPnP is toggleable by the config property `peer.discovery.upnp_enabled` and is enabled by default.
- If automatic port mapping fails, a log message notifies the user to enable UPnP on their router, or disable UPnP in the node conf and forward router ports manually.
- Any automatic port mapping created via UPnP on the router is deleted upon node shutdown.
Implementation notes:
- The `UpnpService` is injected into `UDPServer` if the service was enabled in the conf.  This is the only service using UPnP right now.
- There are three TCP services running: `Web3WebSocketServer`, `Web3HttpServer` , `PeerServerImpl`.  All three of these services are configurable with different network interfaces/local addresses, each of which could be connected to unique WAN gateways.  If …

Add UPnP support for peer discovery. Resolves #1036

---

rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
rskj-core/src/test/java/co/rsk/trie/TrieStoreImplTest.java
rskj-core/src/test/java/org/ethereum/datasource/DataSourceWithCacheTest.java

The implementation of `DataSourceWithCache` is improved with:
Automanage of write flush
Synchronization locks to support multithreading
And `TrieStoreImpl` avoid the write of a known trie world state

Improved DataSourceWithCache: auto flush, sync locks; TrieStore avoid to write known state

---

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/vm/OpCode.java
rskj-core/src/main/java/org/ethereum/vm/OpCodes.java
rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

Simple implementation for the SELFBALANCE opcode, given that it is asking for the balance of the owner of the contract, it is assumed that the balance is already in cache, and thus is cheaper than a call to BALANCE.

Selfbalance opcode

---

rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
rskj-core/src/test/java/co/rsk/mine/ParameterizedNetworkUpgradeTest.java

Miner Server tests relating to the extraData field would break when executing on a non-SNAPSHOT version.
The aim of this PR is to generalize these tests to work under any of the configured test configurations.

Generalize Miner Server's extra data tests

---

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java

Validating a transaction is more expensive than verifying if it's already added in a Hash map.
Performing first the check if the Tx hash exists in pendingTransactions or queuedTransactions improves performance

First check if the transaction is already added in TransactionPoolAddResult

---

rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Introduce `cumulativeDifficulty` field to `eth_getBlockX` and `eth_getUncleX` responses. 
The field equals the sum of the block's difficulty plus its uncles' difficulty.

Add cumulativeDifficulty field to BlockResultDTO

---

rskj-core/src/main/java/co/rsk/core/TransactionExecutorFactory.java
rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/test/java/org/ethereum/core/TransactionExecutorTest.java

Since the reduction of MAX_DEPTH on commit aaa88a386, this thread
is deprecated, as it helped alleviate a memory issue when depth was
way too big, but now depth is capped so this should no longer be a
issue.
Should improve performance too as a nice side effect :)

remove thread on which the vm executes programs

---

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java

Avoid saving end state when reexecute a transaction

Improve transaction execution with trace in BlockExecutor

---

rskj-core/src/main/java/co/rsk/core/BlockDifficulty.java
rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/co/rsk/mine/BlockToMineBuilder.java
rskj-core/src/main/java/org/ethereum/core/BlockFactory.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderBuilder.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java
rskj-core/src/test/java/co/rsk/core/BlockFactoryTest.java
rskj-core/src/test/java/co/rsk/core/BlockTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/co/rsk/net/NetBlockStoreTest.java
rskj-core/src/test/java/co/rsk/validators/BlockDifficultyValidationRuleTest.java
rskj-core/src/test/java/org/ethereum/TestUtils.java
rskj-core/src/test/java/org/ethereum/core/BlockHeaderBuilderTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/DifficultyTestCase.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java
rskj-core/src/test/java/org/ethereum/validator/DifficultyRuleTest.java
rskj-core/src/test/java/org/ethereum/validator/ParentGasLimitRuleTest.java
rskj-core/src/test/java/org/ethereum/validator/ParentNumberRuleTest.java

This new class serves as a more flexible alternative to the newHeader construction methods from BlockFactory
Pending work: decouple BlockHeaderBuilder creation from BlockFactory. There may be some places where it should be carefully thought how the `ActivationConfig` parameter should be obtained to inject into the constructor.
This PR decouples the BlockHeaderBuilder changes from https://github.com/rsksmart/rskj/pull/1171

Introduce BlockHeaderBuilder class

---

rskj-core/src/main/java/org/ethereum/vm/program/Program.java

The changed logging lines were mistakenly using a `{number}` positional syntax that's not actually used in the logging methods, instead `{}` simply replaces the corresponding parameter that has been passed. Add further confusion, if the last parameter is an exception, it should not be referenced in the format string, instead the stack trace is printed below the string. 
So to make the fix I removed the 0 from `{0}` and also I removed the format reference to the exception parameter.

Fix minor debug logging error in Program class

---

rskj-core/src/main/java/co/rsk/net/BlockSyncService.java

The `unknownBlockHashes` attribute in `BlockSyncService` used to have a purpose before but that purpose was removed in this previous commit: https://github.com/rsksmart/rskj/commit/89c206a078351d978aede7e81dae4a2b8de5922f 
Instead, currently it's a Map that's being written to, but it is never read from. This PR removes the attribute entirely.
This will fix a LGTM warning.

Remove unused unknownBlockHashes attribute in BlockSyncService

---

rskj-core/src/main/java/org/ethereum/db/TrieKeyMapper.java
rskj-core/src/test/java/org/ethereum/db/TrieKeyMapperTest.java

Cache was only checked but not element added.
Added a line where the element is added before returning it. 
And added a Unit Test for verifying the functionality.

TrieKeyMapper - accountKeys cache not initialized (LGTM alert).

---

rskj-core/src/main/java/org/ethereum/util/CompactEncoder.java

Ignores [LGTM Warning](https://lgtm.com/projects/g/rsksmart/rskj?mode=tree&ruleFocus=2049320662)
Related method it's only used for testing and related tests are not compromised by the out of bounds exception.

Ignoring lgtm alert

---

rskj-core/src/main/java/co/rsk/net/eth/LightClientHandler.java
rskj-core/src/main/java/co/rsk/net/light/MessageVisitor.java
rskj-core/src/main/java/co/rsk/net/light/message/AccountsMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/BlockBodyMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/BlockHeaderMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/BlockReceiptsMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/CodeMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetAccountsMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetBlockBodyMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetBlockHeaderMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetBlockReceiptsMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetCodeMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetStorageMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/GetTransactionIndexMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/LightClientMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/StatusMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/StorageMessage.java
rskj-core/src/main/java/co/rsk/net/light/message/TransactionIndexMessage.java

Created a visitor pattern to replace the ugly switch we had.
The only concern is the creation of the Visitor each time a new message is created. This is because a message need the ChannelHandlerContext passed to the channelRead0 function, so the context is passed in the constructor.
Other possible solutions:
1. setCtx (not that pretty)
2. pass the ctx to the accept method (I really dont like this because ctx is only needed for the Status message, and this would mean we have to change the whole signature of both accept AND apply in EVERY message for just only one)

Message Visitor for the light client handler

---

rskj-core/src/main/java/co/rsk/net/BlockNodeInformation.java
rskj-core/src/main/java/co/rsk/net/TransactionNodeInformation.java
rskj-core/src/test/java/co/rsk/net/BlockNodeInformationTest.java
rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorTest.java

See https://github.com/rsksmart/rskj/issues/1145
maxPeers here is not actually used for anything. maxPeers is hardcoded to 50 and it limits the total size of a HashMap, the attribute blocksByNode of the BlockNodeInformation class. But, that structure is not actually queried at all in the main code, it should be queried by the getBlocksByNode methods (there are two overrides) but it is only queried on the test code. 
For clarity, this PR removes the unused attribute and changes the test code to make the same assertions in a different way.
In this class, maxPeers here is not actually used for anything, literally the attribute is unused. So we are removing the maxPeers from the class and the constructor.
These two attributes simply limit the amount of blocks/transactions remembered by …

Remove unused code from BlockNodeInformation & TransactionNodeInformation

---

rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java
rskj-core/src/main/java/co/rsk/net/light/message/StatusMessage.java
rskj-core/src/test/java/co/rsk/net/LightSyncProcessorTest.java
rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java
rskj-core/src/test/java/co/rsk/net/light/message/StatusMessageTest.java
rskj-core/src/test/java/org/ethereum/net/rlpx/MessageCodecTest.java

TxRelay is used in LC to determine if the newly connected peer is able to relay transactions.

TxRelay added as option in Status message handshake

---

rskj-core/src/main/java/co/rsk/net/light/LightPeer.java

It solves the misunderstanding of the blockheader list variable in light peer. It'll be replaced by a unique header chain and I add the latter as a comment in the code. Also, I added the VisibleForTesting tag in the getBlockHeader method.

light peer modification

---

rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java
rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java
rskj-core/src/main/java/co/rsk/net/light/MessageVisitor.java
rskj-core/src/main/java/co/rsk/net/light/message/GetBlockHeadersMessage.java
rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java
rskj-core/src/test/java/co/rsk/net/LightSyncProcessorTest.java
rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java
rskj-core/src/test/java/co/rsk/net/light/message/GetBlockHeadersMessageTest.java

Basing on the Parity's Light Client Sync protocol, the behavior is the following:
1. GetBlockHeaders message adds the fields **skip** and **reverse**, also we replaced the field **count** to **max**. The **reverse** field alters the way the list of block headers resultant is constructed and returned. Then, the parameters of GetBlockHeadersMessage are **reqid**, **blockhash** which is the starting block, **max**, **skip** and **reverse**.
2. In the message processing, light client processor responses with **max** numbers of blocks. But the difference between each block number (Ni, Ni+1 two sequential block numbers) is for all i, Ni+1 - Ni + 1 = **SKIP**. 
The way light processor returns this is, given a list of numbers (0..Max):
If the reverse option is settled, it'll take the numbers …

Change behavior of GetBlocksHeader message processing

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/net/eth/LightClientHandler.java
rskj-core/src/main/java/co/rsk/net/light/LightMessageHandler.java
rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java
rskj-core/src/test/java/co/rsk/net/LightClientTestUtils.java
rskj-core/src/test/java/co/rsk/net/LightMessageHandlerTest.java
rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java
rskj-core/src/test/java/co/rsk/net/light/LightSyncProcessorTest.java

This PR improves the Light Client Sync protocol with the possibility to process more than one message at the same time, instead of discarding them.
The process is simple: Once a message arrives it is inserted in a FIFO blocking queue (so we can assure each message is inserted correctly from different threads). 
There is a thread which consists only in getting messages from the queue and processing them, in FIFO order. Each message is linked to its own ChannelContextManager, LightPeer and LightClientHandler (for the sync message only).
Testing is done in order to check whether one and several messages are processed correctly, from the same and different Peers. Also a new TestUtils class is created for this purpose (I created a method to return the correct answer for a given GetAccounts …

Message Handler to Support multiple messages from different Light Peers

---

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/test/java/co/rsk/test/DslFilesTest.java
rskj-core/src/test/resources/dsl/reorganization.txt
rskj-core/src/test/resources/dsl/reorganization_different_non_competing_tx.txt
rskj-core/src/test/resources/dsl/reorganization_different_tx_on_both_same_nonce.txt
rskj-core/src/test/resources/dsl/reorganization_same_tx_on_both.txt

As reported in https://github.com/rsksmart/rskj/issues/1127 transactions are being lost in reorganizations.
When a new block is created the method `processBest` of the `TransactionPoolImpl` class is called with the new block, which should calculate the fork, and for each block that is no longer part of the best chain, call `retractBlock` which in turn calls to `addTransaction`.
The current problem is the following: `addTransaction` runs validations on the block, but these validations are run against the wrong AccountState: an account state that is derived from what was the *previous* best block, a block that *included* the same transaction we now want to add again to the transaction pool. This is because currently the `bestBlock` attribute of the `TransactionPoolImpl` is being updated …

Fix issue #1127: Transactions were lost in reorganizations

---

rskj-core/src/main/java/co/rsk/net/discovery/DiscoveryEvent.java
rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java
rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java

This makes the PeerExplorer reply to ping and pongs using the ip and port of the udp packet instead of only the ip plus the port inside the message. 
Without this change, nodes that are behind routers that change the udp port cannot connect to the network succesfully.

Use udp packet port in PeerExplorer

---

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/org/ethereum/core/TransactionSet.java
rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java

The method `TransactionPoolImpl.addTransaction` was modified to consider the adding of queued successors.
This modificacion fixes #1132 and #1130  The tests mentioned in #1130 were added and run without failure.

Fixing transaction pool add transaction behaviour

---

rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java
rskj-core/src/main/java/co/rsk/net/light/state/CommonAncestorSearchSyncState.java
rskj-core/src/main/java/co/rsk/net/light/state/DecidingLightSyncState.java
rskj-core/src/test/java/co/rsk/net/light/LightSyncStateTest.java

- Added a new way to transits to StartRoundSync from genesis. If the best block headers of the light peers is Genesis, its transits directly to StartRoundSync otherwise it transits to SearchCommonAncestor. The last way is when the peers common ancestor is Genesis.
- The maxAmountOfHeaders is stored as a instance variable so when the peer receives a list of block headers in CommonAncestorSearch state, it checks against maxAmountOfHeaders if its correct

StartRoundSync from Genesis

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java

Move `isInputSignedByThisFederator` method from `BridgeSupport` to `BridgeUtils`, to be used by the federate node

Move method from BridgeSupport to BridgeUtils

---

rskj-core/src/main/java/org/ethereum/net/MessageQueue.java
rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java

This fixes the bug where a MessageQueue was witnessed accumulating messages that are never sent, creating a memory leak.
The root cause of the bug is due to a race condition that happens when there is a disconnection of a channel at the same time the channel is being promoted to active in the ChannelManagerImpl class. 
How it happens
1. There is a disconnection in the channel. Two things happen here. There is a listener set up on EthereumChannelInitializer for disconnection that ends up calling ChannelManagerImpl#notifyDisconnect with the Channel. This ends up removing the channel from activePeers and/or newPeers collection. There is also the P2pHandler channelInactive method which is also called on the disconnection by Netty which ends up calling MessageQueue#close, which stops the …

Fix race condition around newPeers in ChannelManagerImpl

---

rskj-core/src/main/java/co/rsk/core/Wallet.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Added logic to check if an account exists before add it to the Wallet.
Now it is possible to added several time the same account using the method `personal_newAccountWithSeed`.
This PR fix this issue adding a logic that checks before add.
Please @ajlopez and @fedejinich take a look of this.

Check if an account exists before add it.

---

rskj-core/src/main/java/co/rsk/util/ListArrayUtil.java
rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java
rskj-core/src/main/java/org/ethereum/core/BlockHeader.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderTest.java
rskj-core/src/test/java/co/rsk/util/ListArrayUtilTest.java

We found out that the conversion of native byte arrays (`byte[]`) to object lists (`List<Byte>`) was adding a bit of overhead when performing merge mining tag lookups in the block's btc coinbase data in `ProofOfWorkRule` as well as in the fork detection data retrieval in `BlockHeader`. So we decided to temporarily use an implementation of the lookup algorithm that uses native types instead of objects. Altough the change is small, we felt it was a good first step before jumping to a faster or complex implementation.

ForkDetectionData retrieval performance

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/remasc/RemascFeesPayer.java
rskj-core/src/main/java/co/rsk/rpc/modules/trace/CallType.java
rskj-core/src/main/java/co/rsk/rpc/modules/trace/ProgramSubtrace.java
rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceAction.java
rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceTransformer.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceModuleImplTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceTransformerTest.java
rskj-core/src/test/java/co/rsk/test/dsl/WorldDslProcessor.java
rskj-core/src/test/java/co/rsk/test/dsltest/WorldDslProcessorTest.java
rskj-core/src/test/resources/dsl/call01.txt
rskj-core/src/test/resources/dsl/create201.txt
rskj-core/src/test/resources/dsl/delegatecall01.txt

This  code fix two issues in current JSON RPC output for `trace_transaction` and `trace_block`:
- `callType` value should be `delegatecall` when the call from contract A to contract B was executed via a DELEGATECALL opcode
```
{
"action": {
"callType": "delegatecall",         //   <-------------- this value
"from": "0x9653f73cbf95b738a44019aeb1efc4e1b5632d71",
"gas": "0x3fd19",
"input": "0xb63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000180000000000000000000000000d5d82b6addc9027b22dca772aa68d5d74cdbdf440000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

Fix JSON RPC trace_transaction and trace_block

---

rskj-core/src/main/resources/reference.conf

With this pull request the config property `flushNumberOfBlocks` is set to `1000`. Previously default value of it was `20`.
Reason for this is a result of some benchmarking tests that were made.

Set flushNumberOfBlocks to 1000

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java
rskj-core/src/main/java/co/rsk/db/BlocksIndex.java
rskj-core/src/main/java/co/rsk/db/MapDBBlocksIndex.java
rskj-core/src/main/java/org/ethereum/db/BlockStore.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/main/resources/logback.xml
rskj-core/src/test/java/co/rsk/db/HashMapBlocksIndex.java
rskj-core/src/test/java/org/ethereum/db/BlockStoreDummy.java

- Issue
When we a halt of the JVM (on purpose or not), we have a NPE trying to commit the changes on the indexDB. So last blocks were lost. 
The problem was that the DB was initialised with a property of closeOnShutdown, so when we try to flush it's already closed (shouldn't throw a NPE, but thats because we use an older version of mapdb).
- Solution
What i did was just remove the option of automatically closing the db when shutdown, and do it "manually" after flushing.
- Test
Dont know how to properly test it, i just run a node -> stop it by halting the jvm -> start it again (checking that the last block number its the same as when starts).
- Exception thrown
```
Exception in thread "Thread-3" java.lang.NullPointerException
at org.mapdb.StoreDirect.indexValGet(StoreDirect.java:1575)
at …
```

Fix index DB shutdown NPE

---

rskj-core/src/main/resources/config/regtest.conf

Iris should not be enabled even in regtest until we actually release that network upgrade

Disable Iris network upgrade in regtest

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/RegisterBtcTransactionException.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java

Move lock, release and migration logic to their own methods
Refactor lock validations to extract refund logic from them

Refactor RegisterBtcTransaction

---

rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorMinimuGasPriceValidator.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/main/resources/config/devnet.conf
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/vm/VMTest.java

This PR aims 
- to move [this](https://github.com/rsksmart/rskj/pull/991) other PR into "hardfork mode"
- Fix [this](https://github.com/rsksmart/rskj/issues/1272) issue
According to the [EIP-211](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-211.md)
```
If the call-like opcode is executed but does not really instantiate a call frame (for example 
due to insufficient funds for a value transfer or if the called contract does not exist), 
the return data buffer is empty.
```
Since VM code it's critical, we've decided to implement it as part of hardfork.
I've also added elements to `ConsensusRule` & `NetworkUpgrade` enums to be used in the future network upgrade
NOTE: `ConsensusRule` name (eip211Compatibility) will be changed

Clean returnDataBuffer for call-like opcodes

---

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/vm/OpCode.java
rskj-core/src/main/java/org/ethereum/vm/OpCodes.java
rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

This code implements the original Ethereum Improvement Proposal 2315: [Simple Subroutines for the EVM](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2315.md)
It adds three new opcodes to the virtual machine: BEGINSUB, RETURNSUB, JUMPSUB, and a return stack to keep the return program counters.
Many of the tests described in the original IP were implemented in code.
As with JUMPDEST, at the beginning of the execution of a contract, the valid BEGINSUB are scanned, in order to reject any spurius BEGINSUB.

Subroutines in EVM

---

rskj-core/src/main/java/co/rsk/peg/PeginInformation.java
rskj-core/src/test/java/co/rsk/peg/PeginInformationTest.java

This class is responsible for parsing a btc lock tx and obtaining the RSK address where the funds should be transferred to, and a BTC refund address in case the lock can not be completed. This information is obtained from peg-in instructions included in an output with OP_RETURN in the tx, or from the tx sender using BtcLockSender class.

Create PeginInformation class

---

rskj-core/src/main/java/co/rsk/crypto/Keccak256.java
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java
rskj-core/src/main/java/org/ethereum/util/ByteUtil.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionReceiptDTOTest.java
rskj-core/src/test/java/org/ethereum/util/ByteUtilTest.java

This sets the length of the `root` field that's being returned by `eth_getTransactionReceipt` JSON-RPC call to 32 bytes.
Right now rskj returns 0x00,0x01 instead of 0x0...0 and 0x0...1 (32 bytes) for the `root` field. This makes some js libraries incompatible with rskj.
This change is required for the rskj node to be compatible with client libraries at the JSON-RPC level.
JSON-RPC response of `eth_getTransactionReceipt` has been checked.

Fixed length of root field in tx receipt response

---

rskj-core/src/main/java/co/rsk/net/BlockProcessResult.java
rskj-core/src/main/java/co/rsk/net/BlockSyncService.java
rskj-core/src/test/java/co/rsk/net/BlockProcessResultTest.java
rskj-core/src/test/java/co/rsk/net/simples/SimpleBlockProcessor.java

Per #1346: 
Add static factory methods for two types of `BlockProcessResultTest` and make ctor protected. 
Refactoring. 
All unit tests pass

#1346: Add static factory methods for BlockProcessResult

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/exception/RskJsonRpcRequestException.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleDLSTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/resources/dsl/eth_module/revert_reason.txt

RSK is not notifying the revert reason when a transaction invoked by RPC is reverted. This PR decodes and adds the revert reason to the exception thrown in such case.

Preserve Txn revert reason

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

Previously only the derivationHash was saved, now the hash of the original bitcoin transaction is added as a joint key.

Modify the signature and the way the derivationHash is saved.

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/FastBridgeCompatibleBtcWallet.java
rskj-core/src/main/java/co/rsk/peg/fastbridge/FastBridgeFederationInformation.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/FastBridgeCompatibleBtcWalletWithSingleScriptTest.java
rskj-core/src/test/java/co/rsk/peg/FastBridgeCompatibleBtcWalletWithStorageTest.java

Change Sha256Hash to Keccak256 type for parameter DerivationArgumentsHash in getFastBridgeDerivationHash, createFastBridgeFederationInformation, BridgeStorageProvider, etc and related test cases.

Change Sha256Hash to Keccak256 type

---

rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java
rskj-core/src/main/java/co/rsk/validators/Rskip92MerkleProofValidator.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/validator/Rskip92MerkleProofValidatorTests.java

This change limits the RSK merged mining merkle proof length to max of 480 bytes.

Limit the RSK merged mining merkle proof

---

.circleci/config.yml

While there, rename jvm-executor to rskj-executor to avoid confusion.

CI: migrate SonarQube docker image to JDK 11

---

rskj-core/src/main/java/co/rsk/core/Coin.java
rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
rskj-core/src/test/java/co/rsk/core/CoinTest.java
rskj-core/src/test/java/org/ethereum/listener/GasPriceTrackerTest.java

Considering best block's MGP in `eth_getPrice`.
This change takes into account best block's MGP while calculating gas price in the `eth_getPrice` JSON-RPC method. This resolves #1343
Using unit tests

Consider MGP in eth_getPrice

---

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

Remove virtual machine opcodes execution `TXINDEX`, `DUPN`, `SWAPN`
In order to keep compatibility with any  future Ethereum virtual machine (evolution of opcodes), we remove the mentioned ones.
Using code tests, with fork activation and without activation
This opcodes where never used or described in documentation, AFAIR

Remove non-standard opcodes TXINDEX; DUPN, SWAPN

---

rskj-core/src/main/java/co/rsk/rpc/netty/Web3ResultHttpResponseHandler.java

Add a `Content-Type` header to JSON RPC responses, with value `application/json` to solve #1365 1365
Current code does not returns the content type header in the responses to JSON RPC invocations.
It was tested using `curl`

Content type in JSON RPC response

---

rskj-core/src/main/java/co/rsk/core/Coin.java
rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
rskj-core/src/test/java/co/rsk/core/CoinTest.java
rskj-core/src/test/java/org/ethereum/listener/GasPriceTrackerTest.java

Considering best block's MGP in `eth_getPrice`.
This change takes into account best block's MGP while calculating gas price in the `eth_getPrice` JSON-RPC method.
Using unit tests
*fit: 2.2-rc*

[PAPYRUS-2.2.0-rc] Consider MGP in eth_getPrice

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/co/rsk/net/handler/TxPendingValidator.java
rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorNonceRangeValidator.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorNonceRangeValidatorTest.java

This change makes the number of account slots for pending transactions in a tx pool configurable.
Instead of using hardcoded value, this allows us to configure it.
unit tests and running the node locally
*fit: 2.2-rc*

[PAPYRUS-2.2.0-rc] Make num of account slots for pending txs configurable

---

rskj-core/src/main/java/co/rsk/rpc/netty/Web3ResultHttpResponseHandler.java

*fit: 2.2-rc*
Add a `Content-Type` header to JSON RPC responses, with value `application/json` to solve #1365 1365
Current code does not returns the content type header in the responses to JSON RPC invocations.
It was tested using `curl`

[PAPYRUS-2.2.0-rc]  Content type in JSON RPC response

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

*fit: 2.2-rc*
Fix #1380 JSON/RPC API returns incorrect v value for EIP155 transactions
Compatibility with Ethereum ecosystem
Using new test code exercising `TransactionResultDTO`
New integration tests are recommended

Fix v value in JSON RPC transaction result (2.2.0)

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java
rskj-core/src/main/java/co/rsk/logfilter/BlocksBloom.java
rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomBuilder.java
rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomProcessor.java
rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomService.java
rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomStore.java
rskj-core/src/main/java/org/ethereum/db/BlockStore.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/logback.xml
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/bc/BlockChainFlusherTest.java
rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomBuilderTest.java
rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomProcessorTest.java
rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomServiceTest.java
rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomStoreTest.java
rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomTest.java
rskj-core/src/test/java/org/ethereum/db/BlockStoreDummy.java
rskj-core/src/test/resources/logback.xml

*fit: 2.2-rc*
Using a new configuration option, the build and save of block blooms data could be executed within the normal operation of the node. This data is used to retrieve log information efficiently.
Usually, this block blooms information is used only in nodes that has JSON RPC open, and log query operation enabled. And with the first query, the data is build and saved. But even with this feature, the operation could take many minutes and resources from the node.
So, this new code allow the build of the same data along the blockchain node normal processing, ie, during long synchronization or normal synchronization. To do this, a new internal service was added, and it is activated by configuration (the default value is not activated),
It has code tests, and also was tested running a …

Build Block Blooms Database (2.2.0)

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleDLSTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/co/rsk/util/TestContract.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

This fixes compatibility issue for empty contracts return result.
Empty contract return should be `0x`, but it’s `0x00` instead.
To be compatible with Ethereum JSON-RPC clients `0x` should be returned by `eth_call` for an empty contract instead of `0x00`.
Using unit tests
*fit: node-call-changes*

Fixed issue with empty contract's return result

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/util/TimeProvider.java
rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorBuilder.java
rskj-core/src/test/java/co/rsk/validators/BlockTimeStampValidationRuleTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

This implementation checks if BTC and RSK block timestamps are close enough.
This extends `BlockTimeStampValidationRule` class with the timestamps validation logic and its activation in the next HF.
This aims to prevent a merge-miner attacker from mining old RSK blocks with the current Bitcoin hashrate. 
Using unit tests and running the node locally.

Implemented timestamp linking validation

---

rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

Fix #1380 JSON/RPC API returns incorrect v value for EIP155 transactions
Compatibility with Ethereum ecosystem
Using new test code exercising `TransactionResultDTO`
New integration tests are recommended

Fix v value in JSON RPC transaction result

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/RepositoryBtcBlockStoreWithCache.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/main/java/org/ethereum/crypto/ECKey.java
rskj-core/src/main/resources/config/testnet.conf
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/logback.xml
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/performance/LockWhitelistTest.java
rskj-core/src/test/java/co/rsk/peg/performance/LockingCapTest.java

Make BtcBlockStore cache configurable, with 2 options: depth and size.
Add more logs, to identify possible issues in long sync.
When making a long-sync in testnet, I found some range of blocks with a lot of BTC blocks, which makes it really hard to process. Increasing the cache, would make it faster and would take more advantage of this cache. As the configuration of this cache are now static fields, I made this change so we could configure it depending on the chain we are. 
For the purpose of this PR, we wanted to change only testnet params.
Syncing with Boton instance on testnet.
Properties:
- cache.btcBlockStore.size: default to 10k
- cache.btcBlockStore.depth: default to 5k (depth is calculated by the height of the block)

Make BtcBlockStore cache configurable

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java

It includes a new function in bridgeMethods called receiveHeader, which will be public and receives a single header as an input parameter, being able to return errors.
This function can be used from RSKIP200
In turn, receiveHeaders is no longer public with this same RSKIP.

Creation of receiveHeaders function

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

Time limit control between calls for receiveHeader
It includes a time limit between calls to receiveHeaders and control of some errors:
-1 -> time in calls is less than defined by constant
- 99 -> exception during add method

Receive headers calculate period time

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

Check the depth of the block, taking into account the depth in the storage of the previous block.
If the depth of the block is too old, then it returns error. If it can't find the previous block in storage, then it also returns error.
The new errors that are introduced here are:
-2 -> RECEIVE_HEADER_BLOCK_TOO_OLD
-3 -> RECEIVE_HEADER_CANT_FOUND_PREVIUOS_BLOCK

Depth limit for Receive Header.

---

rskj-core/src/main/java/co/rsk/Start.java
rskj-core/src/main/java/co/rsk/config/NodeCliFlags.java
rskj-core/src/main/java/co/rsk/util/PreflightCheckException.java
rskj-core/src/main/java/co/rsk/util/PreflightChecksUtils.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/test/java/co/rsk/util/PreflightChecksUtilsTest.java

Added preflight checks to stop node from running when Java Version is not supported.
Java version check can be avoided if the `--skip-java-check` flag is set.
Some people use jre16 or alike for running rskj node. We only support LTS versions 8 and 11, so we should restrict in the code versions of java we support.

JVM version preflight check

---

rskj-core/src/main/java/co/rsk/scoring/InetAddressUtils.java
rskj-core/src/main/java/org/ethereum/crypto/signature/Secp256k1.java

Updating wrong Javadoc tags
As described in LGTM [documentation](https://lgtm.com/rules/2049510531/): "The Javadoc comment for a method or constructor should always use non-empty @param values that match actual parameter or type parameter names."
Changes does not require tests since code was not changed.

Fixing javadoc tags

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestPowerMock.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

When the Federation change voting process finishes, the Bridge emmits a commit_federation event. This event can be used to provide a blockchain proof of the Federation address when requested. Nowadays doing this would imply navigating the blockchain to determine when it was emmited, or constantly monitoring said events.
This RSKIP proposes adding on-chain information to easily fetch the block where the Federation was changed for the last time. With the block, a system could provide proof that it belongs to the mainchain.
Additionally, once a Federation migration process finishes, the retiring Federation is removed. This RSKIP proposes to keep the last retiring Federation address in storage, to be used in case there are outstanding funds to migrate after the retiring age.
When a user gets …

[RSKIP186] Active Federation creation block height registration

---

rskj-core/build.gradle

Missing dependency at `jar` task
Now `jar` task dependsOn `generateResources`
This PR aims to fix this [described issue](https://github.com/rsksmart/rskj/issues/1456) 
- Builded the project without this dependecy and then sent a JSON RPC request => PAPYRUS-dev
- Builded the project with this dependecy and then sent a JSON RPC request => PAPYRUS-someHash
- Run the entire test suite. 
- An integration test is needed to test it properly

Missing dependency at jar task

---

rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionReceiptDTOTest.java

Remove the `root` field from Transaction Receipt DTO (Data Transfer Object) used in JSON RPC serialization
It should solve #1328 
The `root` field was never used in current RSK testnet and mainnet, so we don't need to implement it as a hard fork.
Some test code was added, testing the result of other field, `status`.
I recommend intergration tests for this feature

Removing root field from TransactionReceiptDTO

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionInstant.java
rskj-core/src/main/java/org/ethereum/rpc/exception/RskJsonRpcRequestException.java
rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java

When a transaction is mined immediately (when the automine is enabled, ie using `-Dminer.client.autoMine=true`, if an error occurs (ie out of gas, revert) a message describing the problem is returned
Some node implementation used for testing (like ganache and hardhat) have a node that executes immediately a transaction (like our autominer) but also they return a message in case an error occurs. If the error was raised by a unsatisfied require (in Solidity) with an associated description message, that message is included in the returned JSON object.
It was tested manually, maybe a better code test could be implemented
The message added to `eth_sendTransaction` and `eth_sendRawTransaction` was taken from `eth_call` implementation. But it should be changed for compatibility with the …

Send Transaction and Send Raw Transaction returns an error message when automine is enabled

---

rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/converters/TypeConverterTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

The nonce of a transaction now it is returned WITHOUT leading zeroes
The main motivation is to fix issues with ecosystem tools, like `geth`. In previous changes, other JSON RPC values were adapted to be returned WITHOU leading zeroes, but transaction nonce was not fixed.
With code tests

Return Transaction Nonce as Quantity Value in JSON RPC methods

---

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplUnitTest.java

JSON RPC method `eth_getStorageAt` now returns `0x0` instead of null if the storage cell to be retrieved is empty (the default value is then zero)
Returning null riases some issues with the ecosystem, ie `geth` console and other integration tools
Adding code tests, and manually
Please, we need more info about other `getStorageAt` compatibility. For example, our implementation returns `0x0000000000000000000000000000000000000000000000000000000000000001` when the storage cell contains the value ONE, but `ganache` returns `0x01`. Is it an issue? Which is the value returned by `geth` and other implementations? Maybe they expect `0x1` as in other cases (with leading zeroes removed)

getStorageAt from empty cell now returns 0x0 instead of null

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/main/java/co/rsk/peg/utils/RejectedPegoutReason.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java

A peg-out transaction has a minimum established in the Bridge constants.
This value doesn't take into account the changing nature of the fees.
Ths commit adds a validation to calculate the approximated cost of a peg-out with the current fees per KB of the network.
The cost is calculated considering a transaction with two inputs and two outputs, which is the most common situation ATM.
A peg-out transaction should also generate value for the user, this is, if a peg-out tx costs 400k satoshis and the user is attempting to peg-out 450k, the remainder (50k) won't be of much use for the user. In order to avoid this situation the Bridge now includes a percentage above the fee cost that the peg-out should include, if this is amount is not attained, the peg-out is rejected and funds returned.

Add new check for peg-out minimum considering fees 

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestPowerMock.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java

When a fast bridge Federation UTXO is spent, it probably generates a change UTXO, this change UTXO is then registered via registerBtcTransaction, but the logic in this method detects the transaction as an attempted peg-in, which will be rejected because the FB Federation is a multisig. This will burn the funds because the FB Federation won't register those funds.
Fix:
Extract the standard redeem script from the input using the existing bitcoinj logic, and compare it against the active federations redeem script. If it matches, then don't process the tx as a peg-in
*fed:fb-burning-utxos-fix*

Fast bridge burning utxos fix

---

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/org/ethereum/rpc/Web3.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

This change makes `chainId` a valid call argument at the JSON-RPC level.
Since Truffle version 5.2.5, `chainId` is included as a transaction parameter. The change allows to properly handle JSON-RPC requests from this client. As of now, `chainId` argument is being ignored.
Via JSON-RPC calls.
Fixes #1485

Added chainId to list of valid call args

---

rskj-core/README.md

Add a step to the setup instructions (to run the configure.sh script, so that a local Gradle version can be used when developing).
For new devs to know they can use a local Gradle version (which is compatible with the project - 6.5 at the moment of writing this).
By doing a fresh setup of the project and following the instructions.

Add configure.sh instructions to rskj-core README page

---

rskj-core/src/main/java/co/rsk/jsonrpc/JsonRpcError.java
rskj-core/src/main/java/co/rsk/jsonrpc/JsonRpcInternalError.java
rskj-core/src/main/java/org/ethereum/rpc/exception/RskErrorResolver.java
rskj-core/src/test/java/org/ethereum/rpc/exception/RskErrorResolverTest.java

When doing a JSON RPC request, if an invalid field is sent, then only an internal error is returned.
When a field is invalid a description of the problem is returned Instead of returning and Internal Error without description, e.g., when a "form" field is sent instead of "from", the following message is returned:
> Unrecognized field "form" (8 known properties: ["gasPrice", "value", "gas", "from", "to", "chainId", "nonce", "data"])
Closes https://github.com/rsksmart/rskj/issues/1531
By using Unit Tests and Integration Tests

Adding error handler for invalid fields

---

rskj-core/src/main/java/co/rsk/rpc/netty/Web3HttpServer.java
rskj-core/src/main/java/co/rsk/rpc/netty/Web3HttpStatusCodeProvider.java
rskj-core/src/main/java/co/rsk/rpc/netty/Web3ResultHttpResponseHandler.java
rskj-core/src/test/java/co/rsk/rpc/netty/Web3HttpStatusCodeProviderTest.java

Since the jsonrpc4j keeps on returning internal error HTTP status codes upon JSON-RPC errors (it shouldn't, since the transport layer protocol should be agnostic to JSON-RPC), we add custom logic to handle them.
Inspired on [this](https://github.com/hyperledger/besu/issues/549), any valid JSON-RPC request should generate a JSON-RPC response, the HTTP status code should be 200. No matter if the response is a success or error response.
Calling a method that hasn't been enabled or a method that doesn't exist are valid JSON-RPC requests, therefore the expected response is a JSON-RPC error (and status code = 200)
Any invalid JSON-RPC request (malformed JSON, etc.) should generate a 400 status code.
Issue #1387 
Unit testing

Add custom HttpStatusCodeProvider to adjust to JSON-RPC 2.0 conventions

---

rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java
rskj-core/src/main/java/co/rsk/pcc/NativeMethod.java

Updating multiplications to avoid casting the result to a wider type.
As described in LGTM [documentation](https://lgtm.com/rules/7900075/): "An integer multiplication that is assigned to a variable of type long or returned from a method with return type long may cause unexpected arithmetic overflow."
Using Unit Test

Fixing multiplication cast to wider type

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/core/TransactionArguments.java
rskj-core/src/main/java/org/ethereum/core/TransactionBuilder.java
rskj-core/src/main/java/org/ethereum/rpc/Web3.java
rskj-core/src/main/java/org/ethereum/util/TransactionArgumentsUtil.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleTest.java
rskj-core/src/test/java/org/ethereum/util/TransactionArgumentsUtilTest.java
rskj-core/src/test/java/org/ethereum/util/TransactionTestHelper.java

eth_sendTransaction support 'gasLimit' field #961
Added gasLimit field to Web3.CallArguments and make the necessary treatments in the EthModuleTransactionBase.sendTransaction and PersonalModuleWalletEnabled.sendTransaction. Making 'gas' param overwrite 'gasLimit' if both are provided
https://github.com/rsksmart/rskj/issues/961
Tested on regtest with sendTransaction rpc API:
`{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from": "0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826", "to": "0x7986b3df570230288501eea3d890bd66948c9b79", "gasLimit": "0x76c0", "gasPrice": "0x9184e72a000", "value": "0x186A0"}],"id":73}`
- New feature (non-breaking change which adds functionality)
- [ X ] My change requires a change to the documentat

eth_sendTransaction support 'gasLimit' field #961 plus transaction refactory

---

rskj-core/src/main/java/org/ethereum/net/NodeStatistics.java
rskj-core/src/test/java/org/ethereum/net/NodeStatisticsTest.java

Removing implicit cast operations.
As described in LGTM [documentation](https://lgtm.com/rules/1780084/): Compound assignment statements of the form x += y or x *= y perform an implicit narrowing conversion if the type of x is narrower than the type of y. For example, x += y is equivalent to x = (T)(x + y), where T is the type of x. This can result in information loss and numeric errors such as overflows.

Removing implicit cast

---

rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java
rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabledTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

A new check was added to look for Raw Key Strings containing the "hex prefix' (0x). If the string contains this prefix, then it is removed and the execution continues.
Solves issue #1340.

Adding Support for Raw Keys containing Hex Prefix (0x)

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/rpc/netty/RskWebSocketJsonRpcHandler.java
rskj-core/src/main/java/co/rsk/rpc/netty/RskWebSocketServerProtocolHandler.java
rskj-core/src/main/java/co/rsk/rpc/netty/Web3WebSocketServer.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/rpc/netty/RskWebSocketJsonRpcHandlerTest.java
rskj-core/src/test/java/co/rsk/rpc/netty/Web3WebSocketServerTest.java

Any websocket connection will be closed after a certain write timeout. Currently set to 30 seconds but it can be less (I think it should be less).
This implied 
- in adding a `WriteTimeoutHandler` to the `Web3WebSocketServer`
- And creating an `RskWebSocketJsonRpcHandler` to close a connection after exceding the timeout.
- Also renamed `RskJsonRpcHandler` to `RskWebSocketJsonRpcHandler`, since it was only used for the websocket server.
Also take account that I had to modify the `RskWebSocketJsonRpcHandler`, there where two reference counted objects that are producing memory leaks when the connection is closed due to exceding the timeout:
```java
class RskWebSocketJsonRpcHandler {
protected void channelRead0(ChannelHandlerContext ctx, ByteBufHolder msg) {
... 
RskJsonRpcRequest request = …
```

Configurable write timeout for websocket server

---

rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorBuilder.java
rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java
rskj-core/src/test/java/co/rsk/test/DslFilesTest.java

This PR tries to adapt failing tests from Iris3.0, they came up when we tried to merge the `3.0.0-rc` branch into the master branch, by setting the iris activation as default for the entire test suite:
1. `runCreateContractAndPreserveBalance`: activated Iris by default, no need to provide any custom activations
2. `runCreateContractAndPreserveNoBalance`: as mentioned in the TODO comment, added custom activations to disable Iris network upgrade
3. `blockInTheFuture`: refactored to test the previous and current behavior, providing a valid `bitcoinTimestamp` according to the `validPeriod`

Adapt expected failing tests from release candidate

---

rskj-core/src/main/java/org/ethereum/rpc/CallArguments.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java

As some js libraries started to send `type` parameter in JSON-RPC calls that expect call arguments (e.g. `eth_sendTransaction` or `eth_estimateGas`), this causes some tests that are using these libraries to fail. This change introduces `type` as expected, non-required field which is simply being ignored.
Motivation behind this is to prevent failing of those JSON-RPC endpoints when the `type` field is being provided by a client.

Added type arg to CallArguments

---

rskj-core/src/main/java/org/ethereum/rpc/Web3.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java

As some js libraries started to send type parameter in JSON-RPC calls that expect call arguments (e.g. eth_sendTransaction or eth_estimateGas), this causes some tests that are using these libraries to fail. This change introduces type as expected, non-required field which is simply being ignored.
Motivation behind this is to prevent failing of those JSON-RPC endpoints when the type field is being provided by a client.

Added type arg

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/core/TransactionBuilder.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/CallTransactionTest.java
rskj-core/src/test/java/co/rsk/test/builders/TransactionBuilder.java
rskj-core/src/test/java/co/rsk/test/builderstest/TransactionBuilderTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/BlockResultDTOTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

Continuing this [previous PR](https://github.com/rsksmart/rskj/pull/1490) from @ajlopez, adds support to skip REMASC transaction from blocks on JSON RPC requests. This feature it's disabled by default
Use `-Drpc.skipRemasc=true`
There are some Ethereum's ecosystem tools that relies on transactions with gasUsed > 0 (since there are no transactions with gasUsed > 0 on eth). Checkout this example https://github.com/rsksmart/rskj/issues/1484
In RSK every block has a tranaction, which is part of the consensus, named REMASC. This special case differs from other ones beacause it has `gasUsed == 0`.
In order to provide a better UX and compatibility we provide a mechanism to filter this Transaction from the returned block/s on JSON RPC requests (IE `eth_getBlockByNumber` or `eth_getBlockByHash`). …

Skip REMASC Transaction (Configurable)

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/rpc/netty/RskWebSocketServerProtocolHandler.java
rskj-core/src/main/java/co/rsk/rpc/netty/Web3WebSocketServer.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/rpc/netty/Web3WebSocketServerTest.java

This PR intends to solve a bug when processing incomplete or chunked requests received through the Websocket endpoint.
This PR aims to provide a solution to a bug causing chunked requests sent to the Rskj WebSocket Endpoint to be treated as separate requests.
This bug was discovered when using the official Ethereum Go client to send a transaction. The geth client sends data > 1024 bytes in chunks. That caused the Web3WebSocketServer to read every chunk of 1024 bytes as a new request, failing in consequence to process it as a valid json.
Adding the WebsocketFrameAggregator handler to the pipeline provides a way to properly handle those chunked requests.
This patch was tested using geth client with successful results
A new test was added in Web3WebSocketServerTest.java called …

Properly handle chunked requests on WebsocketServer

---

rskj-core/src/main/java/co/rsk/trie/Trie.java

Calculate Trie.getHash without additional storage access
Originated from https://github.com/rsksmart/rskj/pull/1545
Fix issue #1511
Changes from #1526 are also include, please don't review those lines (not related with children size calculation)

Fix Trie getHash

---

rskj-core/src/main/java/org/ethereum/core/BlockHeader.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderTest.java

This change allows to cache a block hash after first call to `BlockHeader.getHash()` and reuse cached value in next calls.
See https://github.com/rsksmart/rskj/issues/1584
unit tests / running node in local env.

Reused calculated block hash

---

rskj-core/src/main/java/co/rsk/cli/tools/ExecuteBlocks.java
rskj-core/src/main/java/co/rsk/db/importer/BootstrapImporter.java
rskj-core/src/main/java/co/rsk/trie/MultiTrieStore.java
rskj-core/src/main/java/co/rsk/trie/NodeReference.java
rskj-core/src/main/java/co/rsk/trie/Trie.java
rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
rskj-core/src/test/resources/logback.xml

It removes a trie node set, add an internal boolean flag to each trie node to knows if the node was already saved, improve the retrieval of the node (no get hash calculation is needed for adding the retrieved node to the removed set), improve save trie without visiting unloaded child nodes
Originated from https://github.com/rsksmart/rskj/pull/1526
It solves #1509 and #1510
Additionally to the usual code tests, the execution of blocks from a testnet node was executed:
java -cp rskj-core-3.0.0-triefix-all.jar -Dlogback.configurationFile=<logbackfile> -Dblockchain.flushNumberOfBlocks=1000 -Dcache.states.max-elements=1000000 co.rsk.cli.tools.ExecuteBlocks 1672391 1673139 --testnet
There are new logs, to obtain some additional information from TrieStoreImpl and DataSourceWithCache. The above …

Improve Trie Node Retrieve and Save

---

rskj-core/src/main/java/co/rsk/trie/NodeReference.java
rskj-core/src/main/java/co/rsk/util/NodeStopper.java
rskj-core/src/test/java/co/rsk/mine/MinerUtilsTest.java
rskj-core/src/test/java/co/rsk/trie/NodeReferenceTest.java

Now we throw and exception when a node can not be retrieved from database.
Fixing the bug reported by @SergioDemianLerner  on issue [#1549](https://github.com/rsksmart/rskj/issues/1549).
Extracted from the issue "When the node cannot be retrieved from storage, it returns an optional empty trie.
However, the inexistence of a node in the database is NOT a a normal situation, but a fatal exception that should shutdown the node as soon as possible. Anything you do in this situation can be used to fork the network."
Unit Tests
fixes https://github.com/rsksmart/rskj/issues/1549

Fixing semantic confusion

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/rpc/ExecutionBlockRetriever.java
rskj-core/src/main/java/co/rsk/rpc/Web3InformationRetriever.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/test/java/co/rsk/rpc/ExecutionFoundBlockRetrieverTest.java
rskj-core/src/test/java/co/rsk/rpc/Web3InformationRetrieverTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

This PR adds support of the "pending" block identifier (see [The default block parameter](https://eth.wiki/json-rpc/API#the-default-block-parameter) section).
This capability has been introduced in the following JSON-RPC methods:
- `eth_getBlockByNumber`
- `eth_getTransactionByBlockNumberAndIndex`
- `eth_getUncleCountByBlockNumber`
- `eth_getUncleByBlockNumberAndIndex`
Fixes #1578.
Besides already implemented "earliest" and "latest" block identifiers, add support of "pending", as described in the [spec](https://eth.wiki/json-rpc/API#the-default-block-parameter).

Added support of pending block identifier

---

.gitignore
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/net/MessageCounter.java
rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/net/MessageCounterTest.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java
rskj-core/src/test/java/co/rsk/net/utils/TransactionUtils.java
rskj-core/src/test/java/co/rsk/util/CacheElementTest.java

add control to message queue size by peer
To avoid overflow of messages if the local node is to busy processing
unit tests
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the code style of this project.
- [ X ] Tests for the changes have been added (for bug fixes / features)

add control to message queue size by peer

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWalletEnabled.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Improve transaction tests
For more information: https://github.com/rsksmart/rskj/issues/965
Basically there are leading zeros that are being truncated in Java and we need to keep the size to keep consistency for the decoding process.
For more information: https://github.com/rsksmart/rskj/issues/965
Seems kind of hard to test this since we need leading zeros for either R or S properties after signing the data.

Added fixed size to the signature response of eth_sign

---

rskj-core/src/main/java/co/rsk/core/NetworkStateExporter.java
rskj-core/src/main/java/co/rsk/core/bc/AccountInformationProvider.java
rskj-core/src/main/java/co/rsk/core/bc/PendingState.java
rskj-core/src/main/java/co/rsk/db/RepositorySnapshot.java
rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java
rskj-core/src/main/java/co/rsk/trie/Trie.java
rskj-core/src/main/java/org/ethereum/db/MutableRepository.java
rskj-core/src/test/java/co/rsk/core/NetworkStateExporterTest.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java

The function ext_dumpState() didn't work in Mainnet for several reasons:
1) It threw an exception when getCode() returns null
2) It takes too long to finish (more than 30 minutes)
3) It exhaust all available memory
This PR fixes all 3.
It fixes 1 by returning "" (empty string) when the code is missing.
It fixes 2 and 3 by allowing partial requests.
Three (3) arguments are added:
* String account,
* boolean exportStorageKeys
* boolean exportCode
The argument account, if non-empty, generates a dump limited to a single account. If empty, all accounts are processed.
The argument exportStorageKeys enables or disables the dump of contract storage key/values.
The argument exportCode enables or disables the dump of the contract code.
Also a new field "codeHash" was added to enable first …

Fixed ext_dumpState (it didn't work in Mainnet) / added partial export

---

rskj-core/src/main/java/co/rsk/NodeRunnerImpl.java
rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/Start.java
rskj-core/src/main/java/co/rsk/cli/tools/StartBootstrap.java
rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceTable.java
rskj-core/src/test/java/co/rsk/NodeRunnerImplTest.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java

This adds bootstrap node launcher to the list of cli tools
This allows to run an RSK node in the special "bootstrap" mode, which means that the only peer discovery protocol is active, all other capabilities, like syncing, blocks / txs propagation etc., are disabled. This should offload the bootstrap node from other responsibilities and allow it to focus only on helping other peers to boot.
The bootstrap node can be started, for example, via the following command:
```java
java -cp ./rskj-core-3.1.0-SNAPSHOT-all.jar co.rsk.cli.tools.StartBootstrap --testnet
```

Added bootstrap node into cli tools

---

rskj-core/src/main/java/co/rsk/core/DifficultyCalculator.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/NetworkUpgrade.java
rskj-core/src/main/resources/config/devnet.conf
rskj-core/src/main/resources/config/main.conf
rskj-core/src/main/resources/config/regtest.conf
rskj-core/src/main/resources/config/testnet.conf
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/RskContextTest.java
rskj-core/src/test/java/co/rsk/jsontestsuite/LocalBasicTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/resources/json/BasicTests/difficulty1.json

Difficulty drop in Testnet should drop to a higher difficulty (current one is too low)
Testnet it's processing a lot a blocks when the following condition happens:
1. Miner with a lot of hardware resources gets in.
2. Block Validation Difficulty Increases.
3. Miner with a lot of hardware leaves the net.
4. Difficulty drops really fast at a point that Miner with low resources can process blocks every second
This change will ensure Testnet consensus to happen so fast
Added 2 tests for it

Changed difficulty min value for testnet

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/cli/tools/IndexBlooms.java
rskj-core/src/main/java/co/rsk/config/NodeCliFlags.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomStore.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/util/MapSnapshot.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/RskContextTest.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomStoreTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
rskj-core/src/test/java/org/ethereum/util/MapSnapshotTest.java

This introduces some performance improvements to the `eth_getLogs` JSON-RPC method.
To index block blooms which are not indexed yet, this PR adds a new cli tool - `IndexBlooms`. See motivation section for more details.
The `eth_getLogs` JSON-RPC call consumes lots of resources, especially when it's triggered on a long block range to retrieve historical data. One way to improve this is to use blocks' bloom filters. Bloom filters are already part of each RSK block, but iterating over each block in a requested range is still time consuming operation, as it requires retrieving blocks from a db.
To improve this some time ago there were introduced "combined" bloom filters for block batches (by default, each such batch has 64 blocks), so during the iteration process we can skip some block …

getLogs perf improvements

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/org/ethereum/net/rlpx/FrameCodec.java

**Try** blocks were replaced by **Try With Resources** blocks.
As described in LGTM [documentation](https://lgtm.com/rules/2980072/): "Ensure that the resource is always closed to avoid a resource leak. Note that, because of exceptions, it is safest to close a resource properly in a finally block. (However, this is unnecessary for subclasses of StringWriter and ByteArrayOutputStream.) For Java 7 or later, the recommended way to close resources that implement java.lang.AutoCloseable is to declare them within a try-with-resources statement, so that they are closed implicitly." 

Fixing potential resource leak

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java
rskj-core/src/main/java/co/rsk/cli/tools/RewindBlocks.java
rskj-core/src/main/java/co/rsk/cli/tools/ShowStateInfo.java
rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java
rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/main/java/co/rsk/util/ExecState.java
rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java
rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
rskj-core/src/test/java/co/rsk/RskContextTest.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplInvalidTest.java
rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java
rskj-core/src/test/java/org/ethereum/core/genesis/BlockchainLoaderTest.java

This tries to mitigate an issue of data inconsistency after improper node shut down.
This also adds a new capability to the `RewindBlocks` cli tool, which allows to find minimum inconsistent block number as well as to "rewind" inconsistent blocks(`fmi` and `rbc` cli flags respectively).
Recommended ways to stop the node is to use `Ctrl+C` or via the `kill -TERM <PID>` command.
Sometimes (rather rarely), if the node is not properly shut down, for instance, when it's killed via `kill -KILL <PID>`, stopping an IDE debugger or after machine powering off, the database goes into the inconsistent state - very often when a best block's state root hash points to a missing record in the states db.
This PR adds a few tricks to mitigate the issue, for instance, blocks are flushed after the trie …

Mitigated db inconsistency issue after improper node shutdown

---

rskj-core/src/main/java/co/rsk/remasc/RemascTransaction.java
rskj-core/src/main/java/org/ethereum/core/Transaction.java

Documented RemascTransaction check usage across the platform
Basically we are documenting the usage of:
```
obj instanceof RemascTransaction
```
and 
```
transaction.isRemascTransaction(x, y)
```
Since they are used on multiple scenarios but with the goal, we need to make sure things are clear.
This issue https://github.com/rsksmart/rskj/issues/1582, wants to refactor the check to determine whether a transaction is remasc or not but the refactor is not worth since it's being used inconsistently, but not in a bad way, in multiple places.

Documented RemascTransaction check usage across the platform

---

rskj-core/src/main/java/co/rsk/rpc/netty/JsonRpcWeb3ServerHandler.java
rskj-core/src/main/java/co/rsk/util/CustomJsonRpcBasicServer.java
rskj-core/src/test/java/co/rsk/rpc/netty/Web3HttpServerTest.java

Validating id property in json request.
JSON RPC responses of empty HTTP200 status responses, when sending request without id
This issue id the motiviation: https://github.com/rsksmart/rskj/issues/408.
Basically is not following `geth` standards.

Validating request content before processing the request itself

---

rskj-core/src/main/java/co/rsk/net/discovery/message/FindNodePeerMessage.java
rskj-core/src/main/java/co/rsk/net/discovery/message/NeighborsPeerMessage.java
rskj-core/src/main/java/co/rsk/net/discovery/message/PeerDiscoveryMessage.java
rskj-core/src/main/java/co/rsk/net/discovery/message/PeerDiscoveryMessageFactory.java
rskj-core/src/main/java/co/rsk/net/discovery/message/PingPeerMessage.java
rskj-core/src/main/java/co/rsk/net/discovery/message/PongPeerMessage.java
rskj-core/src/test/java/co/rsk/net/discovery/PeerMessagesTest.java
rskj-core/src/test/java/co/rsk/net/discovery/message/FindNodePeerMessageTest.java
rskj-core/src/test/java/co/rsk/net/discovery/message/NeighborsPeerMessageTest.java
rskj-core/src/test/java/co/rsk/net/discovery/message/PingPeerMessageTest.java
rskj-core/src/test/java/co/rsk/net/discovery/message/PongPeerMessageTest.java

Validate _messageId_ format when responding to received _Node Discovery Messages_ to ensure it is a valid UUID before sending a response message that contains it.
There’s no check of _messageId_ format during _PeerDiscoveryMessages_ parse therefore an attacker can send any payload to make server response with the same payload. With UDP packet spoofing an attacker can put any src IP address to make server send response to the specified address. Therefore UDP packet containing attacker’s payload can be relayed inside the network where RSKj is deployed to attack other internal services (SSRF)

Validate messageid format to UUID

---

rskj-core/src/main/java/co/rsk/core/Wallet.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
rskj-core/src/main/java/org/ethereum/datasource/HashMapDB.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSource.java
rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java
rskj-core/src/test/java/org/ethereum/datasource/DataSourceWithCacheTest.java
rskj-core/src/test/java/org/ethereum/datasource/LevelDbDataSourceTest.java
rskj-core/src/test/java/org/ethereum/rpc/converters/CallArgumentsToByteArrayTest.java

Allow running contains() on KeyValueDataSource#keys() result 
Use ByteArrayWrapper as return type of KeyValueDataSource#keys() instead of byte[] to ensure expected behavior: contains() working, etc.
https://github.com/rsksmart/rskj/issues/1541

KeyValueDataSource#keys() result should allow contains() call

---

rskj-core/src/main/java/co/rsk/rpc/modules/debug/DebugModuleImpl.java
rskj-core/src/main/java/co/rsk/rpc/modules/debug/DisableOption.java
rskj-core/src/main/java/co/rsk/rpc/modules/debug/TraceOptions.java
rskj-core/src/main/java/org/ethereum/crypto/signature/Secp256k1ServiceBC.java
rskj-core/src/main/java/org/ethereum/crypto/signature/Secp256k1ServiceNative.java
rskj-core/src/main/java/org/ethereum/vm/trace/Op.java
rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTraceProcessor.java
rskj-core/src/test/java/co/rsk/rpc/modules/debug/DebugModuleImplTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/debug/TraceOptionsTest.java
rskj-core/src/test/java/org/ethereum/crypto/signature/Secp256k1ServiceTest.java

Adding tracing options to `debug_traceTransaction` method
As described in linked issue, there are some missing options for `debug_traceTransaction` method. This PR adds the ones regarding storage, memory and stack.
It helps with ecosystem compatibility.
By doing unit and manual tests
- [] Tests for the changes have been added (for bug fixes / features)
Fixes https://github.com/rsksmart/rskj/issues/1553

Adding Tracing Options

---

rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java

Disable by default sco, debug and trace rpc modules in HOP
Disable sco, debug and trace modules
The Security team has already been insisting for quite a long time to disable by default a few RPC modules, for instance, personal, debug etc.
Added unit tests
*ci: rskj-400-rc-ver*

Disable sco debug trace modules

---

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java
rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java
rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java

We made the next change in the PrallelilizeTransactionHandle class:
- bucketBySender: instead of storing the list of buckets where a tx is located given the sender if the sender is in the sequential, no changes are made. If the sender was already stored in a parallel bucket and the Handler is adding another tx with the same sender to the sequential, the sequential number is settled given the sender.
- getBucketCandidates():  Changed the algorithm to a simpler one that returns the bucketId:
-  If the tx sender is in the sequential, goes to the sequential.
-  If there is a collision with more than one key placed in two different buckets, goes to the sequential. Otherwise, if it is the same bucket, goes to that bucket. If there is no collision, it goes to the bucket with gas the less.
- We …

Handler's been refactorized

---

rskj-core/src/main/java/co/rsk/core/TransactionExecutorFactory.java
rskj-core/src/main/java/co/rsk/core/TransactionListExecutor.java
rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/test/java/co/rsk/vm/MinerHelper.java
rskj-core/src/test/java/org/ethereum/core/TransactionExecutorTest.java
rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java

Instead of paying to the REMASC contract…every transaction, the fees are accumulated into a variable and once all of the transactions are processed, the fees are added to the Remasc's balance in the MutableRepository. If the rREMASCFee is greater than 0 the payment is made. Some tests had to be changed since they replicate the behavior of the block executor and the REMASC payment is actually made in the block executor so the tests were modified as well

Modified the REMASC payment

---

rskj-core/src/main/java/co/rsk/rpc/netty/RskWebSocketServerProtocolHandler.java
rskj-core/src/main/java/co/rsk/rpc/netty/Web3WebSocketServer.java
rskj-core/src/test/java/co/rsk/rpc/netty/Web3WebSocketServerTest.java

This change allows `WebSocketServerProtocolHandler` to accept any url path. Basically ignores everything after `host:server`.
Alejandro Cavallero reported that there are users reporting that is tricky and a problem to require ‘/websocket’ in the endpoint. Is it possible to accept both ws://your-ip:4445 and ws://your-ip:4445/websocket
We added a unit test and also we did some manual testing using Postman websockets feature.

Accept websocket connection without '/websocket'

---

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/co/rsk/validators/ValidTxExecutionListsEdgesRule.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java

Replace THREAD_COUNT in BlockExecutor for Constants.getTransactionExecutionThreads() and changed everywhere.

Created a Constant with the number of threads

---

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java
rskj-core/src/main/java/org/ethereum/core/Transaction.java
rskj-core/src/test/java/co/rsk/core/TransactionIsRemascTest.java
rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java

- `txindex` started in 1. So `isLastTx` was false
- `data` was empty but not null in `SnapshotManagerTest` (idk why) so `checkRemascTxZeroValues` was also false
The remasc transaction was added to a parallel thread instead of the sequential one because it was wrongly identified as non-remasc tx
All tests pass now 😄 (see #1794)

Research/parallel-tx/Fix isRemascTransaction validation and pass correct index

---

rskj-core/src/main/java/org/ethereum/db/MutableRepository.java
rskj-core/src/test/java/co/rsk/db/RepositoryTrackingTest.java

Ref: https://github.com/rsksmart/rskj/pull/1811/files#r919225159
There are 4 cases on add balance:
- Account doesn't exist: avoids changing the current functionality. Account is created, wether it adds balance non-0 or 0
- Account exists
- Adds balance non-0: reads account state and then writes the new balance, as current functionality
- Adds balance 0: reads account, avoids writing since value doesn't change

Fix write the same value - avoid write on add balance 0

---

rskj-core/src/main/java/co/rsk/rpc/netty/Web3ResultHttpResponseHandler.java
rskj-core/src/test/java/co/rsk/rpc/netty/Web3HttpServerTest.java

Adding `Content-Length` and `Connection` headers to `JSON-RPC` responses.
`Content-Length` and `Connection` headers should be included in all JSON-RPC responses to increase compatibility with some clients.
- Unit Tests
- Integration Tests
- Local Tests
- QA
*fed:HOP-4.1.0-rc*
*fit:HOP-4.1.0-rc*
*ci:rskj-410-rc-ver*

Adding new Response Headers

---

rskj-core/src/main/java/co/rsk/cli/tools/DbMigrate.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSource.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java

Created a tool that allows the user to migrate between databases: `rocksdb and leveldb`
Tool class is: `co.rsk.cli.tools.DbMigrate`
Required cli args:
* args[0] - database target where we are going to insert the information from the current selected database.
Be aware that you cannot migrate to the same database, an error will be thrown.
It is highly recommended to turn off the node in order to perform the migration since latest data could be lost.
Example:
```
java -cp rsk-core-<VERSION>.jar co.rsk.cli.tools.DbMigrate rocksdb
```
When we want to use rocks db we need to reset the database and do a full sync. We wanted a way of just migrating what we have downloaded
* Unit tests
* Migrating data between databases using boton.

Add tool to migrate betweeen databases

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/rpc/dto/BlockResultDTOTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

Added flag to conditionally return `0x0` for signature fields of Remasc Transaction
- Unit tests
- Running Hardhat _Mainnet Forking_ test pointing to a Boton instance with this fix + content-header fix
- Postman RPC calls to affected methods with both flag `true` and `false`

Added option to set signature fields to 0x0 for Remasc on RPC response

---

rskj-core/src/main/java/co/rsk/core/bc/ReadWrittenKeysTracker.java
rskj-core/src/test/java/co/rsk/core/bc/ReadWrittenKeysTrackerTest.java

2X performance improvement, and better tests

---

rskj-core/src/main/java/co/rsk/cli/tools/DbMigrate.java
rskj-core/src/main/java/co/rsk/core/Wallet.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceKeyIterator.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
rskj-core/src/main/java/org/ethereum/datasource/DefaultKeyIterator.java
rskj-core/src/main/java/org/ethereum/datasource/HashMapDB.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSource.java
rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java
rskj-core/src/main/java/org/ethereum/datasource/LevelDbKeyIterator.java
rskj-core/src/main/java/org/ethereum/datasource/RocksDbDataSource.java
rskj-core/src/main/java/org/ethereum/datasource/RocksDbKeyIterator.java
rskj-core/src/test/java/org/ethereum/datasource/DataSourceWithCacheTest.java
rskj-core/src/test/java/org/ethereum/datasource/KeyValueDataSourceTest.java
rskj-core/src/test/java/org/ethereum/datasource/LevelDbDataSourceTest.java
rskj-core/src/test/java/org/ethereum/datasource/RocksDbDataSourceTest.java

Improving db migration process by using iterator instead of getting all the keys
In large databases it is not a good idea to get all existing keys. Instead we are using an iterator to iterate key by key.

Using iterator instead of loading all keys to avoid java heap errors

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/main/java/co/rsk/peg/FederationSupport.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/NetworkUpgrade.java
rskj-core/src/main/resources/config/devnet.conf
rskj-core/src/main/resources/config/main.conf
rskj-core/src/main/resources/config/regtest.conf
rskj-core/src/main/resources/config/testnet.conf
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportProcessFundsMigrationTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/FederationSupportTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

- Rename Hop500 network upgrade to Hop401
- Remove special case federation activation age
- Use RSKIP357 for new federation migration age
- Consider transactions with a p2sh erp redeem script before RSKIP353 when checking the transaction type

New erp script updates

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java
rskj-core/src/main/java/co/rsk/mine/BlockToMineBuilder.java
rskj-core/src/main/java/co/rsk/rpc/ExecutionBlockRetriever.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceModuleImpl.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/ExecutionFoundBlockRetrieverTest.java
rskj-core/src/test/java/co/rsk/rpc/Web3InformationRetrieverTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceModuleImplTest.java
rskj-core/src/test/java/co/rsk/test/World.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/util/EthModuleTestUtils.java
rskj-core/src/test/java/org/ethereum/vm/program/NestedContractsTest.java

This fixes the issue when requesting a "pending" block data via JSON-RPC api (only reproducible when mining is enabled). The issue was introduced in this [PR](https://github.com/rsksmart/rskj/pull/1885).
In #1885 implicit saving of a trie during block template creation was removed. But it turns out that some json-rpc methods were dependant on this, meaning that they expected the sate of a pending block to be sitting in the store.
This pull request adds one more method - `buildPending()` - which is specifically dedicated to the purpose of building a pending block with its final state (a trie) and cache them in memory for reuse if needed.
*ci:rskj-420-rc-ver*

Fixed issue with eth_call triggered for pending block

---

rskj-core/src/main/java/org/ethereum/db/MutableRepository.java
rskj-core/src/test/java/co/rsk/db/RepositoryTrackingTest.java

The checking: `value == Coin.Zero` returns false even when the value is Coin.Zero. It was fixed with value.equals(Coin.Zero)
and tested. Also, It was removed some ignored tests.

Fixing addBalance with zero

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestUtil.java
rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeStorageProviderUtil.java

Get rid of the BridgeSupportTest hierarchy, move those methods to util classes, and make test classes independent.

Get rid of BridgeSupportTest hierarchy 

---

rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java
rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java

Two new cases were fixed:
1. Writing sequential thread wasn't tracked, so reading after writing sequential would return bad candidates
2. Writing to sequential after writing to parallel wasn't updated, hence not giving more precedence on future reads or writes to the sequential

Fix writes after writing to parallel

---

rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/facade/Ethereum.java
rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java
rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleEthereum.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Updated `Ethereum#summitTransaction` method to return the result of adding the transaction to the pool so the caller can check if it was successful or not.
Updated the JRPC method `personal_sendTransaction` to behave the same as `eth_sendTransaction` when the transaction can not be added to the pool.
*fed:update_eth_add_transaction_response*

Updating ethereum_summitTransaction method and personal_sendTransaction

---

rskj-core/src/main/java/org/ethereum/datasource/RocksDbDataSource.java

Not dispose Options instance in RocksDbDataSource until db is closed
As of now, we are disposing and creating a new instance of the Options class every time we init RocksDB. According to the RocksDB’s javadoc we should not do that until db instance is closed.
Haven’t created unit tests for this specific change because I would like the team to review the changes made and see if there’s any other optimal solution. But all the existing unit tests are going through perfectly, and everything appears to be working fine by running the node locally.
- **Other information**:

Not dispose Options instance in RocksDbDataSource until db is closed

---

rskj-core/src/main/java/co/rsk/util/FormatUtils.java

Forces `String.format` to use `Locale.ROOT` to keep a consistent output across environments.
Closes #1709 
Some tests were failing in a system with Spanish locale (that uses comma as decimal separator instead of a point)

Sets default locale when converting numbers to strings in FormatUtils

---

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/config/BridgeConstantsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportProcessFundsMigrationTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java

This change consists of changing method co.rsk.config.BridgeConstants#getFundsMigrationAgeSinceActivationEnd to return again the fundsMigrationAgeSinceActivationEnd(10585L) value when the RSKIP374 gets active.

Affecting consensus by changing back federation migration age to its previous value

---

rskj-core/src/main/java/co/rsk/net/messages/BlockHeadersResponseMessage.java
rskj-core/src/main/java/co/rsk/net/messages/MessageType.java
rskj-core/src/main/java/org/ethereum/core/BlockFactory.java
rskj-core/src/main/java/org/ethereum/core/BlockHeader.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderBuilder.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderExtension.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderExtensionV1.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderV0.java
rskj-core/src/main/java/org/ethereum/core/BlockHeaderV1.java
rskj-core/src/test/java/co/rsk/core/BlockFactoryTest.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderExtensionTest.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderExtensionV1Test.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderTest.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderV0Test.java
rskj-core/src/test/java/co/rsk/core/BlockHeaderV1Test.java
rskj-core/src/test/java/org/ethereum/core/BlockHeaderBuilderTest.java

- Make extension data (ex logs bloom field) shortest as possible (32 bytes for version 1)
- Add version to RLP encoding (1 extra byte now). Now decode header will read version from RLP
- Express compressed on encode/decode (see `decodeHeader(RLPList rlpHeader, boolean compressed, boolean sealed)`)
- Rename methods and variables (use _extension data_ and _encoded compressed_ terms)
- Make header v0 read from extensionData (now logs bloom is stored in what is called the _extension data_ that both headers v0 and v1 have)

RSKIP 351 updates

---

doc/rpc/components/schemas/Receipt.json
doc/rpc/components/schemas/Transaction.json
doc/rpc/components/schemas/TransactionExampleResult.json
doc/rpc/methods/eth_getTransactionReceipt.json
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionReceiptDTOTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java

To be backwards compatible with Ethereum we need to extend our transaction receipt DTO and transaction result DTO in the RPC response with new the new field “type”, and return “0x0” as its value. - following EIP-2718

Return "0x0" type in transaction receipt and result

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionSet.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportProcessFundsMigrationTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/PowpegMigrationTest.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionSetTest.java

Renamed methods:
- processReleaseRequests -> processPegoutRequests
- processReleaseTransactions -> processConfirmedPegouts
- addPegoutTxToReleaseTransactionSet -> addPegoutBtcTxToPegoutWaitingForConfirmationsSet
- checkIfEntryExistsInTxsWaitingForSignatures -> checkIfEntryExistsInPegoutsWaitingForSignatures
Also, renamed logs 'release' to 'pegout' on methods renamed and refactored co.rsk.peg.ReleaseTransactionSet.Entry class

Renamed methods, logs and tests and refactored co.rsk.peg.ReleaseTransactionSet.Entry class

---

rskj-core/src/main/java/co/rsk/config/ConfigLoader.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java

Currently, rpc.modules is an array. Changing only one value (in DevOps case, enabling debug module in order to get access to queue size thru RPC) implies redefining rpc.modules in its totality.
Given that each entry of rpc.modules does include an unique name property, a better approach could be to change modules into an object.

Change rpc.modules config from array to object

---

rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java
rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorTest.java

In the processNewBlockHashesMessage method we could probably avoid requesting too advanced blocks (for example, if node is on early stages of a full-sync).
The main idea of this change is to avoid requesting these "far" blocks which will be later discarded. And by doing that, we can optimize the "processNewBlockHashesMessage" method.
This way we could save some unnecessary load in both nodes.

Avoid requesting for advanced (far) blocks.

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java
rskj-core/src/main/java/co/rsk/cli/tools/DbMigrate.java
rskj-core/src/main/java/co/rsk/cli/tools/ImportState.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSource.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSourceUtils.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
rskj-core/src/test/java/org/ethereum/datasource/NotParameterizedKeyValueDataSourceTest.java

Removal of execution code from the KeyValueDataSource interface, and move it to KeyValueDataSourceUtils. 
The refactor revealed a potential source of confusion where the key KEYVALUE_DATASOURCE_PROP_NAME was used for two unrelated things (database type determination and node configuration). 
Now there are two different keys: 
* PROPERTY_KEYVALUE_DATASOURCE  (for configuration)
* KEYVALUE_DATASOURCE_PROP_NAME (for database type determination)
We take out of the KeyValueDataSource interface the functionality to create a database  (LevelDB or RocksDB).
- An interface should not contain execution code
- An abstract interface should not reference concrete implementations of that interface (LevelDB / RocksDB) because that defeats its abstraction purpose
- An identifier …

Refactor KeyValueDataSource interface

---

rskj-core/src/main/java/co/rsk/Flusher.java
rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java
rskj-core/src/main/java/co/rsk/rpc/Web3RskModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/rsk/RskModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/rsk/RskModuleImpl.java
rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/core/bc/BlockChainFlusherTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3Mocks.java

This PR enables a new RPC method ("rsk_flush") that flushes all state databases to disk.
We add a new RPC command which calls the BlockChainFlusher class.
We also fix the flush method of DataSourceWithCache that previously didn't flushed the database (which wasn't a problem before because the databases used so far perform automatic flushing)
There are several reasons it is useful to make sure the state of the node databases have been written to disk without interrupting the node:
* If one suspects that power will soon fail
* For fair comparisons between databases (RocksDB vs LevelDB) is it important to assure both have committed all changes to disk
* To safely backup the databases without interrupting the node
* To access the databases in realtime from another application without …

Flush databases by RPC

---

Dockerfile

Allow JAVA_OPTS env variable when running docker container.
In the rskj repo we have a GitHub workflow that builds and pushes a docker image to DockerHub. Here’s a docker [file](https://github.com/rsksmart/rskj/blob/9c14a23e49de1b4729c8ab226c9e68445a8437a3/Dockerfile#L31-L36) for that
As of now, only a specific set of sys args is specified in the entrypoint statement and there’s no way to override or add extra vm args, eg. -Xmx or -Xss.
The idea is to define an env. var. in the Dockerfile, which would allow us to do that.
Running the follwoing commands:
```
docker build -t rskj-node -f Dockerfile . 
docker run --name rskj-node -e DEFAULT_JVM_OPTS="-Xms3G -Xmx5G" rskj-node
```

Allow specifying VM options when running RSKj in docker container

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/jsonrpc/JsonRpcError.java
rskj-core/src/main/java/org/ethereum/rpc/Filter.java
rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java
rskj-core/src/main/java/org/ethereum/rpc/NewBlockFilter.java
rskj-core/src/main/java/org/ethereum/rpc/PendingTransactionFilter.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/rpc/FilterTest.java
rskj-core/src/test/java/org/ethereum/rpc/LogFilterTest.java

Create two configurable limits for the JSON RPC request eth_getLogs
We are adding two configurable limits related with the amount of blocks to query and another one to limit the max number of logs to be return. 
By default they are deactivated with the default value = 0

Configurable eth get logs limits

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

Added test emulating when one pegout batch and a pegout migration are created on the same updateCollection, and share the same pegoutCreationRskTxHash key

add-test-for-two-pegout-using-same-key

---

rskj-core/src/main/java/co/rsk/peg/P2shErpFederation.java
rskj-core/src/test/java/co/rsk/peg/BitcoinTestUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
rskj-core/src/test/java/co/rsk/peg/ErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/FederationTestUtils.java
rskj-core/src/test/java/co/rsk/peg/P2shErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java

There is currently a method in ErpFederationTest that builds an ERP federation and signs a transaction with it. This is useful for unit testing, but also useful to try creating new federations with different keys and spending from it. Also useful to test spending using the emergency keys since it simplifies the signing process.
The way the method is set up now is not very flexible, it has a few keys hardcoded and they need to be put manually in order for it work.
Move the method to a utils class, make it so that a federation can be created simply by passing the seed for the different keys and the public and private keys can be derived from them.

Move the tests that spend from an ERP federation to it's own utils class

---

gradle/verification-metadata.xml
rskj-core/build.gradle
rskj-core/src/main/java/co/rsk/peg/P2shErpFederation.java
rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionBuilder.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java

Modify ReleaseTransactionBuilder to have witness in the transactions.
1. Override getP2SHScript() in P2shErpFederation to use createP2SHP2WSHOutputScript instead of createP2SHOutputScript.
2. Add segwitScriptSig into scriptSig's tx input and push witness data from originalScriptSig's tx input in ReleaseTransactionBuilder.
3. Modify ReleaseTransactionBuilderTest to check ReleaseTransactionBuilder works as expected.
This is one step from the _make fed address segwit-compatible_ task.
To run the project we should use built _bitcoinj-thin SNAPSHOT version_ (from _segwit-poc_ branch).

Add witness to ReleaseTransactionBuilder and ReleaseTransactionBuilderTest

---

rskj-core/src/main/java/co/rsk/peg/P2shErpFederation.java
rskj-core/src/test/java/co/rsk/peg/FederationTestUtils.java
rskj-core/src/test/java/co/rsk/peg/P2shErpFederationTest.java

Add a new test to check signing a tx from a p2shp2wsh fed.
createWitnessScript function (and all the needed constructor values) was added into TransactionWitness class in bitcoinj-thin project to use it here.

Add witness signatures

---

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java
rskj-core/src/jmh/java/co/rsk/jmh/web3/BlocksAndTx.java
rskj-core/src/jmh/resources/conf/testnet-3_860_000.conf

Improved jmh benchmarking configuration by reducing iterations (taking too long on debug and trace methods) and by reducing trace methods block range

Rpc benchmark optimisations

---

rskj-core/src/integrationTest/java/co/rsk/cli/tools/CliToolsIntegrationTest.java
rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java
rskj-core/src/main/java/co/rsk/cli/tools/DbMigrate.java
rskj-core/src/main/java/co/rsk/cli/tools/ImportState.java
rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSourceUtils.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/RskContextTest.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
rskj-core/src/test/java/org/ethereum/datasource/NotParameterizedKeyValueDataSourceTest.java
rskj-core/src/test/resources/rskj.conf
rskj-core/src/test/resources/test-rskj.conf

* Added rocksdb as default in the .conf files.
* Updated the default return type of `getDbKindValueFromDbKindFile`
Currently, RSKj default library storage is LevelDb. 
We want to make RocksDb the default db. 
Nodes running on LevelDb should keep using LevelDb, same with RocksDb. But nodes started from scratch will use RocksDb.
1. Running node from scratch and then stop it.
2. Run the node again.
3. Run node from scratch selecting non-default DB and then stop it.
4. Run the node again.
5. Run the node again with a different db selected and make sure it was running fine as well.

Make rocksdb the default DB instead of leveldb

---

rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/rpc/CallArguments.java
rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java

- Added `input` field to CallArguments
- Added new test for RPC methods that acccept a CallArguments object as argument.
Following the investigation done in [CORE-2939](https://rsklabs.atlassian.net/browse/CORE-2939), regarding an issue with some of the RPC methods we use in rskj, we found that both Web3js and Geth now have a parameter called `input`  which currently is not supported by our code, this parameter seems to behave similar to the `data` parameter given that Web3js automatically add `input` in the payload if it is missing add sets its value to a copy from `data`'s. 

Add input to CallArguments class

---

rskj-core/src/main/java/org/ethereum/rpc/FilterManager.java
rskj-core/src/main/java/org/ethereum/rpc/exception/RskJsonRpcRequestException.java
rskj-core/src/test/java/org/ethereum/rpc/FilterManagerTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

- Added the `filterNotFound` method to the `RskJsonRpcRequestException` class.
- Updated `getFilterEvents` and `removeFilter` method in `FilterManager` so they will throw the `filterNotFound` exception instead of returning null.
- Added unit tests fort the updated methods in `FilterManager` and integration tests for the affected eth methods.
The reponse for the eth filter method in rskj when a filter is not found is different from the response GETH returns. For example, when calling the endpoint `eth_getFilterChanges`:
Example call:
```
curl --location 'http://localhost:4444' \
--header 'Content-Type: application/json' \
--data '{
"jsonrpc":"2.0",
"method":"eth_getFilterChanges",
"params":[
"0x16"
],
"id":73
}'
```
The filter does not exist, GETH is returning;
```
{
"jsonrpc": "2.0", …
```

Add filterNotFound exception to RskJsonRpcRequestException class

---

doc/rpc/methods/eth_hashrate.json
rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/co/rsk/rpc/Web3EthModuleTest.java

This PR changes the response of the `eth_hashrate` method from a plain decimal number to a hexadecimal string. The change is in line with the behavior of the Geth.
This change is required to align the behavior of the RSKj client with the Ethereum clients, which return the hashrate as a hex-encoded string. This change fixes [issue #1837](https://github.com/rsksmart/rskj/issues/1837), where the `eth_hashrate` method in RSKj was returning a plain decimal number.
The changes have been tested by running the RSKj node with the changes applied. I checked the response format of the `eth_hashrate` method, and it now returns the hashrate as a hex-encoded string, which aligns with the behavior of geth.

Fix response format on eth_hashrate()

---

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransaction.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionDisabled.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionInstant.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWallet.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWalletDisabled.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleDSLTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleGasEstimationDSLTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplUnitTest.java
rskj-core/src/test/java/org/ethereum/util/TransactionFactoryHelper.java
rskj-core/src/test/java/org/ethereum/vm/program/NestedContractsTest.java

- Implemented deserializers added in [#2097](https://github.com/rsksmart/rskj/pull/2097).
- Updated affected tests.
We want to align GETH's and RSKJ's behavior when handling requests errors to avoid returning "Internal server error" from RSKJ.
Using the payloads from the notion document linked in the ticket CORE-3026 for the methods, for the payloads that should return an error, said error should not be "Internal server error". For example:
```
curl --location 'http://localhost:4444' \
--header 'Content-Type: application/json' \
--data '{
"jsonrpc":"2.0",
"method":"eth_getTransactionCount",
"params":[
"0xefd2de7da3e0cc04fa07654f34b8bcb8ebbf1015",
"first" 
],
"id":1
}'
```
Should return:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Invalid block identifier 'first'"}}`
* …

Implement json param validation

---

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletDisabled.java
rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java
rskj-core/src/main/java/org/ethereum/rpc/Web3.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/rpc/parameters/HexDurationParam.java
rskj-core/src/main/java/org/ethereum/rpc/parameters/HexStringParam.java
rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabledTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplUnitTest.java

Updating arguments types for methods listed on CORE-3130

Update methods argument classes

---

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/rpc/parameters/HexStringParam.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplUnitTest.java

Updating arguments types for methods listed on CORE-3238

Update methods arguments types

---

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java

Do not consider replaced transaction for pending transactions cost calculation.
On the transaction pool, when a pending transaction is replaced by another one (with a gasPrice bump), the original (replaced) transaction should not count for the total pending transactions costs calculation, as it is being replaced, and just the new one (replacement) should.

Ignore replaced transaction on total pending tx cost calculation

---

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Updated the `eth_protocolVersion` method so its return value is a hexadecimal String instead of an Integer.
As per the Rootstock [documentation](https://dev.rootstock.io/rsk/node/architecture/json-rpc/) the `eth_protocolVersion` method should return the current ethereum protocl version number as a hexadecimal, but it currently returns it as a decimal number.
```
curl --location 'http://localhost:4444' \
--header 'Content-Type: application/json' \
--data '{
"jsonrpc":"2.0",
"id":666,
"method":"eth_protocolVersion"
}'
// Should return
{"jsonrpc":"2.0","id":666,"result":"0x32"}
```

Convert rsk_protocalVersion return value to hex

---

rskj-core/src/main/java/co/rsk/cli/RskCli.java
rskj-core/src/test/java/co/rsk/cli/RskCliTest.java

Right now `--import` flag requires a value to be provided. This PR fixes this and returns how it was before.
*ci:fingerroot530-modifier*

Fixed parsing of --import cli flag

---

rskj-core/src/main/java/co/rsk/pcc/environment/GetCallStackDepth.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/test/java/co/rsk/pcc/environment/GetCallStackDepthTest.java
rskj-core/src/test/java/org/ethereum/vm/program/ProgramTest.java

Update the `Program#callToPrecompiledAddress` method to check if the contract beign called is `Environment` and if so, call its `init` method by passing a `PrecompiledContractArgs` instance with just its `programInvoke` variable set.

Add Environment contract check and init call to Program

---

rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java
rskj-core/src/test/java/org/ethereum/core/TransactionExecutorTest.java

Updated the repository passed to the precompiled contract `init` method fromt `track` to `cacheTrack`.
This change is suggested by the security team in their report to prevent potential future issues (for reference - PTX-CI-5).

Update the repository passed to the precompiled contract init method

---

rskj-core/src/main/java/co/rsk/peg/ErpRedeemScriptBuilderUtils.java
rskj-core/src/test/java/co/rsk/peg/ErpRedeemScriptBuilderUtilsTest.java

To build it correctly we should use `add-is-sent-to-standard-multisig-method` bj-thin's branch
https://github.com/rsksmart/bitcoinj-thin/tree/add-is-sent-to-standard-multisig-method

Add tests for erp builder utils

---

rskj-core/src/main/java/co/rsk/net/discovery/DiscoveryEvent.java
rskj-core/src/main/java/co/rsk/net/discovery/NodeChallenge.java
rskj-core/src/main/java/co/rsk/net/discovery/NodeChallengeManager.java
rskj-core/src/main/java/co/rsk/net/discovery/PeerDiscoveryRequest.java
rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java
rskj-core/src/main/java/co/rsk/net/discovery/table/BucketEntry.java
rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceTable.java
rskj-core/src/main/java/co/rsk/net/discovery/table/OperationResult.java

Added more logs to PeerExplorer class in order to increase visibility during the peer discovery process.

Add logs peer discovery

---

rskj-core/src/main/java/co/rsk/util/SystemUtils.java
rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
rskj-core/src/test/java/org/ethereum/datasource/KeyValueDataSourceTest.java
rskj-core/src/test/java/org/ethereum/datasource/LevelDbDataSourceTest.java
rskj-core/src/test/java/org/ethereum/datasource/NotParameterizedKeyValueDataSourceTest.java

As of now, LevelDB database engine doesn't support Apple or any other ARM-based silicons which causes unit tests check to fail when triggered on such cpu's

Ignore LevelDB-related unit tests when running on ARM CPUs

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java
rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java
rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
rskj-core/src/test/java/org/ethereum/facade/EthereumImplTest.java

We are updating the logic about how the gas price data returned by the eth_gasPrice rpc method is calculated.
The new behaviour is: 
1. We need to check [isFeeMarketWorking()](https://github.com/rsksmart/rskj/blob/5c5fe3db8b1ff07c87a7a79cf4a0f7db0f3c6b6d/rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java#L128C33-L128C51) in the GasPriceTracker class to figure out if recent blocks are full enough. If the method returns true then go to the item 2 below. Otherwise, eth_gasPrice should return lastBestBlock.getMinimumGasPrice() * minGasPriceMultiplier , where minGasPriceMultiplier is a configuration value and should be 1.1 by default ( 10% increment of min gas price).
2.If a market is working (isFeeMarketWorking() returns true) , then eth_gasPrice should return same results as …

Updating how eth_gasPrice is calculated

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderFederationTests.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/FlyoverCompatibleBtcWalletWithStorageTest.java
rskj-core/src/test/java/co/rsk/peg/FlyoverCompatibleBtcWallextWithSingleScriptTest.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java
rskj-core/src/test/java/co/rsk/peg/PowpegMigrationTest.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java
rskj-core/src/test/java/co/rsk/peg/federation/NonStandardErpFederationsTest.java

With the Federations refactor, what we used to call the legacy // legacy erp federation has been renamed to NonStandardErpFederation, due to its non-standardness.
Therefore, we ended up having instances with the old naming and instances with the new one.
This pr aims to rename legacy // legacy erp // erp to non standard erp to make the code more consistent and clear.
Also, the same was done in some 'standard multisig fed' cases.

Rename legacy to non standard

---

rskj-core/src/main/java/co/rsk/rpc/Web3RskModule.java
rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/rpc/parameters/HexAddressParam.java
rskj-core/src/main/java/org/ethereum/rpc/parameters/HexNumberParam.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplUnitTest.java

Adding new rsk_getStorageBytesAt JSON-RPC method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

Correct legacyProcessPegin name in logs.
Inside the `legacyProcessPegin` method, the logs where printing `processPegIn` as the method name, which is not correct. So, this pr is changing that to print the correct one.

Correct legacyProcessPegin name in logs

---

rskj-core/src/main/java/co/rsk/peg/federation/ErpFederation.java
rskj-core/src/main/java/co/rsk/peg/federation/ErpFederationArgs.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationArgs.java
rskj-core/src/test/java/co/rsk/peg/federation/NonStandardErpFederationsTest.java
rskj-core/src/test/java/co/rsk/peg/federation/P2shErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/federation/StandardMultisigFederationTest.java

This pr creates tests for the new FederationArgs and ErpFederationArgs added classes.
Also, it includes the creation of the getErpArgs() method to return erpFederationArgs from erp federations.
The method getArgs() that returns federationArgs from federations was already created

Create getErpArgs method for ErpFederation. Create tests for both FederationArgs and ErpFederationArgs classes

---

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplUnitTest.java

Updated eth_getStorageAt to return a 32-byte zero value for non-existing keys, aligning with geth client behavior.
Ensures compatibility with Ethers.js and other clients like Geth, which expect a 32-byte zero value for non-existing keys.
Tested in local development environment; unit tests updated to reflect new return value.

Return properly encoded value by eth_getStorageAt RPC method for non-existing keys

---

rskj-core/src/main/java/co/rsk/peg/Federation.java
rskj-core/src/test/java/co/rsk/peg/LegacyErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/P2shErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/StandardMultisigFederationTest.java

- Created a new method to get federation member by btc public key
- Added new tests for the new method:
- Passing a null should return an empty optional.
- Passing a random BTC public key should return an empty optional.
- Passing an existing BTC public key should return the matched federation member.

Added getMemberByBtcPublicKey new method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/Federation.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

-  logAddSignature method was refactored to receive a federation member instead of a btcPublicKey. Regarding, getting rid of btcTx, it was not removed because legacy implementation of BridgeEventLogger is using that parameter and logging it.
- New tests were added, and existing tests were updated to call the method using the new signature.

Fix logAddSignature method where pegnatory RSK address is wrongly being derived from the btc public key for key file and hsm pegnatories

---

rskj-core/src/main/java/co/rsk/net/discovery/UDPServer.java

*ci:rc600-modifier*
*fed:ARROWHEAD-6.0.0-rc*
*rit:ARROWHEAD-6.0.0-rc*

Used fixed buffer allocator for udp channel

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/remasc/Remasc.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderPegoutTxIndexTests.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java
rskj-core/src/test/java/co/rsk/peg/PowpegMigrationTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascRskAddressActivationTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

Background
- Fix the `ActivationConfig` instance being created using an incorrect block at the `processMinersFees` method. Because of this issue activations checks were wrong resulting in a fork when syncing previous code for a boton instance. The `ActivationConfig` object should always use the execution block number to check which rskip is active. So we refactored how the activations object is created, now it uses only the execution block number, and instead of using `ActivationConfig` object we changed it to be an `ActivationConfig.ForBlock`, so we only need to pass the block number once when we creating the object.
- Also, we abstract the RSKIP85 activation check into a separate method: `shouldRewardBeAboveMinimumPayableGas`. This way the method itself expresses what this rskip is for …

Fixed misused of activation config passing wrong execution block number.

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/Federation.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java
rskj-core/src/main/java/co/rsk/remasc/Remasc.java
rskj-core/src/main/java/co/rsk/remasc/RemascFederationProvider.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderPegoutTxIndexTests.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java
rskj-core/src/test/java/co/rsk/peg/LegacyErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/P2shErpFederationTest.java
rskj-core/src/test/java/co/rsk/peg/PowpegMigrationTest.java
rskj-core/src/test/java/co/rsk/peg/StandardMultisigFederationTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascFederationProviderTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascRskAddressActivationTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java
rskj-core/src/test/java/co/rsk/remasc/RemascTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

Summary of changes
- Create a new method to get federation member by btc public key and added tests for it.
- logAddSignature method was refactored to receive a federation member instead of a btcPublicKey. Regarding, getting rid of btcTx, it was not removed because legacy implementation of BridgeEventLogger is using that parameter and logging it.
- New tests were added, and existing tests were updated to call the method using the new signature.
- Refactored RemascFederationProvider constructor to receive only ActivationConfig.ForBlock activations and FederationSupport federationSupport, since this class only needs these 2 dependencies. It was receiving many other dependencies only to create the FederationSupport instance. Hence, I decided to simplify it by only receiving 2 dependencies …

RskAddress derives properly from rsk key

---

rskj-core/src/main/java/co/rsk/rpc/Web3InformationRetriever.java
rskj-core/src/test/java/co/rsk/rpc/Web3InformationRetrieverTest.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

With the current logic implementation, the hash is working to retrieve the block. We had to change the way to get blockReference that wasn't considering the identifier to be a hash.
With the change, we try to get the bockReference as if the identifier was a number, if it still doesn't work, we try as a hash. Since both ways are accepted as a string identifier.

Fix the web 3 retriever with block hash as identifier

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/org/ethereum/listener/GasPriceCalculator.java
rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
rskj-core/src/main/java/org/ethereum/listener/PercentileGasPriceCalculator.java
rskj-core/src/main/java/org/ethereum/listener/WeightedPercentileCalc.java
rskj-core/src/main/java/org/ethereum/listener/WeightedPercentileGasPriceCalculator.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/NodeRunnerSmokeTest.java
rskj-core/src/test/java/org/ethereum/listener/GasPriceTrackerTest.java
rskj-core/src/test/java/org/ethereum/listener/WeightedPercentileCalcTest.java
rskj-core/src/test/java/org/ethereum/listener/WeightedPercentileGasPriceCalculatorTest.java

A option to calculate the gas price using weighted percentile considering the gas used is being added to the client. At the same time the legacy calculation is being kept and used as default for now.
Plain percentile calculation was extracted from the gasPriceTracker and a new GasUsed weighted percentile calculator was added in order to update how the gasPrice is being calculated. 
The calculator to use (legacy/weighted) can be configured. 
We want to improve the current algorithm which is being used by eth_gasPrice method. Right now we only consider actual gas price of recently mined txs when we are looking for a price percentile. The suggestion is to besides gas price also consider tx.gasUsed.

Weighted percentile for gasPrice calculation

---

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java
rskj-core/src/main/java/co/rsk/net/SyncProcessor.java
rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java
rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java

In order to be able to merge the branch, we have to fix the CodeQL issues with high severity. This branch does it.

Solving codeql issues

---

rskj-core/src/test/java/org/ethereum/vm/program/invoke/ProgramInvokeMockImpl.java

The overloaded methods `getOriginAddress` and `getCallerAddress` in `ProgramInvokeMockImpl` perform hashing and secp256k1 base point multiplication each time `ORIGIN` or `CALLER` are executed.
https://github.com/rsksmart/rskj/blob/12c9b322cfb968c1ed7adb93bad32e7ed14c62b6/rskj-core/src/test/java/org/ethereum/vm/program/invoke/ProgramInvokeMockImpl.java#L111-L129
This makes these opcodes unnecessary slow and it impedes my effort to detect genuine performance issues with the EVM itself.
With this test harness (rskj-core/src/test/java/co/rsk/vm/Poc.java):
```java
package co.rsk.vm;
import org.ethereum.config.blockchain.upgrades.ActivationConfig;
import co.rsk.config.TestSystemProperties;
import co.rsk.config.VmConfig;
import org.ethereum.vm.*;
import org.ethereum.core.BlockFactory;
import …
```

Improve performance of mock getOriginAddress, getCallerAddress

---

rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java
rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java

As RSK user I want IP addresses (instead of DNS names) to be sent to other peers in response to FIND_NODE peer discovery message
Instead of DNS hostnames a node always sends IP addresses in response to the FIND_NODE peer discovery message
As of now, in the peer discovery protocol, when a peer asks for neighbours by sending FIND_NODE message in response it gets a sub list of other discovered peers in a network. Sometimes, instead of IP addresses of remote peers that list might include DNS names resolved via reverse DNS lookup in a context of the peer that returns that response. In some cases this might lead to issues when the reverse DNS resolution happens in different network contexts, for instance, when inside AWS VPC an IP can be resolved to ip-10-10-133-54.us-west-2.compute.internal, …

fix(discovery): makes pong send only IP without hostname

---

rskj-core/src/main/java/co/rsk/peg/abi/ABICallSpec.java

There is an ongoing effort to organize Bridge classes in their package and avoid circular dependencies.
One of the classes we have identified that could be moved to their package are those related to ABI voting.
To capitalize this effort, there are some improvements that can be done in each class.
This PR modifies the ABICallSpec:
- Refactor methods to make them mode readable.
- Make fields final.

Modify ABICallSpec

---

rskj-core/src/main/java/co/rsk/peg/AddressBasedAuthorizer.java

There is an ongoing effort to organize Bridge classes in their package and avoid circular dependencies.
One of the classes we have identified that could be moved to their package are those related to ABI voting.
To capitalize this effort, there are some improvements that can be done in each class.
This PR modifies the ABICallVoteResult:
- Refactor using lambda expression.

Modify AdressBasedAuthorizer

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/UnauthorizedVoterException.java
rskj-core/src/main/java/co/rsk/peg/vote/ABICallElection.java
rskj-core/src/main/java/co/rsk/peg/vote/UnauthorizedVoterException.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/vote/ABICallElectionTest.java

There is an ongoing effort to organize Bridge classes in their package and avoid circular dependencies.
One of the classes we have identified that could be moved to their package are those related to ABI voting.
To capitalize this effort, there are some improvements that can be done in each class.
This PR modifies the ABICallElection:
- Make getWinner return Optional instead of null. 
- Add logs.
- Make validate method throw a new UnauthorizedVoterException.

Modify ABICallElection

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationMember.java

The FederationMember class contains a KeyType enum. This enum has a Value field that must be declared with the final keyword.
This is part of a tech debt and improves good practices on the project. The Final keyword will make this attribute immutable, which is a good practice for handling concurrent transactions and avoiding state modification after creation.

Make Value Field In the KeyType Enum Final

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

releaseBtc method is printing a message showing the wrong unit. We changed the log message to print Weis as the unit instead of Satoshis getting the value in Weis from the Rsk transaction before converting it to satoshis with rskTx.getValue().
This improves the traceability of the project.

Fix log message in BridgeSupport releaseBtc Method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsGetTransactionTypeTest.java

There are 2 bridge constants related to the minimum pegout value. legacyMinimumPegoutTxValueInSatoshis and minimumPegoutTxValueInSatoshis. These names are not precise, because the data type is actually a Coin object, so it’s not an amount and should not have a unit. For this reason, we renamed both constants to legacyMinimumPegoutTxValue and minimumPegoutTxValue respectively.
To improve naming conventions.

Rename Minimum Pegout Constants From BridgeConstants

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java

Update Bridge constants to use a ZonedDateTime object to indicate the `genesisFederationCreationTime` value instead of an Instant object.

Use original values for genesisFederationCreationTime

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/main/java/co/rsk/peg/FederationSupport.java
rskj-core/src/main/java/co/rsk/peg/PegUtils.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/PendingFederation.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/feeperkb/constants/FeePerKbMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java
rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/main/java/org/ethereum/config/SystemProperties.java

Extract federation constants from BridgeConstants to their own classes.
Create /federation package to have all federation-related classes.
Move new classes to /federation/constants package.
Fix now broken use of BridgeConstants

Extract federation constants from BridgeConstants

---

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java

We are creating a new event named pegout_transaction_created, where the peg-out transaction hash and the list of outpoint values will be stored. This will enable the PowPeg to retrieve these values from the rsk transaction receipt where the peg-out was created, allowing it to provide them to the PowHsm.

Create pegout_transaction_created event

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java

Create FederationSupport interface in /federation package with all federation-related methods
_Disclaimer:_ added `getPendingFederation` method to replace that the pending federation is being get directly from the provider.

Create FederationSupport interface

---

rskj-core/src/main/java/org/ethereum/rpc/parameters/CallArgumentsParam.java
rskj-core/src/test/java/org/ethereum/rpc/parameters/CallArgumentsParamTest.java
rskj-core/src/test/java/org/ethereum/util/TransactionFactoryHelper.java

Fixed eth_call 'input' param handling

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationChangeFunction.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationChangeFunctions.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProviderImpl.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/main/java/co/rsk/peg/federation/PendingFederation.java

Refactor some methods to improve readibility.
_Disclaimer:_ the only file that should be reviewed in this pr is `FederationStorageProviderImpl`.
The other ones belong to other prs that were done starting from this branch.

FederationStorageProviderImpl refactor

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/federation/PowpegMigrationTest.java

- Fix `PowpegMigrationTest`
- Move `PowpegMigrationTest` to `/federation` package.
- Make `commitFederation` method in `FederationSupportImpl` protected instead of private to test

Fix PowpegMigrationTest

---

rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java
rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationConstantsTest.java

- Fix `BridgeConstantsTest` by moving federation constants related tests from it.
- Create `FederationConstantsTest` class inside new `/federation/constants` package to have those tests.

Fix BridgeConstantsTest

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProviderImpl.java

- Add the initialization to `FederationStorageProviderImpl`, since the field is now part of it.
_Context:_ `storageVersionEntries` was being initialized when belong to `BridgeStorageProvider`. See [here](https://github.com/rsksmart/rskj/blob/master/rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java#L126).
This got lost during the refactor.
- Refactor the method `getStorageVersion` method following a Sonar suggestion

Initialize storageVersionEntries as new hashmap

---

rskj-core/src/main/java/org/ethereum/vm/VM.java
rskj-core/src/main/java/org/ethereum/vm/program/Program.java

Removed the call to `Arrays.copyOf()` method and made `getCode()` return the array directly. As per @asoto-iov suggestion the `getCodeLength()` method.
Currently the `doCODESIZE()` and `doCODECOPY()` methods can, under certain conditions, make a call to the `getCode()` method that returns a deep copy of the underlying array which can cause perfomance issues if the code array is too big.

Update getCode so it does not make a copy of the array

---

rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java

With the refactors, getting the federationConstants from bridgeConstants [is now needed](https://github.com/rsksmart/rskj/blob/federation-support-refactor-integration/rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java#L124) when logging commit federation.
This pr mocks the response.

Mock needed getFederationConstants response

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java

In the federation support refactor, the bridge support's method `getPendingFederationHash` [was modified](https://github.com/rsksmart/rskj/blob/federation-support-refactor-integration/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L1996) to return a `Keccak256 hash` [instead of](https://github.com/rsksmart/rskj/blob/master/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L2348) `bytes`, and therefore, the same bridge's method [was modified](https://github.com/rsksmart/rskj/blob/federation-support-refactor-integration/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L978) to get the bytes from the hash [instead of](https://github.com/rsksmart/rskj/blob/master/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L977) getting the bytes directly.
This pr refactors the bridge method to …

Fix getPendingFederationHash bridge's method to avoid npe 

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistResponseCode.java

New enum WhitelistResponseCode that contains the response codes for Whitelist. Currently, they are part of BridgeSupport, and we are going to remove them and put them all in the new object.
Remove the LOCK_WHITELIST prefix, and _CODE suffix since don't add any value.
This is related to the Bridge Refactor to decouple some objects that are tied closely to the Bridge.

Whitelist Response Code Enum

---

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

- Rename `FederationSupportTest` to `FederationSupportImplTest`
- Move the class to the `/federation` package

Rename and move FederationSupportTest

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageIndexKey.java
rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistStorageIndexKey.java
rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistStorageProviderImpl.java

Due to multiple storage keys being included in BridgeStorageIndexKey Enum, we need to refactor Whitelist logic to its package and classes, we should also create its own Enum with storage index keys.
Create a new enum called WhitelistStorageIndexKey under co.rsk.peg.whitelist package. Move from BridgeStorageIndexKey to WhitelistStorageIndexKey whitelist constants, and make the respective refactor related.

Whitelist Storage Index Key

---

rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorIntrinsicGasLimitValidatorTest.java
rskj-core/src/test/java/org/ethereum/config/ConstantsTest.java

Some tests outside /peg package were failing after the refactor.
This pr fixes them:
- `TransactionTest`, by adding a bridgeConstants mock response to avoid a npe.
- `TxValidatorIntrinsicGasLimitValidatorTest`, by using the regtest federation private keys being now used in regtest.
- `ConstantsTest`, by using the correct genesis federation public keys from `FederationTestNetConstants`.

Fix remaining broken tests

---

Dockerfile

Add new Environment Variable in Dockerfile to print logs to STDOUT by default.
Some Rootstock users complain that it’s a hassle to make Docker / Docker Compose to print logs via docker logs -f, so we should enable logging to stdout by default in Docker containers.

Update Dockerfile to print logs to STDOUT by default

---

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

- Remove unrealistic test cases with non null `oldFederation` and null `newFederation`
- Rename the tag where these tests were removed to be more accurate
Also,
- Replace `BeforeAll` with `BeforeEach` for inner test classes to better align with unit tests practices.
This change required that the variables declared in the `setUp()` of the `ActiveFederationTestsWithNonNullFederations` class be made global, so they can be used by the method sources.

Remove unrealistic test cases. Rename tag to be more accurate

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

- Add `getRetiringFederatorBtcPublicKey` tests
- Rename `getRetiringFederatorPublicKey` to `getRetiringFederatorBtcPublicKey` in `FederationSupport` and in `BridgeSupport` to be more accurate with what the method does

Add getRetiringFederatorBtcPublicKey tests

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

- Add getPendingFederatorBtcPublicKey tests
- Rename `getPendingFederatorPublicKey` to `getPendingFederatorBtcPublicKey` in `BridgeSupport` and `FederationSupport` to be more accurate

Add getPendingFederatorBtcPublicKey tests

---

rskj-core/src/main/java/org/ethereum/vm/program/Program.java
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceModuleImplTest.java
rskj-core/src/test/resources/dsl/delegatecall02.txt

Pass `codeAddress` instead of `null`  if the contract code is empty when creating a new call sub trace.
This is a reported [bug](https://github.com/rsksmart/rskj/issues/2346). Traces generated from any `trace_` api method do not include the `to` property in an `action` when in cases when `action` in question is a `delegatecall` to a non existent contract.

Add to field in trace responses

---

rskj-core/src/test/java/co/rsk/peg/whitelist/WhitelistSupportImplTest.java

As part of Bridge refactors, this is time to work on the Whitelist process, so we need to extract this from the Bridge and create its objects to decouple the process.
Create UTs for verifyLockSenderIsWhitelisted to increase coverage on WhitelistSupportImplTest.
Increase coverage.
Unit Tests

Add UTs for verifyLockSenderIsWhitelisted in WhitelistSupportImplTest

---

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

-Add `save()` test
_Disclaimer_
since the `save()` method from the `federationSupport` is just calling the one from its provider, this test ensures that this happens correctly. That's why the provider had to be mocked.
Checking the internal logic of the federationStorageProvider's `save()` is out of scope of this test, it should be part of `FederationStorageProviderTests`

Add save test

---

rskj-core/src/integrationTest/java/co/rsk/snapshotsync/SnapshotSyncIntegrationTest.java
rskj-core/src/integrationTest/java/co/rsk/util/OkHttpClientTestFixture.java
rskj-core/src/integrationTest/java/co/rsk/util/cli/ConnectBlocksCommandLine.java
rskj-core/src/integrationTest/resources/snap-sync-client-rskj.conf
rskj-core/src/integrationTest/resources/snap-sync-server-rskj.conf
rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java
rskj-core/src/main/java/co/rsk/net/SyncProcessor.java
rskj-core/src/main/java/co/rsk/net/messages/MessageVisitor.java
rskj-core/src/main/java/co/rsk/net/sync/BaseSyncState.java
rskj-core/src/main/java/co/rsk/net/sync/ChunkTask.java
rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java
rskj-core/src/main/java/co/rsk/net/sync/SnapSyncState.java
rskj-core/src/main/java/co/rsk/net/sync/SyncConfiguration.java
rskj-core/src/main/java/co/rsk/net/sync/SyncEventsHandler.java
rskj-core/src/main/java/co/rsk/net/sync/SyncMessageHandler.java
rskj-core/src/main/java/co/rsk/net/sync/SyncState.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java
rskj-core/src/test/java/co/rsk/net/ThreeAsyncNodeUsingSyncProcessorTest.java
rskj-core/src/test/java/co/rsk/net/sync/SimpleSyncEventsHandler.java
rskj-core/src/test/java/co/rsk/net/sync/SnapSyncStateTest.java
rskj-core/src/test/java/co/rsk/net/sync/SyncMessageHandlerTest.java

changes:
- client SNAP sync state migrated from `SnapshotProcessor` to `SnapSyncState`
- processing of SNAP requests and responses is being queued in appropriate blocking queue and then executed in a dedicated thread 
- now there are two separate snap configs for client and server
- updated a bit snap integration test

chore(snap): refactor code to use blocking queues with threads for SNAP messages processing

---

.github/workflows/build_and_test.yml
build.gradle

The Sonarqube seems to consume some test reports generated by JaCoCo gradle plugin
This PR persists these and ensures that the sonar gradle script has access to all branches

fix(ci): persist test reports for sonar

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java

-Add tests that add coverage to those `BridgeSupport` methods that simply pass the call to `FederationSupport` ones.
-Refactor / rename some methods in `BridgeSupport`.
-Remove tests from `BridgeSupportTest` that are now part of `FederationSupportImplTest` class.

Add tests for BridgeSupport methods that call FederationSupport

---

rskj-core/build.gradle
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/NetworkUpgrade.java
rskj-core/src/main/resources/config/main.conf
rskj-core/src/main/resources/config/regtest.conf
rskj-core/src/main/resources/config/testnet.conf
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

Related to https://blog.rootstock.io/noticia/incident-report-rootstock-peg-in-peg-out-service-outage-on-june-24th/
Only register in the Bridge Bitcoin blocks past 849,137 height if RSKIP434 is active.
Relates to
- https://github.com/rsksmart/bitcoinj/pull/17
- https://github.com/rsksmart/bitcoinj-thin/pull/78
*ci:rc631-modifier*
*fed:ARROWHEAD-6.3.1-rc*
*rit:ARROWHEAD-6.3.1-rc*

Chainwork fix

---

.github/workflows/build_and_test.yml

Moves untrusted input of github variables to the step env var definition to prevent RCE. https://securitylab.github.com/research/github-actions-untrusted-input/

fix(ci): moves vars to step env

---

rskj-core/src/test/java/co/rsk/peg/federation/P2shErpFederationBuilder.java
rskj-core/src/test/java/co/rsk/peg/federation/StandardMultiSigFederationBuilder.java

-Change creation time and creation block number in federation builders to avoid des/serialization of 0
-Change erp fed members in p2sh federation builder so it matches the real ones

Fix federation builders to avoid des/serialization of 0

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageIndexKey.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapStorageIndexKey.java

Create the package lockingcap with an enum to hold the storage index key for locking cap value, create a new enum LockingCapStorageIndexKey to contain the index key for the locking cap value in storage, remove it from BridgeStorageIndexKey, remove the. _KEY suffix, and rename to LOCKING_CAP.

Create LockingCapStorageIndexKey Enum

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeDevNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/constants/LockingCapConstants.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/constants/LockingCapMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/constants/LockingCapRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/constants/LockingCapTestNetConstants.java

Following with the Bridge refactors, it is now time to refactor and remove the locking cap business logic from the Bridge.
Create its package `lockingcap` with a Support, StorageProvider, and Constants classes. Since it will have its classes, should be removed from the variable names, `lockingCap`, to avoid being redundant.

LockingCapConstants Refactor

---

rskj-core/src/main/java/co/rsk/peg/lockingcap/constants/LockingCapConstants.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/constants/LockingCapTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/lockingcap/constants/LockingCapConstantsTest.java

Following the Bridge refactors, we already migrated the LockingCapConstants to their classes to break the high coupling LockingCap had with the Bridge objects, however, it’s missing add coverage, so we need to create Unit Tests to get reliability that your new code doesn't break existing functionality when a change is made to the application.
- Create Unit Tests for all methods in LockingCapConstants 
- Create Test Cases for all Networks such as MainNet, TestNet, and RegTest.
Unit Tests.

LockingCapConstants Test

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java

Following with the Bridge refactors, it is now time to refactor and remove locking cap logic from BridgeSupport class. Create LockingCapConstants in BridgeConstants.

Create LockingCapConstants in BridgeConstants

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/test/builders/BridgeSupportBuilder.java

Following with the Bridge refactors, it is now time to refactor and remove locking cap logic from Bridge objects to LockingCap objects. This time we need to add Locking Cap logic to BridgeSupportBuilder class. Add WhitelistSupport to BridgeSupportBuilder business logic.

Add LockingCapSupport To BridgeSupportBuilder

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupportFactory.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupportImpl.java

Update BridgeSupportFactory to create an instance of LockingCapSupport and pass it to BridgeSupport constructor.

Add LockingCapSupport Creation To BridgeSupportFactory

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java

After the `LockingCapSupport` interface has been created, we will use it on the `BridgeSupport`. Adapt `LockingCap` methods in the `BridgeSupport`. Use the new interface created, `LockingCapSupport`, under `co.rsk.peg.lockingcap` package to create `LockingCap` behavior.

Adapt BridgeSupport Methods for LockingCap Refactor

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProviderImpl.java

- Create `setProposedFederation` public method in `FederationStorageProviderImpl` to set the proposed federation
- Create `saveProposedFederation` private method in `FederationStorageProviderImpl` to save the serialized proposed federation in the repository

Add methods to save proposedFederation entries

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java

Fix BridgeSupportAddSignatureTest class.
Unit Tests.

Fix BridgeSupportAddSignatureTest after LockingCap refactor

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportIT.java

Fix BridgeSupportIT class.
Unit Tests.

Fix BridgeSupportIT after LockingCap refactor

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java

Fix BridgeSupportRegisterBtcTransactionTest class.
Unit Tests.

Fix BridgeSupportRegisterBtcTransactionTest after LockingCap refactor

---

rskj-core/src/test/java/co/rsk/peg/federation/PowpegMigrationTest.java

- Fix the PowpegMigrationTest class.
- Get rid of setting the LockingCap since it is not mandatory in the test. From now on, the test will use the LockingCap default value, i.e., the LockingCapConstants.initialValue().
Unit Tests.

Fix PowpegMigrationTest after LockingCap refactor

---

doc/rpc/components/schemas/Receipt.json
doc/rpc/methods/eth_getTransactionReceipt.json
rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionReceiptDTOTest.java

In order to let the transactionReceipt compatible with the Ethereum one, we are adding the field effectiveGasPrice, that it's the same value of the gasPrice on the transaction.

Adding the effectiveGasPrice to the eth_getTransactionReceipt

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java

- Fix registerBtcTransaction_after_RSKIP134_activation_sends_above_lockingcap test
- Fix BridgeSupportFlyoverTest after LockingCap refactor
Since the locking cap refactor `BridgeSupportFlyoverTest` has been failing, those tests needed to be fixed once the refactor was done.
Unit testes

Fix bridge support flyover tests after locking cap refactor

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProviderImpl.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java

- Create `getProposedFederation` method to get the proposed federation saved in the repository.
- Create tests for different scenarios

Add getProposedFederation method

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapIllegalArgumentException.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupport.java
rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/lockingcap/LockingCapSupportImplTest.java

Following the `Bridge` refactors, we migrated the `LockingCap` processes to their classes to break the high coupling LockingCap had with the Bridge objects. Please move the business logic related to the zero-negative LockingCap value from `Bridge.java` to `LockingCapSupportImpl.java`. This way, decouple the process and get all `LockingCap` business logic, in the `LockingCapSupport` object.
- Move business logic related to the zero-negative LockingCap value from Bridge.java to LockingCapSupportImpl.java.
- Put this validation at the beginning of the `increaseLockingCap` Method.
- Fix issues related to `BridgeIllegalArgumentException` in the `LockingCapSupportImpl#increaseLockingCap` Method because of adding the new validation.
- Fix issues related to `BridgeIllegalArgumentException` in the …

Zero - Negative LockingCap Value Business Logic

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java

Bug fix For LockingCapConstants in all the networks placed in BridgeConstants.

BugFix For LockingCapConstants in all the Networks

---

rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java

Add coverage for `getFeePerKbConstants`, `getWhitelistConstants`, and `getFederationConstants` methods, placed in `BridgeConstants`.
Unit Tests.

Add Coverage in BridgeConstants

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java

Fix reference to whitelist constants in BridgeTestNetConstants

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java
rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java

-Create `spendableValueFromProposedFederation` in BridgeConstants as `minimumPegoutTxValue * 2`

Add spendable value in bridge constants

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

-Create a new settleReleaseRequest that perform all the needed actions whenever creating a pegout.
-Get rid of existing addToPegoutsWaitingForConfirmations method.

Create new settleReleaseRequest method to perform common actions when creating pegouts

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

Although the Bridge::addFederatorPublicKey method is disabled from the BridgeMethods class post RSKIP123.
Check this line:
https://github.com/rsksmart/rskj/blob/859b52a0f174eedd852312ed9c93081888ddcfe1/rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java#L45
It still can be called directly from the FederationSupportImpl class.
We need to add a check in FederationSupportImpl to throw an exception if the “add” function is called.
This pr addresses that.

Adds RSKIP123 check to addFederatorPublicKey

---

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
rskj-core/src/main/java/co/rsk/net/Peer.java
rskj-core/src/main/java/co/rsk/net/sync/PeersInformation.java
rskj-core/src/main/java/org/ethereum/net/client/Capability.java
rskj-core/src/main/java/org/ethereum/net/client/ConfigCapabilitiesImpl.java
rskj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java
rskj-core/src/main/java/org/ethereum/net/server/Channel.java
rskj-core/src/main/java/org/ethereum/net/server/EthereumChannelInitializer.java
rskj-core/src/test/java/co/rsk/net/simples/SimpleNodeChannel.java
rskj-core/src/test/java/co/rsk/net/simples/SimplePeer.java
rskj-core/src/test/java/co/rsk/net/sync/PeersInformationTest.java
rskj-core/src/test/java/org/ethereum/net/HelloMessageTest.java
rskj-core/src/test/java/org/ethereum/net/rlpx/HandshakeHandlerTest.java
rskj-core/src/test/resources/rskj.conf

I have implemented the analysis documentation that explores various options for enabling SNAP feature discovery among connected peers. You can view the detailed analysis here: [SNAP Feature Discovery Analysis](https://www.notion.so/iovlabs/DRAFT-Analyse-possible-options-for-SNAP-feature-discovery-among-connected-peers-148f805e06fc4b778cb5bf8a21059a7c)
Establishing a decentralized approach for RSKj nodes to seamlessly discover and establish connections with SNAP-sync-provider peers during their initial connection phase. This enhancement will focus on integrating a new capability into the HelloMessage and HandshakeHandler classes, thereby facilitating efficient peer discovery and connectivity within the network

Adding SNAP capability

---

rskj-core/src/integrationTest/java/co/rsk/snapshotsync/SnapshotSyncIntegrationTest.java
rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java
rskj-core/src/main/java/co/rsk/net/sync/BlockConnectorHelper.java
rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java
rskj-core/src/main/java/co/rsk/net/sync/SnapSyncState.java
rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java
rskj-core/src/test/java/co/rsk/net/sync/BlockConnectorHelperTest.java
rskj-core/src/test/java/co/rsk/net/sync/SnapSyncStateTest.java

The main purpose of this PR is to add the onStateChunkResponseError method, so if during the process of a stateChunkResponse, an error happens we ask for the same stateChunk again and to another peer if possible.

Add on error handler for snap blocks

---

rskj-core/src/main/java/co/rsk/peg/PegUtilsLegacy.java
rskj-core/src/main/java/co/rsk/peg/federation/ErpFederation.java
rskj-core/src/test/java/co/rsk/peg/federation/PowpegMigrationTest.java

Once the method signature on RedeemScriptParser#extractStandardRedeemScript is changed, we need to apply this to RSKj to modify how the method is used from it.
Old method signature: Script extractStandardRedeemScript();
New method signature: List<ScriptChunk> extractStandardRedeemScriptChunks();
This relates to the Reactors to add SegwitRedeemScriptParser.
Unit Tests.

Change method signature on extractStandardRedeemScript

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageIndexKey.java

Just as we did with the [fund transaction unsigned hash](https://github.com/rsksmart/rskj/blob/feature/powpeg_validation_protocol/rskj-core/src/main/java/co/rsk/peg/BridgeStorageIndexKey.java#L26), we need to save the spend transaction hash to be able to identify it when trying to register it later.

Create SVP spend tx hash unsigned storage entry

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java

To save the spend transaction (unsigned) hash in the repository, we need to create new methods in BridgeStorageProvider: one for setting the variable and another one for saving it in the repository.

Create set and save SvpFundTransactionHashUnsigned methods

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java

Both setSvpSpendTransactionUnsignedHash and saveSvpSpendTransactionUnsignedHash methods have been created. To have all the flow covered, we now have to create the getSvpSpendTransactionUnsignedHash one.

Create getSpendTransactionHashUnsigned method

---

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerTest.java

Update the logging method to receive a Coin with the value in weis. Log the amount in weis or satoshis according to RSKIP427 activation

Change logReleaseBtcRequestRejected to receive co.rsk.core.Coin

---

rskj-core/src/main/java/org/ethereum/vm/program/Program.java

- removed unused method
- suppressed false positive sonar warning

fix(pte): suppress sonar warnings

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeState.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/StateForFederator.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java

To proceed with its signing, the spend transaction object has to be accessed from the storage. In order to do so, we need to include serialization and deserialization for map entries using the RLP format. This also includes a minor refactor to the existing logic. 

Create new svpSpendTxWaitingForSignatures storage entry with Serialization/Deseralization Logic 

---

.github/workflows/rit.yml

This GitHub Actions workflow is designed to automate the execution of Rootstock Integration Tests for the RSKj repository. It replaces the previous Jenkins-based setup with a streamlined and integrated GitHub Actions workflow. The primary goal is to ensure that integration tests are run manually or automatically for opened pull requests against the `master` branch or any `*-rc` branches, as well as for direct pushes to these branches.
**Triggers**:
- **Pull Requests**: The workflow triggers on pull requests opened or reopened against any branch, specifically targeting `master` and `*-rc` branches.
- **Push Events:** The workflow triggers on pushes to `master` and `*-rc` branches.
- **Manual Trigger**: The workflow can be manually triggered using the `workflow_dispatch` event, which allows …

Adding Rootstock Integration Tests workflow

---

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestUtil.java

To avoid keep using the `mockChainOfStoredBlocks` method, two new ones were created to recreate a valid chain that has:
- a valid partial merkle tree with the wanted transactions
- the block with that merkle root stored at wanted height
- a new chainhead stored block at wanted height

Add methods to create a real valid chain with stored blocks to avoid using mocks

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

Add a method to check if svp period is ongoing

Add method to check if svp is ongoing

---

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
rskj-core/src/main/java/org/ethereum/util/Utils.java
rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java

Currently, the `web3_clientVersion()` RPC call always returns a hardcoded Java version string, such as `Java1.8`, in the client version string (`e.g., RskJ/6.3.1/Linux/Java1.8/ARROWHEAD-27cba5598`). We need to update this functionality to return the actual Java major version in the format `Java<MAJOR_VERSION>` (e.g., `Java8`, `Java17`, etc.)
Providing the real Java major version in the `web3_clientVersion` RPC call will enhance accuracy and help users and developers better understand the Java environment in use. This improvement is crucial for debugging and ensuring compatibility with various Java versions.

Refactor Java version output in web3_clientVersion

---

rskj-core/src/main/java/co/rsk/peg/FlyoverCompatibleBtcWallet.java
rskj-core/src/main/java/co/rsk/peg/PegUtilsLegacy.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

- Update tests to use script builders instead of the deprecated static method inside the parsers 
- Fix MultiSigType.ERP_FED reference to MultiSigType.NON_STANDARD_ERP_FED after refactoring.
- Update isPegOutTx and isValidPegInTx instead of passing script sig, pass redeem script chunks to RedeemScriptParserFactory.get.
To support new refactors in bitcoinj thin.
Unit tests

Update ErpRedeemScriptParser reference to new name and fix tests failing after RedeemScriptParserFactory refactor

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java

Now we are able to save the spend transaction in the `svpSpendTxWaitingForSignatures` entry. So now we need a method to get the transaction saved.

Create getSvpSpendTxWaitingForSignatures method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeState.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/StateForFederator.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java

Also add serialization for rsk tx hash to reuse it when possible

Add serialization for btc tx to avoid passing boolean, and reuse it when possible

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/FlyoverCompatibleBtcWallet.java
rskj-core/src/main/java/co/rsk/peg/PegUtilsLegacy.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/FlyoverCompatibleBtcWalletWithStorageTest.java
rskj-core/src/test/java/co/rsk/peg/FlyoverCompatibleBtcWallextWithSingleScriptTest.java
rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java
rskj-core/src/test/java/co/rsk/peg/federation/PowpegMigrationTest.java
rskj-core/src/test/java/co/rsk/peg/performance/RegisterFlyoverBtcTransactionTest.java

Stop using FastBridgeRedeemScriptParser and legacy builder; instead, use FlyoverRedeemScriptParser and FlyoverRedeemScriptBuilderImpl to create flyover redeem scripts.
This is related to refactors done in bitcoinj-thin where the FastBridge parser was replaced by a new simpler parser called FlyoverRedeemScript parser.
Unit Tests

Stop using FastBridgeRedeemScriptParser and legacy builder

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/StateForFederator.java
rskj-core/src/main/java/co/rsk/peg/StateForProposedFederator.java
rskj-core/src/test/java/co/rsk/peg/StateForFederatorTest.java
rskj-core/src/test/java/co/rsk/peg/StateForProposedFederatorTest.java

New DTO class called `StateForProposedFederator`, which would act similar to existing`StateForFederator`. It will receive the `svpSpendTxWaitingForSignatures` to notify the pegnatories.
Also includes a refactor of `StateForFederator`. 

Create StateForProposedFederator and Refactor StateForFederator

---

.github/workflows/build_and_test.yml
.github/workflows/codeql.yml
Dockerfile
rskj-core/build.gradle
rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
rskj-core/src/main/java/co/rsk/util/PreflightChecksUtils.java
rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java
rskj-core/src/test/java/co/rsk/util/PreflightChecksUtilsTest.java
rskj-core/src/test/java/org/ethereum/TestUtils.java
rskj-core/src/test/java/org/ethereum/net/server/ChannelManagerImplTest.java

`fed:vovchyk/min-java-ver-bump`

chore: increase min supported java version to 17

---

rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
rskj-core/src/test/java/co/rsk/peg/FlyoverCompatibleBtcWalletWithStorageTest.java
rskj-core/src/test/java/co/rsk/peg/FlyoverCompatibleBtcWallextWithSingleScriptTest.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java

- Stop using FastBridgeErpRedeemScriptParser. Now, it uses FlyoverRedeemScriptBuilderImpl to create flyover redeem scripts.
- Replace Fast Bridge MultiSigTypes for MultiSigType.FLYOVER
- Move logic to check if the redeem script is Erp to its own method
This is related to refactors done in bitcoinj-thin, where the FastBridgeErpParser static method to create FastBridgeRedeemScripts was removed. Now, rskj should use `FlyoverRedeemScriptBuilderImpl` to create FlyoverRedeemScripts.
Unit Tests

Stop using FastBridge enum and FastBridgeErpRedeemScriptBuilder

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/StateForFederator.java
rskj-core/src/main/java/co/rsk/peg/StateForProposedFederator.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java

The spend transaction should be signed as any other peg-out, but by the proposed powpeg. For this to happen, we need the proposed pegnatories to know when the spend transaction is waiting for signatures.
This also includes a small fix where the `StateForFederators*` where serializing their corresponding RLP raw data twice.

Create new getStateForSvpClient Bridge Method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

Create a utility method to remove signatures from a bitcoin transaction

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/NonStandardErpRedeemScriptBuilderTest.java

Add tests for NonStandardErpRedeemScriptBuilder
This is related to refactors done in bitcoinj-thin, where the NonStandardErpRedeemScriptBuilder static method to create NonStandardErpRedeemScript was removed. Now, rskj should use only `NonStandardErpRedeemScriptBuilder` to create NonStandardErpRedeemScript.
Unit Tests

Add tests for NonStandardErpRedeemScriptBuilder

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/P2shErpRedeemScriptBuilderTest.java

Add tests for P2shErpRedeemScriptBuilder
This is related to the refactors done in bitcoinj-thin, where the P2shErpRedeemScriptBuilder static method to create P2shErpRedeemScript was removed. Now, rskj should use only `P2shErpRedeemScriptBuilder` to create P2shErpRedeemScript.
Unit Tests

Add tests for P2shErpRedeemScriptBuilder

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/NonStandardErpRedeemScriptBuilderHardcodedTest.java

Add tests for NonStandardErpRedeemScriptBuilderHardcoded
This is related to refactors done in bitcoinj-thin, where the NonStandardErpHardcodedRedeemScriptBuilder static method to create NonStandardErpRedeemScriptHardcoded was removed. Now, rskj should use only `NonStandardErpRedeemScriptBuilderHardcoded` to create NonStandardErpRedeemScriptHardcoded.
Unit Tests

Add tests for NonStandardErpRedeemScriptBuilderHardcoded

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/NonStandardErpRedeemScriptBuilderWithCsvUnsignedBETest.java

Add tests for NonStandardErpRedeemScriptBuilderWithCsvUnsignedBE
This is related to refactors done in bitcoinj-thin, where the NonStandardErpRedeemScriptBuilder static method to create NonStandardErpRedeemScript was removed. Now, rskj should use only `NonStandardErpRedeemScriptBuilder` to create NonStandardErpRedeemScript.
Unit Tests

Add tests for NonStandardErpRedeemScriptBuilderWithCsvUnsignedBE

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

When the fund transaction is registered, we can proceed with the spend transaction (i.e., the transaction that will send back the funds from the proposed federation to the active one) process: its creation, its addition to the corresponding `svpSpendTxHashUnsigned` storage entry and `svpSpendTxWaitingForSignatures` map entry, and the broadcast of the `release_requested` and `pegout_transaction_created` events needed for the hsm signing.
In this pr:
-Create a new method `processSvpSpendTransactionUnsigned` that will:
create the spend transaction as described [here](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP419.md?plain=1#L151)
add it to the `svpSpendTxHashUnsigned` storage entry
add it and the rsk hash of the spend transaction creation to the `svpSpendTxWaitingForSignatures` …

Svp spend transaction creation

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

Update test in BitcoinUtilsTest to use deterministic keys

---

rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java

Since we are unit-testing, there's no need to pass arguments to the assertion methods.
We can use global variables to make the code cleaner and improve readability

Refactor BridgeEventLoggerImplTest

---

rskj-core/src/main/java/co/rsk/peg/bitcoin/FlyoverRedeemScriptBuilderImpl.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/FlyoverRedeemScriptBuilderImplTest.java

- Add internal redeem script validations to flyover redeem script builder
- Add missing and corner tests to FlyoverRedeemScriptBuilderImplTest
This is related to refactors done in bitcoinj-thin, where the FastBridgeErpParser static method to create FastBridgeRedeemScripts was removed. Now, rskj should use FlyoverRedeemScriptBuilderImpl to create FlyoverRedeemScripts.
Unit Tests

- Add tests and internal redeem script validations to flyover

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/PegUtils.java
rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

The empty input script has to be added for every svp spend tx input.

Add missing empty p2sh input script to svp spend transaction

---

rskj-core/src/main/java/co/rsk/core/types/bytes/Bytes.java
rskj-core/src/main/java/co/rsk/core/types/bytes/BytesSlice.java
rskj-core/src/main/java/co/rsk/core/types/bytes/HexPrintableBytes.java
rskj-core/src/main/java/org/ethereum/core/CallTransaction.java
rskj-core/src/main/java/org/ethereum/solidity/SolidityType.java
rskj-core/src/main/java/org/ethereum/util/RLP.java
rskj-core/src/main/java/org/ethereum/util/RLPItem.java
rskj-core/src/main/java/org/ethereum/util/RLPList.java
rskj-core/src/main/java/org/ethereum/util/Utils.java
rskj-core/src/test/java/co/rsk/core/CallTransactionTest.java
rskj-core/src/test/java/co/rsk/core/TransactionTest.java
rskj-core/src/test/java/co/rsk/core/types/bytes/BytesSliceTest.java
rskj-core/src/test/java/co/rsk/core/types/bytes/BytesTest.java
rskj-core/src/test/java/co/rsk/util/Functions.java
rskj-core/src/test/java/org/ethereum/core/TransactionTest.java
rskj-core/src/test/java/org/ethereum/solidity/SolidityTypeTest.java
rskj-core/src/test/java/org/ethereum/util/RLPTest.java
rskj-core/src/test/java/org/ethereum/util/UtilsTest.java

perf: improve decoding in CallTransaction

---

rskj-core/src/main/java/co/rsk/peg/PegUtilsLegacy.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java

- Resolve pending `TODO` about removing legacy code once RSKIP353 gets activated and P2shErpRedeemScriptParser starts to be used
- A couple of tests had to be updated. 
-- When sending funds from a p2sh erp fed(using the active fed keys) to the active federation:
---Before removing the legacy code: the method `co.rsk.peg.PegUtilsLegacy#isValidPegInTx` was returning true because it was failing when parsing the script and then couldn't find any utxo below the minimum(this was a bug that got fixed later).
--- After removing the legacy code: now the method `co.rsk.peg.PegUtilsLegacy#isValidPegInTx is returning false since the sender is being identified as equal to the active federation. 
Unit tests

Eliminate legacy todo and update tests

---

rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java

Currently we are casting method references to a raw type of the functional generic interface `BridgeMethodExecutorTyped`. This means we not providing the specific type parameter that `BridgeMethodExecutorTyped` expects.
By using a raw type, we lose the information about what type `T` should be. This means that any attempt to use the methods of `BridgeMethodExecutorTyped` will not have type safety.
If we later try to call methods that expect a certain type, we might encounter `ClassCastException` at runtime because the compiler won’t be able to enforce type checks.
Unit tests
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.

Fix Type Safety Issues in BridgeMethodExecutorTyped Functions 

---

.github/workflows/build_and_test.yml
.github/workflows/rit.yml

Right now, checks for pull requests (PRs) from external contributors using forked repositories are not passing. The main issue is that the rootstock-integration-tests workflow is attempting to find the branch in the original rsksmart/rskj repository instead of the contributor's fork. Here are the specific problems we've encountered:
`Git Checkout Error: error: pathspec 'vovchyk/status-badge' did not match any file(s) known to git
`
and 
```
SonarQube Execution Error: Execution failed for task '
'.Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to.
```
It appears that the SonarQube check is being triggered …

Adding repo owner input

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java

- Change pegout refund logic in BridgeSupport to return the total value sent to the Bridge post RSKIP427
- Add tests

When rejected pegout is refunded, post RSKIP427 refund the total value sent in weis

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java

For the validation protocol to be successful, we need the spend transaction to be signed and broadcasted by the proposed pegnatories.
Requirements
-Create a new `addSvpSpendTxSignature` method that would add the signatures from the proposed pegnatories to the svp spend transaction.
This method should also remove the spend transaction from the map once is fully signed, and emit the `release_btc` event so the federators can proceed with the broadcast.

Add svp spend tx signature

---

.github/workflows/build_and_test.yml

**Example pr**: https://github.com/rsksmart/rskj/pull/2803
**Job**: https://github.com/rsksmart/rskj/actions/runs/11334162626

Bugfix: Skipping SonarQube analysis on prs from forked repos

---

rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/mine/BlockGasPriceRange.java
rskj-core/src/main/java/co/rsk/mine/MinimumGasPriceCalculator.java
rskj-core/src/main/java/co/rsk/mine/gas/provider/MinGasPriceProviderFactory.java
rskj-core/src/main/java/co/rsk/mine/gas/provider/StableMinGasPriceProvider.java

feat(stableMinGasPrice): add extra logs

---

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

Implementation of [RSKIP427](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP427.md)
`rit:disable-rskip427`

Express the amount value in weis for peg-out related events

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java
rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java

After concluding the validation was a failure, we need to emit the `commitFederationFailed` event and reset all the values that are used in the process for the federation change to be allowed again.
In this pr, a new `processValidationFailure` method is created:
- emit the new `commitFederationFailed` Bridge event
- clear the proposedFederation storage entry
- clear the svp fund tx storage entries
- clear the expected svp spend tx storage entry/ies

Create processValidationFailure method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java

Call `updateSvpState` from `updateCollections`.
Make `updateSvpState` private and adapt tests.

Make updateSvpState private. Call it from updateCollections

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java

- Fix wrong casting to long
- Change proposed federation creationTime to seconds instead of milliseconds
- Improve `svpIsOngoing` readability

Fix wrong casting to long

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/StateForFederator.java
rskj-core/src/main/java/co/rsk/peg/StateForProposedFederator.java
rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/StateForProposedFederatorTest.java

In this PR we address a fix that was caught when running the `powpeg-node` locally. When there is no SVP spend tx waiting for signatures, the `Bridge` currently returns an single serialized empty array. The problem is that the DTO used (`StateForProposedFederator`) assumes that as its predecessor (`StateForFederator`) it should be double serialized. So this change also returns an empty double serialized array using the RLP format. 
The error thrown by the listener in the powpeg-node:
```
2024-11-14-10:52:55.206 TRACE [c.r.f.BridgeTransactionSender]  Bridge call - method: getStateForSvpClient
2024-11-14-10:52:55.207 ERROR [events]  Listener callback failed with exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at …
```

SVP spend tx waiting for signatures default double serialization

---

.github/workflows/build_and_test.yml
build.gradle
rskj-core/src/main/java/co/rsk/rpc/modules/debug/DebugModuleImpl.java

Update Sonar Configurations
Sonar configurations should be updated in order to take advantage of SonarCloud, taking into consideration the recommended way of doing it for [gradle projects](https://docs.sonarsource.com/sonarcloud/advanced-setup/ci-based-analysis/sonarscanner-for-gradle/), adapting it to the context of Github Actions.
By adding a test function plagued by bad practices and with no test coverage (now removed) to confirm that the SonalCloud analysis worked as expected:
N/A

Updating smell test

---

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/federation/VoteFederationChangeTest.java

Last-retired-federation script shouldn't be set in new commitFederation implementation, since we will set the to-be-active-federation after its validation.

Do not set last retired fed p2sh script in new commitFederation impl

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java

This PR refactors the `eth_estimateGas` RPC call on RSK to handle reverted transactions similarly to Geth. Previously, the `eth_estimateGas` call on RSK did not return an error when a transaction was reverted. This change adds a missing check to ensure that when a transaction is reverted, the `eth_estimateGas` call returns an error, aligning with Geth’s behavior. Check this documentation for more info: https://www.notion.so/iovlabs/Analysis-of-eth_estimateGas-Behavior-on-RSKJ-Node-for-Reverted-Transactions-13cc132873f980c0aa87de78ed0f84a0

Handling transaction revert in eth_estimateGas

---

rskj-core/src/main/java/org/ethereum/rpc/parameters/CallArgumentsParam.java
rskj-core/src/test/java/org/ethereum/rpc/parameters/CallArgumentsParamTest.java

fix(rpc): add handling of null call args

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

Since we added [this](https://github.com/rsksmart/rskj/compare/return_feds_creation_time_in_seconds...remove_unnecessary_logs?expand=1#diff-61e5c53e59bedc5790b677df9fb9db0fbe260d86030c6caa00fb9b12a6afc685R417) log, there is no need to log the peg tx type in the specific tx methods

Remove logs that are no longer necessary since the tx type is being logged above

---

rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java
rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationConstantsTest.java
rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationRegTestConstantsTest.java

Make Federation Regtest Constants use a Lazy Singleton Pattern.
Refactor

Make Federation Regtest Constants use a Lazy Singleton Pattern

---

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

Added RSKIP459 activation code
Unit tests

Added RSKIP459 activation code

---

rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

Relates to https://github.com/rsksmart/bitcoinj-thin/pull/125
Since now the logic to get the witness commitment from a coinbase transaction is in the Bridge, it's necessary to also add `extractWitnessCommitmentHash` and avoid dependency to bitcoinj-thin

Add logic to extractWitnessCommitmentHash in the Bridge

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java

`validationPeriodIsOngoing` and `isSvpOngoing` were very similar, so no need to have them both.

Remove validationPeriodIsOngoing method

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

Consumed UTXOs after creating a release transaction were being removed separately in each method.
This should be happening in `settleReleaseRequest` method, since it is where all the release-releated actions happen. 
This pr does that.

Create method to remove utxos used for a release transaction

---

rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationConstantsTest.java

The current activation age in testnet is set to 120 RSK blocks, and the svp validation period to 80 blocks. This is going to be insufficient to complete the SVP validations.
A safe value to ensure that the SVP has enough time to be validated is 2000 RSK blocks.
This change implies also update the activation age just for testnet.

Update testnet validation period duration and activation age

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/PegUtils.java
rskj-core/src/main/java/co/rsk/peg/pegin/PeginProcessAction.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java
rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
rskj-core/src/main/java/co/rsk/peg/utils/NonRefundablePeginReason.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportRejectedPeginTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsEvaluatePeginTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerTest.java

Mark rejected pegins as processed once RSKIP459 is active.
Peg-in transactions rejected by the Bridge should be marked as processed to ensure that the `rejected_pegin` event is emitted only once per transaction.
Unit tests

Mark invalid pegin as processed

---

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java

Return _null_ early in public method when having an empty RLPList

Return null early in public method instead of in private one.

---

rskj-core/src/main/java/org/ethereum/config/Constants.java
rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorIntrinsicGasLimitValidatorTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeCostsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeIT.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportIT.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationTestUtils.java

Erase the constant REGTEST_FEDERATION_PRIVATE_KEYS from the tests

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/test/java/co/rsk/RskTestUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java

`ADD_SIGNATURE` Bridge's method should only be callable from active, retiring or proposed federations.

Allow proposed fed to call add signature

---

rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

Refactor findWitnessCommitment method to find witness commitment from script bytes, removing
Avoid parsing outputs when finding witness commitment since they can be in nonstandard format, causing script exceptions.
Unit tests

Refactor findWitnessCommitment method

---

.github/dependabot.yml
.github/workflows/build_and_test.yml
.github/workflows/docker-release.yml
.github/workflows/docker-verification.yml
Dockerfile
rskj-core/src/main/java/co/rsk/util/PreflightChecksUtils.java
rskj-core/src/main/resources/version.properties
rskj-core/src/test/java/co/rsk/util/PreflightChecksUtilsTest.java

We noticed that some instances with java 21 docker is having issues with synching, due to that, we are reverting to a previous version to perform more validations before upgrade.
`fed:ARROWHEAD-6.5.0.0`

Using build from eclipse java temurin 17

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java
rskj-core/src/main/resources/expected.conf
rskj-core/src/main/resources/reference.conf
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java

Ignore non-standard outputs when searching for the witness commitment hash.
Coinbase transactions may sometimes contain non-standard outputs that cause the Bridge to fail parsing them. When iterating through the outputs of a coinbase transaction in search for the witness commitment hash, non-standard outputs should be ignored and continue searching through the remaining outputs.
Unit tests
`fed:coinbase-parsing-integration-rebased`

Ignore non-standard outputs when searching for the witness commitment hash

---

rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java

feat(rpc): add mixHash field to block dto with zero value

---

rskj-core/src/main/java/org/ethereum/rpc/FilterManager.java

feat(logging): add logs to FilterManager class

---

.github/workflows/rit.yml

build(slack-notification): Fix rit GH workflow to not send slack notification with empty token

---

.github/workflows/rit.yml

Update rit.yml to use v2 of RIT

---

rskj-core/src/main/java/co/rsk/rpc/modules/debug/trace/call/CallTraceTransformer.java
rskj-core/src/test/java/co/rsk/rpc/modules/debug/trace/call/CallTracerTest.java
rskj-core/src/test/resources/dsl/call_tracer_internal_oog.txt

fix(callTracer): fix missing top-level error field in response

---

rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorIntrinsicGasLimitValidatorTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeCostsTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeIT.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportIT.java
rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java
rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationTestUtils.java

BridgeRegTestConstants is now a singleton. BridgeRegTestConstants stores the instance of FederationRegTestConstants in a global variable. Since all the tests share this variable, the test will fail if they try to use different Regtest federation private keys.

Rollback the custom regtest federation private keys to the default ones

---

rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java

We fixed a performance issues directly related to some logging within `PeerAndModeDecidingSyncState.java`.
We added some boton instances to test this specially from [master branch](https://github.com/rsksmart/rskj/tree/master) and [snap-v4-final](https://github.com/rsksmart/rskj/tree/snap-v4-final). With the help of Grafana + Prometheus we noticed the problem here:
Without snap sync:
With Snap sync:
After more investigation in the codebase we noticed that printing the logs was time consuming for a method that is concurrently called per each node sync, so we needed to update it to use `trace()` method instead, so this is not logged as default.
After using `trace()` instead, we can see the following improvement in the node with Snap Sync:
When experimenting with baseline, the node sends …

Use trace() logs to increase node perf

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

A little test that creates a transaction with two inputs: legacy and segwit compatible. Then, we try to extract the redeem script from both.

Test: Extract redeemscript from multiple types of inputs

---

rskj-core/src/main/java/co/rsk/NodeRunnerImpl.java
rskj-core/src/main/java/co/rsk/RskContext.java
rskj-core/src/main/java/co/rsk/util/SystemUtils.java
rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ActivationConfig.java
rskj-core/src/test/java/co/rsk/util/SystemUtilsTest.java

We are printing a warning message when running the node so we know which NetworkUpgrade are disabled at the point of the node running.
We had an issue where the node of a client was creating a hard fork due to client not having the latest network upgrade `LOVELL700` enabled / added to their config.
We spent a lot of time trying to investigate the issue and we found out it was a configuration issue. If have noticed the configuration issue before we wouldn't spend a lot of time debugging the problem.
We just ran a node from scratch. At the beginning since the block is at height of 0, all the existing network upgrades will be shown, even if they are added to the rsk config, because they will not be active due to the best block height.
Finally, the same node was restarted, so we were able to …

Print warning message when we find any disabled network upgrade

---

rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java

Reorder the tests so they are sorted by extractRedeemScriptFromInput or getFirstInputSighHash.
Create a GetRedeemScript test for the following cases:
- segwit pegout
- segwit pegout multiples ins & out
- segwit pegout with no change for the fed
- segwit migration
- segwit migration multiples ins & out

Sig hash added test

---

rskj-core/src/main/java/co/rsk/peg/BridgeStorageIndexKey.java
rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java

**Background**
To be able to sign segwit-compatible transactions, we need to save the releases outpoints values in the storage.
New entries will be added at runtime and added to the existing ones in storage.
To avoid consuming too much space in storage, each entry will have its own storage key, and its outpoints as the saved value.
_Note: we shouldn't be allowed to call any of these methods pre RSKIP305_
**Requirements**
-Create **set** and **get** methods to set and get specific `releaseTxHash` outpoints values.
-Create **save** method that adds new values to the storage.

Add release outpoints values structure to bridge storage provider

---

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/bitcoin/UtxoUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestUtil.java

**Background**
The releases outpoints values should be saved every time a release request is created, i.e., every time the `pegoutTransactionCreated` event is emitted.
This happens in three scenarios:
1. A release is created (batch pegout / migration / spend tx)
2. A normal pegin should be refunded
3. A flyover pegin should be refunded (if it surpasses locking cap)
**Requirements**
-Set release outpoints values info every time a release transaction is created.
-Add tests for each different scenario

Save release transaction outpoints values when creating pegout

---

.github/workflows/docker-release-master-to-edge.yml

Fixing the docker release pipeline to update also `master` tag when there is a push on master.
It solves the issue of generate master docker tag when we push to master.
It will be tested once we merge to master.
Testing locally it worked: https://github.com/rmoreliovlabs/rskj/actions/runs/14897575674/job/41842968609
You can see that only `edge` and `master` have recent pushes

Changing the pipeline to release it also on master

---

rskj-core/src/main/java/co/rsk/rpc/modules/eth/AccountOverride.java
rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleDSLTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/AccountOverrideTest.java
rskj-core/src/test/java/org/ethereum/util/EthModuleTestUtils.java
rskj-core/src/test/resources/dsl/eth_module/check_balance.txt
rskj-core/src/test/resources/dsl/eth_module/simple_contract.txt

Implements state override handling in EthModule to allow temporary account modifications during eth_call.
This PR introduces the necessary changes to support the state override feature in the EthModule. This allows modified account state (e.g., balance, nonce, code, or storage) to be temporarily applied when executing eth_call, without persisting those changes to the blockchain.
These changes are part of the effort to improve compatibility with Ethereum’s eth_call behavior and enable more advanced use cases such as contract testing and simulation.

Add state override support to EthModule for eth_call

---

rskj-core/src/main/java/co/rsk/pcc/secp256k1/Secp256k1PrecompiledContract.java

Adding the precompile contract abstract class that will be use to extend the `ADD` and `MUL` operations.
For more information see [**[RSKIP516](https://github.com/rsksmart/RSKIPs/blob/secp256k1/IPs/RSKIP516.md)**](https://github.com/rsksmart/RSKIPs/blob/secp256k1/IPs/RSKIP516.md)
We want to introduce precompiles for point addition (ADD) and scalar multiplication (MUL) on the elliptic curve `secp256k1`. Having efficient operations on this curve is essential to enable musig2 functionality in contracts that need to coordinate the aggregation of signatures for Bitcoin transactions.
For more information see [**[RSKIP516](https://github.com/rsksmart/RSKIPs/blob/secp256k1/IPs/RSKIP516.md)**](https://github.com/rsksmart/RSKIPs/blob/secp256k1/IPs/RSKIP516.md)
N / A

Add the abstractions for the math operations Secp256k1PrecompiledContract

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java

Add increaseUnionBridgeLockingCap method to the Bridge class
Unit Tests

Add increaseUnionBridgeLockingCap method to the Bridge class

---

rskj-core/src/main/java/co/rsk/peg/federation/StandardMultisigFederation.java
rskj-core/src/test/java/co/rsk/peg/federation/StandardMultisigFederationTest.java

Remove standard federation script size validation on creation
Federations are always serialized and deserialized as standard multisig federations. Because the standard multisig information is the important data to keep in storage. ERP related information is obtained from the Bridge constants.
This is also true for P2WSH-P2SH federations, but these federation can now have up to 20 members. So the script size validation done in the creation of standard multisig federations needs to be moved to `getRedeemScript` method. Basically, no validation is done when creating the federation, only whn getting the redeem script

Remove standard federation size validation

---

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java

Get rid of activations in union storage get address
Unit tests

Refactor `getAddress` to remove activations parameter

---

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java

Get rid of activations checks of `weisTransferredToUnionBridge` logic
Unit tests

Get rid of activations checks of `weisTransferredToUnionBridge` logic

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupport.java
rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java
rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeConstants.java
rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeMainNetConstants.java
rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeRegTestConstants.java
rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeTestNetConstants.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
rskj-core/src/test/java/co/rsk/peg/union/constants/UnionBridgeConstantsTest.java

Replace BitcoinJ Coin with RSK core Coin across UnionBridge impl to get rid of conversions when doing operations with locking cap and weisTransferred together

Replace BitcoinJ Coin with RSK core Coin across UnionBridge impl

---

rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java
rskj-core/src/test/java/co/rsk/peg/federation/FederationChangeIT.java
rskj-core/src/test/java/co/rsk/test/builders/PegoutTransactionBuilder.java

BitcoinUtils::removeSignaturesFromMultiSigTransaction method can now remove signatures from both legacy and witness transactions.
Unit tests added.
Improvements in other utils methods and PegoutTransactionBuilder

Update BitcoinUtils to also remove signatures from witness transactions

---

rskj-core/src/main/java/co/rsk/peg/Bridge.java
rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeIT.java

Added network check to the `setUnionBridgeContractAddressForTestnet` function to ensure it is disabled when the network is Mainnet.
Unit tests

Add network check to `setUnionBridgeContractAddressForTestnet` BridgeMethod

---

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java
rskj-core/src/main/java/co/rsk/peg/union/UnionResponseCode.java
rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
rskj-core/src/test/java/co/rsk/peg/union/UnionResponseCodeTest.java

Removed redundant network check for the `setUnionBridgeContractAddressForTestnet` method from `UnionBridgeSupportImpl` and updated related tests accordingly.
Unit tests

Remove  redundant network check for setUnionBridgeContractAddressForTestnet in UnionBridgeSupportImpl

---

rskj-core/src/main/java/co/rsk/peg/vote/ABICallElection.java
rskj-core/src/main/java/co/rsk/peg/vote/AddressBasedAuthorizer.java
rskj-core/src/test/java/co/rsk/peg/vote/AddressBasedAuthorizerFactoryTest.java
rskj-core/src/test/java/co/rsk/peg/vote/AddressBasedAuthorizerTest.java

Renamed methods:
- `getNumberOfAuthorizedKeys` to `getNumberOfAuthorizedAddresses`
- `getRequiredAuthorizedKeys` to `getRequiredAuthorizedAddresses`
Unit tests

Rename AddressBasedAuthorizer methods for clarity and consistency
