rskj-core/src/main/java/co/rsk/net/BlockProcessor.java, rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleBlockProcessor.java
Improving sending status to all when syncing
=> Sending status

rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java, rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorUnclesTest.java
Removing unneeded uncle processing
=> Improving Add Block to Blockchain in Node Block Processor

rskj-core/src/main/java/co/rsk/db/ContractDetailsImpl.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/main/resources/config/rsk-sample.conf
Load blockchain from database when node restart
Database reset should be false in restart
Blockstore flush should be enable when collect data
=> Load blockchain

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java
Log was not showing competing difficulties when rebranching is made
=> Improved logs for rebranching

rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java, rskj-core/src/main/java/org/ethereum/db/BlockStore.java, rskj-core/src/main/java/org/ethereum/db/BlockStoreDummy.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascTestBlockStore.java
Modified algorithm in case the best number maps to a fork
=> Load total difficulty from best block hash

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/org/ethereum/core/Blockchain.java, rskj-core/src/main/java/org/ethereum/db/BlockInformation.java, rskj-core/src/main/java/org/ethereum/db/BlockStore.java, rskj-core/src/main/java/org/ethereum/db/BlockStoreDummy.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/main/java/org/ethereum/rpc/TypeConverter.java, rskj-core/src/main/java/org/ethereum/rpc/Web3.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/co/rsk/core/BlockchainDummy.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascTestBlockStore.java, rskj-core/src/test/java/org/ethereum/db/IndexedBlockStoreTest.java, rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleBlockChain.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
=> Blocks by number

rskj-core/src/main/java/co/rsk/net/BlockProcessResult.java, rskj-core/src/main/java/co/rsk/net/BlockProcessor.java, rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorTest.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleBlockProcessor.java
This will let accept higher blocks (>1000) if block sync does not make progress in X time
=> Accept advanced blocks afterntime

README.md, circle.yml
Add circleci configuration file to run tests.
Modify badge on readme to show circleci tests results
=> Change jenkins for circleci

README.md, circle.yml
Change badge in README.md
Watch all branches
=> Fix Circle

README.md, circle.yml
Fix README.md badge
Watch all branches
=> Circle fix master

rskj-core/src/main/resources/version.properties
Version change for next Ginger release.
=> Version change for next Ginger release

rskj-core/build.gradle, rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/main/java/co/rsk/peg/BridgeState.java, rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/StateForFederator.java
Segwit-related fixes in Bridge
=> Bridge Segwit fixes

rskj-core/src/main/java/org/ethereum/core/Block.java, rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java, rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java
Comments added.
Minor improvement: transactions and uncles list in block are exposed as read-only collections
=> Copyonwrite (not removed)

rskj-core/src/main/java/co/rsk/validators/BlockUnclesValidationRule.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java, rskj-core/src/test/java/co/rsk/validators/BlockUnclesValidationRuleTest.java
Few lines were added to uncle rule, with new expected behavior tests
=> Check no sibling in uncles

rskj-core/src/main/java/org/ethereum/rpc/Web3.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
This method is not included in Web3 interface.
=> Removing add account web3 method

rskj-core/build.gradle
=> Remove exclude

rskj-core/build.gradle
=> Fix sonar paths

configure.sh
- Change in configure.sh to support Windows platform. The unames included are: **MINGW32_NT-10.0-WOW and MINGW64_NT-10.0**
=> Support Windows - configure.sh 

rskj-core/src/main/java/org/ethereum/core/Block.java, rskj-core/src/test/java/co/rsk/core/BlockTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/simples/SimpleBlock.java
This adds some basic immutability checks. It uncovers some tech debt in the bridge tests.
=> Uses unmodifiableList for transactions in Block.getTransactionsList

rskj-core/src/main/java/org/ethereum/config/SystemProperties.java, rskj-core/src/main/java/org/ethereum/core/Transaction.java, rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java, rskj-core/src/main/java/org/ethereum/net/rlpx/Node.java, rskj-core/src/main/java/org/ethereum/util/RLPList.java, rskj-core/src/main/java/org/ethereum/util/Value.java
Fix some sonar issues reported in Quality Gate
=> Fix some sonar bugs

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
The JSON parser used to parse input JSONs in Web3 JSON RPC methods, parses an array of Strings as List. Previous code expected String[]
=> Fix get logs

rskj-core/src/main/java/co/rsk/core/Wallet.java, rskj-core/src/main/java/co/rsk/crypto/KeyCrypter.java, rskj-core/src/main/java/co/rsk/crypto/KeyCrypterAes.java
Renaming KeyCrypterScrypt to KeyCrypterAes to express what it really does.
Docs were updated too.
=> KeyCrypterScrypt -> KeyCrypterAes

rskj-core/src/main/java/co/rsk/scoring/InetAddressBlock.java, rskj-core/src/main/java/co/rsk/scoring/InetAddressTable.java, rskj-core/src/main/java/co/rsk/scoring/InetAddressUtils.java
Fix code smells reporder by Sonar Quality Gate
=> Improve INetAddress related classes

rskj-core/src/main/java/org/ethereum/util/RLP.java, rskj-core/src/main/java/org/ethereum/vm/VMUtils.java
Fixing some code smell from Sonar Quality Gate
=> Remove unused fields and methods

rskj-core/src/main/java/co/rsk/Start.java
It isn't clear from the curernt code in `Start.java` that some pieces of code aren't enabled by default. A call to `enableXXX` should just do that, not perform any validation and decide whether to do it or not.
This PR makes the code intent clearer.
=> Refactor Start so it's clear that JSONRPC (and other features) are disabled by default

circle.yml
Integrate circle with sonar for QG assurance in PR
=> Integrate circle with sonar

rskj-core/src/main/java/co/rsk/core/RskFactory.java, rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java, rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java, rskj-core/src/main/java/co/rsk/net/handler/TxValidator.java, rskj-core/src/main/java/org/ethereum/manager/WorldManager.java, rskj-core/src/main/java/org/ethereum/manager/WorldManagerImpl.java, rskj-core/src/test/java/co/rsk/net/handler/TxValidatorTest.java, rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleWorldManager.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
@ajlopez this should fix the issues you were seeing
=> Fix null PendingState in NodeMessageHandler

rskj-core/src/main/java/co/rsk/trie/TrieImpl.java, rskj-core/src/test/java/co/rsk/trie/TrieImplDeleteTest.java
Fix to change variable to 0, related to issue #75
=> Fix change variable

rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/test/java/co/rsk/util/TestContract.java, rskj-core/src/test/java/org/ethereum/util/RskTestFactory.java, rskj-core/src/test/java/org/ethereum/vm/ProgramTest.java
I used the wrong variables and introduced a bug that wasn't caught by any preexisting test.
This fixes it an adds the mentioned test.
=> Fix CALL and REVERT interaction

rskj-core/src/main/java/org/ethereum/db/ContractDetailsCacheImpl.java
I added a panic in the call of these two methods, although they should never be called
=> Remove unused ContractDetailsImplCache methods

rskj-core/src/main/java/org/ethereum/vm/VM.java
Based on https://github.com/ethereum/ethereumj/commit/4e107d86d8e3b713938292dbdcb3c3941f16f6fd.
I think we should also create an issue to test this behavior.
=> Fix DELEGATECALL gas calculations

rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
New testnet federation for bamboo.
=> Bamboo new Testnet federation

rskj-core/build.gradle, rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/Federation.java, rskj-core/src/main/java/co/rsk/peg/PendingFederation.java, rskj-core/src/test/java/co/rsk/core/AccountDataTest.java, rskj-core/src/test/java/co/rsk/core/AccountFileLoaderTest.java, rskj-core/src/test/java/co/rsk/db/RepositoryDumpTest.java, rskj-core/src/test/java/co/rsk/mine/TxBuilderTest.java, rskj-core/src/test/java/co/rsk/net/handler/TxHandlerTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/FederationTest.java, rskj-core/src/test/java/co/rsk/peg/PendingFederationTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/co/rsk/trie/SecureTrieImplArityTest.java, rskj-core/src/test/java/co/rsk/trie/TrieImplArityTest.java
It needs more testing. This work will continue after testnet reset
=> Funds migration

rskj-core/src/test/java/co/rsk/remasc/RemascFederationProviderTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
This test file had a lot of obscure hexadecimal values embebed. The new code has global constants and describes the meaning of each constant.
=> Comments added. Obscure bytecode explained

rskj-core/src/test/java/co/rsk/remasc/RemascFederationProviderTest.java
Fix due to incorrect previous merge
=> Remove duplicated @Ignore

rskj-core/src/main/java/org/ethereum/config/CommonConfig.java, rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java
We should make sure that all dbs depend on repository, though
=> delete database before creating it

rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java
Two new tests to check the expected exception when swapn, dupn stack offset calculation generates an overflow
=> Additional tests for expected behavior, dupn, swapn with overflow

rskj-core/src/main/java/co/rsk/net/messages/BodyResponseMessage.java, rskj-core/src/main/java/co/rsk/net/messages/GetBlockHeadersMessage.java, rskj-core/src/main/java/co/rsk/net/messages/NewBlockHashesMessage.java, rskj-core/src/main/java/co/rsk/net/messages/StatusMessage.java, rskj-core/src/main/java/co/rsk/net/messages/TransactionsMessage.java
=> Fixing some Sonar issues in RSK net messages

rskj-core/src/main/resources/logback.xml
Set messageProcessor logger to INFO
=> Add messageProcessor to logback file

rskj-core/src/main/java/co/rsk/net/eth/MessageFilter.java, rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java, rskj-core/src/main/java/co/rsk/net/eth/WriterMessageRecorder.java
=> Fix some Sonar issues in net eth

rskj-core/src/main/java/co/rsk/net/discovery/DiscoveryEvent.java, rskj-core/src/main/java/co/rsk/net/discovery/NodeChallenge.java, rskj-core/src/main/java/co/rsk/net/discovery/NodeChallengeManager.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerDiscoveryException.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerDiscoveryRequest.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorerCleaner.java, rskj-core/src/main/java/co/rsk/net/discovery/UDPChannel.java, rskj-core/src/main/java/co/rsk/net/discovery/UDPServer.java, rskj-core/src/main/java/co/rsk/net/discovery/message/DiscoveryMessageType.java, rskj-core/src/main/java/co/rsk/net/discovery/message/FindNodePeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/MessageDecoder.java, rskj-core/src/main/java/co/rsk/net/discovery/message/NeighborsPeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PeerDiscoveryMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PeerDiscoveryMessageFactory.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PingPeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PongPeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/table/Bucket.java, rskj-core/src/main/java/co/rsk/net/discovery/table/BucketEntry.java, rskj-core/src/main/java/co/rsk/net/discovery/table/BucketEntryComparator.java, rskj-core/src/main/java/co/rsk/net/discovery/table/DistanceCalculator.java, rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceComparator.java, rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceTable.java, rskj-core/src/main/java/co/rsk/net/discovery/table/OperationResult.java, rskj-core/src/main/java/co/rsk/net/discovery/table/PeerDiscoveryRequestBuilder.java
Fixing some Sonar issues (style refactor) in net discovery package
=> Fixing some Sonar issues, style refactor

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/config/GasLimitConfig.java, rskj-core/src/main/java/co/rsk/config/MiningConfig.java, rskj-core/src/main/java/co/rsk/config/RemascConfig.java, rskj-core/src/main/java/co/rsk/config/RemascConfigFactory.java, rskj-core/src/main/java/co/rsk/config/RskConfigurationException.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java
=> Fixing some Sonar issues, style refactor, Config package

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/core/bc/PendingStateImpl.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/java/co/rsk/net/discovery/table/Bucket.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleWalletEnabled.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoring.java, rskj-core/src/main/java/co/rsk/trie/TrieImpl.java, rskj-core/src/main/java/org/ethereum/datasource/DataSourcePool.java, rskj-core/src/main/java/org/ethereum/datasource/HashMapDB.java, rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/main/java/org/ethereum/db/RepositoryTrack.java, rskj-core/src/main/java/org/ethereum/sync/SyncPool.java
Minor changes on classes to avoid thread syncing issues
=> Added restrictions to avoid desync problems

.circleci/config.yml, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
I suggest to first merge #329 so the integration tests became runnable again
=> Properly register UTXOs from migration funds

rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
Add installer config path.
Remove unused paths.
=> Modify config read paths

rskj-core/src/main/resources/logback.xml
Set all logback loggers to info in order to reduce node verbosity.
=> Set logback to info

rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/main/resources/logback.xml
it makes contract execution 200 times slower.
=> Removed logging of VM and GAS from config file 

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/remasc/Remasc.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeStateTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascFederationProviderTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java
I'm still working on integration tests and figuring out how to set the starting fee per kb (maybe set it in the genesis?).
=> Persist Bridge's fee per kb and allow changing it through voting

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
As discussed internally, we will make the minimum `feePerKb / 2`, according to the average transaction size of 500 bytes.
=> Make minimum funds to migrate depend on the current fee per kb

rskj-core/src/main/java/co/rsk/core/bc/FamilyUtils.java, rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorGasLimitValidator.java, rskj-core/src/main/java/co/rsk/net/handler/txvalidator/TxValidatorNotRemascTxValidator.java, rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorGasLimitValidatorTest.java, rskj-core/src/test/java/co/rsk/net/handler/txvalidator/TxValidatorNotRemascTxValidatorTest.java
Additional null control after retrieving uncles; transaction validation new log messages
=> Bamboo fixes to master

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
And updating unit tests accordingly.
=> Setting bridge gas costs as per estimation

rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
Feexkb signers where not being considered when determining if Bridge txs are free.
=> Consider feexkb signer in free bridge txs period

rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java
This was done using the following code:
```java
public static void main(String[] args) {
Stream.of(
BtcECKey.fromPublicOnly(Hex.decode("04b53899c390573471ba30e5054f78376c5f797fda26dde7a760789f02908cbad2aafaaa2611606699ec4f82777a268b708dab346de4880cd223969f7bbe5422bf")),
BtcECKey.fromPublicOnly(Hex.decode("047319afb15481dbeb3c426bcc37f9a30e7f51ceff586936d85548d9395bcc2344f6f082925b6b823106d21b2aa0572701bf1cd007c41d0c36822aac4cf04412ca")),
BtcECKey.fromPublicOnly(Hex.decode("0455a2e9bf100c00fc0a214afd1bf272647c7824eb9cb055480962f0c382596a7049b97cdffcdca0f5cd199f4f4ec3a35f7b40a35a16d79b65579b153e7fddf48f")),
BtcECKey.fromPublicOnly(Hex.decode("04566d5ded7c7db1aa7ee4ef6f76989fb42527fcfdcddcd447d6793b7d869e46f7e44c9bf49f31a5b5d9f09aa079e0dd86fb439f0e9f11ded3d305783a25eb4306")), …
```
=> Convert Federator MainNet public keys to compressed format

rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
=> make sure blocks are imported best with new rules

rskj-core/src/main/java/co/rsk/trie/TrieImpl.java
Using PathEncoder in Trie instead of Trie static methods
=> Using PathEncoder in Trie

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/validators/TxsMinGasPriceRule.java, rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java, rskj-core/src/main/java/org/ethereum/sync/SyncPool.java, rskj-core/src/main/java/org/ethereum/vm/VM.java
Some panic where too noisy for incidents that shouldn't be so critical. When we improve our tools we could remove more of the ones we are keeping
=> Remove panics based on team feedback

rskj-core/src/main/java/co/rsk/core/RskFactory.java, rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java, rskj-core/src/main/java/org/ethereum/manager/WorldManagerImpl.java
I needed this b/c I had another `EthereumListener` defined in the context of the Federate node
=> Add qualifier to CompositeEthereumListener bean

rskj-core/src/main/java/co/rsk/net/MessageChannel.java, rskj-core/src/main/java/co/rsk/net/eth/EthMessageSender.java, rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java, rskj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java, rskj-core/src/main/java/org/ethereum/net/rlpx/Node.java, rskj-core/src/main/java/org/ethereum/net/server/Channel.java, rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java, rskj-core/src/main/java/org/ethereum/sync/SyncPool.java, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleMessageChannel.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleNodeChannel.java
Instead of using ByteArrayWrapper and byte[]
=> Using NodeID in channel and sync pool

rskj-core/src/main/java/co/rsk/Start.java, rskj-core/src/main/java/co/rsk/core/RskFactory.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/core/bc/PendingStateImpl.java, rskj-core/src/main/java/co/rsk/core/bc/PendingStateImplNoCleaner.java, rskj-core/src/main/java/org/ethereum/core/PendingState.java, rskj-core/src/main/java/org/ethereum/net/NodeManager.java, rskj-core/src/main/java/org/ethereum/net/client/ConfigCapabilitiesImpl.java, rskj-core/src/main/java/org/ethereum/net/client/PeerClient.java, rskj-core/src/main/java/org/ethereum/net/message/StaticMessages.java, rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java, rskj-core/src/main/java/org/ethereum/sync/SyncPool.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/core/bc/PendingStateImplTest.java, rskj-core/src/test/java/co/rsk/net/simples/SimplePendingState.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java, rskj-core/src/test/java/org/ethereum/net/NodeManagerTest.java, rskj-core/src/test/java/org/ethereum/net/server/ChannelManagerImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/util/RskTestFactory.java
There shouldn't be any other cyclic dependency left
=> Remove cyclic dependencies

rskj-core/src/test/java/org/ethereum/jsontestsuite/TestCase.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java
Removing ByteArrayWrapper usage
=> Using RskAddress in JSON test classes

rskj-core/src/main/java/co/rsk/core/Wallet.java, rskj-core/src/main/java/org/ethereum/core/Account.java, rskj-core/src/main/java/org/ethereum/core/Genesis.java, rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java, rskj-core/src/main/java/org/ethereum/core/genesis/GenesisLoader.java, rskj-core/src/main/java/org/ethereum/vm/program/Storage.java, rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvokeFactoryImpl.java, rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTrace.java, rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java, rskj-core/src/test/java/co/rsk/core/NetworkStateExporterTest.java, rskj-core/src/test/java/co/rsk/core/WalletTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/db/RepositoryImplOriginalTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascTestRunner.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/core/StateTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestProgramInvokeFactory.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/AccountValidator.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/RepositoryValidator.java
=> Using RskAddress in Genesis premine map

rskj-core/src/test/java/co/rsk/vm/MinerHelper.java
Miner Helper was still using autowired fields, now they are removed and tries to be more clear the way it's used the class.
=> Removal of last autowired fields used on project

rskj-core/src/main/java/co/rsk/net/BlockCache.java, rskj-core/src/test/java/co/rsk/net/BlockCacheTest.java
=> Use delegation instead of inheritance in BlockCache

rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PeerDiscoveryMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/table/DistanceCalculator.java, rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceComparator.java, rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceTable.java, rskj-core/src/main/java/org/ethereum/config/NodeFilter.java, rskj-core/src/main/java/org/ethereum/net/NodeHandler.java, rskj-core/src/main/java/org/ethereum/net/rlpx/Node.java, rskj-core/src/main/java/org/ethereum/net/server/Channel.java, rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java, rskj-core/src/main/java/org/ethereum/sync/SyncPool.java, rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/table/NodeDistanceTableTest.java, rskj-core/src/test/java/org/ethereum/net/rlpx/NodeTest.java
This also includes some places where we were using `byte[]` and removes some unused setters.
=> Use NodeID as a replacement of ByteArrayWrapper in more places

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/main/java/org/ethereum/rpc/Web3.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
This extracts `Web3EthModule` from the `Web3` interface, along the lines of `Web3TxPoolModule` in #471.
This is in preparation for `eth_call` with `pending` parameter.
=> Extract Web3EthModule from Web3

rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java, rskj-core/src/main/java/co/rsk/core/RskImpl.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/main/java/org/ethereum/facade/Ethereum.java, rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java, rskj-core/src/test/java/co/rsk/core/ReversibleTransactionExecutorTest.java, rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleEthereum.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/util/RskTestFactory.java
This is (yet again) in preparation for `eth_call` with `pending` parameter.
=> Convert ReversibleTransactionExecutor to a component

rskj-core/src/main/java/co/rsk/rpc/modules/txpool/TxPoolModuleImpl.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/txpool/TxPoolModuleImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
TxPool module methods implementation based on Pending State.
The specs are based on https://github.com/ethereum/go-ethereum/wiki/Management-APIs#txpool
Some unit tests are added for the 3 methods from txpool
=> TxPool methods implemented

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/main/java/co/rsk/rpc/modules/txpool/TxPoolModuleImpl.java, rskj-core/src/main/java/org/ethereum/config/CommonConfig.java, rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java, rskj-core/src/main/java/org/ethereum/listener/EthereumListener.java, rskj-core/src/main/java/org/ethereum/listener/EthereumListenerAdapter.java, rskj-core/src/test/java/co/rsk/config/CommonConfigTest.java, rskj-core/src/test/java/co/rsk/core/SnapshotManagerTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java, rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java, rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTestCase.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java
Fix a missing autowired field when instantiating TxPoolModule. 
Also made some clean up to remove last references to pending state.
=> Fix rebase txpool

rskj-core/src/main/resources/version.properties
Change to current develop version
=> 0.4.2-SNAPSHOT

rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/DevNetConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetFirstForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetFirstForkConfig.java, rskj-core/src/main/java/org/ethereum/vm/MessageCall.java, rskj-core/src/main/java/org/ethereum/vm/OpCode.java, rskj-core/src/main/java/org/ethereum/vm/OpCodes.java, rskj-core/src/main/java/org/ethereum/vm/VM.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvoke.java, rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvokeFactory.java, rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvokeFactoryImpl.java, rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvokeImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeFromVMTest.java, rskj-core/src/test/java/co/rsk/vm/BytecodeCompiler.java, rskj-core/src/test/java/co/rsk/vm/BytecodeCompilerTest.java, rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestProgramInvokeFactory.java, rskj-core/src/test/java/org/ethereum/vm/VMTest.java, rskj-core/src/test/java/org/ethereum/vm/program/invoke/ProgramInvokeMockImpl.java
Same functionality than [this PR](https://github.com/rsksmart/rskj/pull/476).
=> Static call - replay

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/co/rsk/test/World.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
Using receiptStore to retrieve transaction from main chain.
=> Fixing Web3Impl get transaction by hash

rskj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java
Using the same criteria as ethereum https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/net/rlpx/HandshakeHandler.java#L328
=> Set the Hanshake failed log level from error to warn 

rskj-core/src/main/java/co/rsk/FullNodeRunner.java
This was breaking synchronization.
=> Call .start() on TransactionGateway

rskj-core/src/main/java/co/rsk/core/RskFactory.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java, rskj-core/src/main/java/org/ethereum/core/EventDispatchThread.java, rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java, rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java, rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/core/genesis/BlockchainLoaderTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java, rskj-core/src/test/java/org/ethereum/listener/TestCompositeEthereumListener.java, rskj-core/src/test/java/org/ethereum/util/RskTestFactory.java
Revert the changes in #549 that moved listeners execution to another.
=> Revert listeners on a separate thread

rskj-core/src/main/java/co/rsk/config/ConfigLoader.java, rskj-core/src/main/java/co/rsk/config/NodeCliFlags.java, rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java, rskj-core/src/main/resources/config/devnet.conf
This also makes it work again when you specify a configuration file with `blockchain.config.name = "devnet"`
=> Add --devnet parameter

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java, rskj-core/src/main/java/org/ethereum/listener/EthereumListener.java, rskj-core/src/main/java/org/ethereum/listener/EthereumListenerAdapter.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java
Added a new type of event that only emits IMPORTED_BEST blocks instead of any block.
=> Added onBestBlock event

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/net/discovery/NodeChallengeManager.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorerCleaner.java, rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceTable.java, rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java, rskj-core/src/test/java/co/rsk/net/discovery/NodeChallengeManagerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/UDPServerTest.java
Update period and clean up period are separated
=> Update explorer clean up period

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/net/discovery/NodeChallengeManager.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorerCleaner.java, rskj-core/src/main/java/co/rsk/net/discovery/table/NodeDistanceTable.java, rskj-core/src/main/java/org/ethereum/config/DefaultConfig.java, rskj-core/src/test/java/co/rsk/net/discovery/NodeChallengeManagerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/UDPServerTest.java
- Peer explorer clean up
- Separated into two executions update and clean up
=> Bring latest changes on release to master

rskj-core/src/main/java/co/rsk/remasc/Remasc.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
This is a subset of #581. These changes are not meant to change any consensus rule, and as a result we can do integration testing earlier.
=> Remasc BlockCache changes in preparation for Network Upgrade

rskj-core/src/main/java/co/rsk/remasc/Remasc.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
=> Revert PR #586 for not including in upcoming release

rskj-core/src/main/resources/version.properties
Bot, we are hurry for making the upcoming release, please check *fed:0.4.4_release*, *utils:0.4.4_release* and *ci:0.4.4_release* ASAP!
xxo
=> 0.4.4-BAMBOO release

rskj-core/src/main/java/org/ethereum/config/blockchain/HardForkActivationConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/net/DevNetConfig.java, rskj-core/src/main/java/org/ethereum/config/net/MainNetConfig.java, rskj-core/src/main/java/org/ethereum/config/net/RegTestConfig.java, rskj-core/src/main/java/org/ethereum/config/net/TestNetConfig.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
:robot: **build using** *utils:RFS-225* *fed:RFS-225*
=> RFS-225 - renamed firstFork as orchid

rskj-core/src/main/java/org/ethereum/config/blockchain/HardForkActivationConfig.java
**use *fed*:0.5.0 *utilities*:0.5.0**
=> RFS-225 - renamed config property

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeStorageConfiguration.java, rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestOrchidConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetOrchidConfig.java, rskj-core/src/main/java/org/ethereum/vm/VM.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/org/ethereum/vm/VMTest.java
=> RFS-224 - renamed feature activation for RSKIP activation

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
=> [RFS-203] enable change processing coming from retiring federation

CONTRIBUTING.md, README.md
Added information about how to contact Security Team about vulnerabilities
=> Update README.md with security information

CONTRIBUTING.md, README.md
Added information about how to contact Security Team about vulnerabilities.
This is a revamp of #635
=> Update README.md with security information 

rskj-core/src/main/java/co/rsk/net/discovery/message/FindNodePeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/MessageDecoder.java, rskj-core/src/main/java/co/rsk/net/discovery/message/NeighborsPeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PingPeerMessage.java, rskj-core/src/main/java/co/rsk/net/discovery/message/PongPeerMessage.java, rskj-core/src/test/java/co/rsk/net/discovery/MessageDecoderTest.java, rskj-core/src/test/java/co/rsk/net/discovery/PacketDecoderTest.java
A couple of test for different errors in the message decoder class
=> Msg decoder test

rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/dto/TransactionResultDTOTest.java
Improve compatibility with Web3 standard
=> Add v, r and s EC values to JSON-RPC tx outputs

rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java
Now the collection doesn't have a max size, instead on each second a thread cleans old data stored there.
=> Improved disconnection collection recycling

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/main/java/co/rsk/peg/exception/BlockHeightOlderThanCacheException.java, rskj-core/src/main/java/co/rsk/peg/exception/InvalidBlockHashException.java, rskj-core/src/main/java/co/rsk/peg/exception/InvalidBlockHeightException.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
Update getStoredBlockAtHeight to throw exceptions instead of returning null
=> Use BrdigeUtils.getStoredBlockAtHeight in getBtcTransactionConfirmation

rskj-core/src/main/java/org/ethereum/config/blockchain/HardForkActivationConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/net/DevNetConfig.java, rskj-core/src/main/java/org/ethereum/config/net/MainNetConfig.java, rskj-core/src/main/java/org/ethereum/config/net/RegTestConfig.java, rskj-core/src/main/java/org/ethereum/config/net/TestNetConfig.java, rskj-core/src/test/java/co/rsk/mine/ParameterizedNetworkUpgradeTest.java
Second fork name TBD
- Added networks' individual configuration files
- Added block-based configuration (commented and TBD for testnet and mainnet)
- Added parameter-based configuration for secondFork in devnet and regtest
=> Adding configuration for the "secondFork" network upgrade

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetSecondForkConfig.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
Network upgrade: upon a successful lock operation, log an event.
=> RFS-122 - Bridge lock event log

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
=> Include a info logger with RSK Address.

rskj-core/src/main/java/co/rsk/db/PruneService.java
1. Don't start pruning after RSKIP85
2. Close data sources before renaming and moving their directories
=> Prune changes

rskj-core/src/main/resources/version.properties
This reverts commit e19c78c75d269b67450d919c43d00f66c40825da.
=> 0.5.3 udpated release

rskj-core/src/main/java/co/rsk/DoPrune.java, rskj-core/src/main/java/co/rsk/FullNodeRunner.java, rskj-core/src/main/java/co/rsk/core/RskFactory.java, rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/main/java/org/ethereum/util/BuildInfo.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3ImplRpcTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
=> Allow node to start without build-info.properties information

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
This was detected by @yeousunn at #697, thanks for your colaboration.
Also add tests for setLockWhitelistDisableBlockDelay and some refactoring.
=> Remove unnecessary  check for negative bestChainHeight

rskj-core/src/main/java/co/rsk/rpc/JacksonBasedRpcSerializer.java, rskj-core/src/main/java/co/rsk/rpc/netty/RskJsonRpcHandler.java
A solution to a problem raised in issue #700
=> Websocket bug

rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java, rskj-core/src/test/java/co/rsk/vm/PrecompiledContractAddressTests.java
=> Improved Precompiled Contracts Index performance (25% faster)

rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
eth_gasPrice method is returning wrong results because of Remasc transactions not being discarded. Also, consider block's minimum gasprice for default price (although not very relevant since this is used only until enough txs have been considered).
=> Do not consider remasc txs in gasPriceTracker

build.gradle
The commit is self explanatory
=> A minor fix so gradle versions don't collide on fresh clone

rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java
They had the environment config missing
=> Proper creation of blockchain builder for Remasc tests

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/core/RskFactory.java, rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java, rskj-core/src/main/java/org/ethereum/core/Genesis.java, rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java, rskj-core/src/test/java/co/rsk/db/RepositoryImplOriginalTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/org/ethereum/core/StateTest.java, rskj-core/src/test/java/org/ethereum/core/genesis/BlockchainLoaderTest.java, rskj-core/src/test/java/org/ethereum/db/IndexedBlockStoreTest.java, rskj-core/src/test/java/org/ethereum/util/RskTestFactory.java
Only one genesis block is created on production code
=> Moved genesis and message recorder to RskFactory

rskj-core/src/test/java/co/rsk/helpers/PerformanceTestConstants.java, rskj-core/src/test/java/co/rsk/helpers/Stopwatch.java, rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTest.java, rskj-core/src/test/java/co/rsk/vm/VMPerformanceTest.java, rskj-core/src/test/java/co/rsk/vm/VMSpecificOpcodesPerformanceTest.java, rskj-core/src/test/java/org/ethereum/vm/program/invoke/ProgramInvokeMockImpl.java
This is an improvement over the VM performance tests, with special emphasis in CALL performance. Asserts were added to many performance tests, even if these tests are ignored by default. The tests could be enabled if the unit test running environment is repeatable or they could be run in QA.
=> VM performance Tests Improvements 

rskj-core/src/main/java/co/rsk/mine/BlockToMineBuilder.java, rskj-core/src/main/java/org/ethereum/core/Block.java, rskj-core/src/main/java/org/ethereum/core/BlockHeader.java, rskj-core/src/test/java/co/rsk/core/BlockTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java, rskj-core/src/test/java/co/rsk/vm/MinerHelper.java
> 19 additions and 209 deletions
=> Block and BlockHeader cleanup

rskj-core/src/main/java/co/rsk/pcc/bto/ToBase58Check.java, rskj-core/src/test/java/co/rsk/pcc/bto/BTOUtilsPerformanceTest.java, rskj-core/src/test/java/co/rsk/pcc/bto/DeriveExtendedPublicKeyPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/pcc/bto/ExtractPublicKeyFromExtendedPublicKeyPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/pcc/bto/GetMultisigScriptHashPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/pcc/bto/ToBase58CheckPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTestCase.java, rskj-core/src/test/java/co/rsk/peg/performance/IdentityPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/peg/performance/PrecompiledContractPerformanceTestCase.java
Performance test cases and performance test suite for the new precompiled contract `BTOUtils` are introduced. Actual costs to be calculated and set in a coming PR.
=> RFS-299 - BTOUtils gas estimation

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/metrics/profilers/Metric.java, rskj-core/src/main/java/co/rsk/metrics/profilers/Profiler.java, rskj-core/src/main/java/co/rsk/metrics/profilers/ProfilerFactory.java, rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java, rskj-core/src/main/java/co/rsk/trie/Trie.java, rskj-core/src/main/java/co/rsk/validators/BlockTxsValidationRule.java, rskj-core/src/main/java/org/ethereum/core/Transaction.java, rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java, rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java
Metric classes needed to log metrics in the RSK Node.
This PR consists of the minimum required information core needs to have in order to log metrics and a basic set of hooks used for the most common profiling cases.
=> Node Profiler

rskj-core/src/main/java/org/ethereum/config/blockchain/HardForkActivationConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/net/DevNetConfig.java, rskj-core/src/main/java/org/ethereum/config/net/MainNetConfig.java, rskj-core/src/main/java/org/ethereum/config/net/RegTestConfig.java, rskj-core/src/main/java/org/ethereum/config/net/TestNetConfig.java, rskj-core/src/test/java/co/rsk/mine/ParameterizedNetworkUpgradeTest.java
- Added networks' individual configuration files
- Added block-based configuration (commented and TBD for testnet and mainnet)
- Added parameter-based configuration for secondFork in devnet and regtest
=> Adding configuration for the "secondFork" network upgrade (definitive name TBD)

rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/devnet/DevNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/regtest/RegTestSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetSecondForkConfig.java, rskj-core/src/main/java/org/ethereum/util/ByteUtil.java, rskj-core/src/main/java/org/ethereum/vm/DataWord.java, rskj-core/src/main/java/org/ethereum/vm/OpCode.java, rskj-core/src/main/java/org/ethereum/vm/OpCodes.java, rskj-core/src/main/java/org/ethereum/vm/VM.java, rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java
PR to implement the shift opcodes with its tests
RSKIP: https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP120.md
New PR from RSK repo
=> Shifting op codes

rskj-core/TestGeneration/libethereum/StateTestsFiller/stSystemOperationsTestFiller.json, rskj-core/src/test/java/co/rsk/jsontestsuite/LocalStateTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/GitHubJSONTestSuite.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/AccountValidator.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/BlockHeaderValidator.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/LogsValidator.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/OutputValidator.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/RepositoryValidator.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/validators/ValidationStats.java, rskj-core/src/test/resources/json/StateTests/stSystemOperationsTest.json
This PR adds many of the original Ethereum tests that were temporarily removed. Only a few remain excluded.
=> Hundreds of state tests added again.

rskj-core/src/main/java/co/rsk/pcc/ExecutionEnvironment.java, rskj-core/src/main/java/co/rsk/pcc/NativeContract.java, rskj-core/src/main/java/co/rsk/pcc/NativeContractIllegalArgumentException.java, rskj-core/src/main/java/co/rsk/pcc/NativeMethod.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/test/java/co/rsk/db/BenchmarkedRepository.java, rskj-core/src/test/java/co/rsk/db/RepositoryTrackWithBenchmarking.java, rskj-core/src/test/java/co/rsk/pcc/NativeContractTest.java, rskj-core/src/test/java/co/rsk/pcc/NativeMethodTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/performance/AddSignatureTest.java, rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTestCase.java, rskj-core/src/test/java/co/rsk/peg/performance/CombinedExecutionStats.java, rskj-core/src/test/java/co/rsk/peg/performance/ExecutionStats.java, rskj-core/src/test/java/co/rsk/peg/performance/IdentityPerformanceTest.java, rskj-core/src/test/java/co/rsk/peg/performance/IdentityPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/peg/performance/Mean.java, rskj-core/src/test/java/co/rsk/peg/performance/PrecompiledContractPerformanceTest.java, rskj-core/src/test/java/co/rsk/peg/performance/PrecompiledContractPerformanceTestCase.java, rskj-core/src/test/java/co/rsk/peg/performance/ReceiveHeadersTest.java, rskj-core/src/test/java/co/rsk/peg/performance/RegisterBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/performance/UpdateCollectionsTest.java, rskj-core/src/test/java/co/rsk/vm/VMPerformanceTest.java
Creates PreCompiledContracts package with new framework for native contracts, adding to that refactors the performance tests for gas estimation.
New framework to use as the base for new native contracts.
Basic common behavior for native contracts.  This could be used in future refactors for existing native contracts.
Basic minimum behavior for native contracts' methods. This will avoid the cluttering of code in native contracts.
As part of this work the existing native contracts' performance tests were refactored as well.
This refactor was based off of the existing Bridge performance tests.
Common behavior for native contracts' performance test
Common behavior for native contracts'  specific method performance tests
=> Native contracts framework and performance tests refactor

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/performance/ReceiveHeadersTest.java
Setting the dynamic gas cost of the Bridge::receiveHeaders method based on [these](https://docs.google.com/spreadsheets/d/14mvfComzS0Lj6O6h--B2ENYHKLyvdyMmyNuSWQ4bbqI/edit?usp=sharing) estimations. Also added some additional estimation tests ultimately used to come up with the final formula.
=> RFS-329 - ReceiveHeaders dynamic gas cost

rskj-core/src/main/java/co/rsk/util/ListArrayUtil.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/test/java/co/rsk/util/ListArrayUtilTest.java
Add tests for ListArrayUtil
Improve ListArrayUtil.asByteList documentation
Remove ListArrayUtil.isNotEmpty
=> Add tests for ListArrayUtil and improve documentation

rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java, rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
`GasUnitInDollars` was assigned with the value of another config property.
Correct that by assigning the right config value and add unit test to cover that case.
=> Fix and add unit test coverage

rskj-core/src/main/resources/version.properties
As I understand it, we decided we'd start the snapshot version and resume our work on the `master` branch. This PR sets the project version to `1.1.0-SNAPSHOT`.
We should merge this before midnight UTC, so tomorrow we can merge https://github.com/rsksmart/rskj/pull/894 and set up the QG accordingly.
=> Begin 1.1.0-SNAPSHOT

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/test/java/co/rsk/RskContextTest.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3EthModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
As specified by [EIP-695](http://eips.ethereum.org/EIPS/eip-695)
*fed:revert-bitcoin-check*
=> Create `eth_chainId` method for JSON-RPC

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
=> Make eth_getCode to support pending parameter

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
Added validation to check feePerKb is positive and unit tests for it
=> Fee per kb validation

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/org/ethereum/core/genesis/BlockChainLoader.java, rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainFlusherTest.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java
This is in preparation for the Garbage Collector (#901).
=> Hook up BlockChainFlusher to onBestBlock event

rskj-core/src/main/java/co/rsk/RskContext.java
Now the database directory is cleaned up before the node runner is even built.
=> Fix database reset behavior

rskj-core/src/main/java/co/rsk/net/NodeBlockProcessor.java, rskj-core/src/test/java/co/rsk/net/NodeBlockProcessorTest.java, rskj-core/src/test/java/co/rsk/net/TwoAsyncNodeUsingSyncProcessorTest.java
The commit from @joaquinlpereyra-iov fix issue #1002
=> Limit ProcessBlockHeadersRequest count to chunkSize

rskj-core/src/main/resources/version.properties
*ci: build-release-1.1.0*
*fed: release_1.1.0.0*
*fit: 1.1.0.0-release*
=> End 1.1.0 development cycle

rskj-core/src/main/java/co/rsk/db/MutableTrieCache.java, rskj-core/src/main/java/co/rsk/db/MutableTrieImpl.java, rskj-core/src/main/java/co/rsk/db/RepositorySnapshot.java, rskj-core/src/main/java/co/rsk/trie/MutableTrie.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/db/MutableRepository.java, rskj-core/src/main/java/org/ethereum/vm/GasCost.java, rskj-core/src/main/java/org/ethereum/vm/OpCode.java, rskj-core/src/main/java/org/ethereum/vm/OpCodes.java, rskj-core/src/main/java/org/ethereum/vm/VM.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/main/java/org/ethereum/vm/program/Storage.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/db/MutableTrieCacheTest.java, rskj-core/src/test/java/co/rsk/db/RepositoryTest.java, rskj-core/src/test/java/co/rsk/vm/ExtCodeHashTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/vm/program/invoke/ProgramInvokeMockImpl.java
=> EXTCODEHASH Opcode

rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeLogsParams.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/LogsNotification.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/LogsNotificationEmitter.java, rskj-core/src/main/java/org/ethereum/rpc/AddressesTopicsFilter.java, rskj-core/src/main/java/org/ethereum/rpc/Topic.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeRequestTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/LogsNotificationEmitterTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/subscribe/LogsNotificationTest.java
This implements filtering as seen in
* https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#logs
* https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
=> Add filter support to eth_subscribe log method

CONTRIBUTING.md
This is an improved criteria added for upcoming hackatons. This addition may be removed or improved after the hackaton.
=> Added External PRs General Acceptance Criteria

.circleci/config.yml
Invoke mining-integration-tests CircleCI job
Signed-off-by: Lucas Gabriel Vuotto <lucas@iovlabs.org>
=> Run mining suite as an external testing source

.circleci/config.yml
Signed-off-by: Lucas Gabriel Vuotto <lucas@iovlabs.org>
=> Pass PR number to mining integration tests

.circleci/config.yml
Signed-off-by: Lucas Gabriel Vuotto <lucas@iovlabs.org>
=> Fix SonarQube

rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java
Some tests would trigger an NPE without this fix.
=> fix test runner to avoid NPE

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/main/java/co/rsk/net/messages/MessageVisitor.java, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerUtil.java, rskj-core/src/test/java/co/rsk/net/OneAsyncNodeTest.java, rskj-core/src/test/java/co/rsk/net/TwoAsyncNodeTest.java, rskj-core/src/test/java/co/rsk/net/TwoNodeTest.java, rskj-core/src/test/java/co/rsk/net/messages/MessageVisitorTest.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleAsyncNode.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleNode.java
The block validation is already included in `BlockchainImpl`
Solving #1065
=> Remove block validation from MessageVisitor

.github/workflows/rebase.yml
Adds automatic rebase action to the repo.
Will run by writing /rebase as a comment in any PR
=> Rebase action

rskj-core/src/main/resources/version.properties
=> Move version to 1.2.0 snapshot

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java, rskj-core/src/test/java/co/rsk/RskContextTest.java, rskj-core/src/test/java/org/ethereum/datasource/LevelDbDataSourceTest.java, rskj-core/src/test/java/org/ethereum/util/RskTestContext.java
=> Add support for disabling GC if it was ever enabled

rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
This PR allows concurrent access to DataSourceWithCache. Note that the comitted caché must be synchronized both for reads and writes due to having an LRU LinkedHashMap, which is not thread safe on reads.
*fed:version120* *fit:120*
=> Concurrency

rskj-core/src/main/java/co/rsk/trie/TrieStoreImpl.java
Now trieStore is thread-safe iif the underlying store is thread-safe
*fed:version120* *fit:120*
=> Synchronized savedTries

.circleci/config.yml, rskj-core/build.gradle, rskj-core/src/main/c/keccak/keccak.c, rskj-core/src/main/c/keccak/sph_keccak.h, rskj-core/src/main/c/keccak/sph_types.h, rskj-core/src/main/c/keccak_jni.c, rskj-core/src/main/java/org/ethereum/crypto/HashUtil.java, rskj-core/src/main/java/org/ethereum/crypto/cryptohash/KeccakNative.java, rskj-core/src/test/java/co/rsk/mine/BlockToMineBuilderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/BridgeTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/FederationTest.java, rskj-core/src/test/java/co/rsk/peg/PendingFederationTest.java
Fix: #1038 
Keccak jni using https://github.com/aidansteele/sphlib
=> Native Keccak256 Implementation

rskj-core/src/main/resources/version.properties
*ci: begin_2.0.0*
*fed: begin_2.0.0.0* 
*fit: begin_2.0.0.0*
=> Begin 2.0.0-SNAPSHOT development cycle

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/main/java/co/rsk/peg/BridgeState.java, rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupportFactory.java, rskj-core/src/main/java/co/rsk/peg/ReleaseRequestQueue.java, rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionSet.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/core/CallTransaction.java, rskj-core/src/main/java/org/ethereum/solidity/SolidityType.java, rskj-core/src/main/java/org/ethereum/vm/LogInfo.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/core/CallTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/BridgeTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/ReleaseRequestQueueTest.java, rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionSetTest.java, rskj-core/src/test/java/co/rsk/peg/performance/ReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/performance/UpdateCollectionsTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/solidity/SolidityTypeTest.java
*fit:solidity-integration* *fed:solidity-event-encoding*
=> Solidity event encoding. Events for lock and release request added

rskj-core/src/main/java/co/rsk/core/DifficultyCalculator.java, rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/jsontestsuite/LocalBasicTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/resources/json/BasicTests/difficultyBeforeRSKIP156.json
Difficulty divisor is increased from 50 to 400
=> Difficulty divisor drop

rskj-core/src/main/java/org/ethereum/datasource/DataSourceWithCache.java
Adding concurrent support to internal map
=> Synchronized methods in DataSourceWithCache

rskj-core/src/main/java/org/ethereum/core/Block.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/co/rsk/core/BlockTest.java, rskj-core/src/test/java/co/rsk/test/builders/BlockBuilder.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
Using a new Block factory method that builds a block using only the header
=> Fix eth_getUncle methods

SECURITY.md
Change the bounty program handle name
=> Change the bounty program handle

rskj-core/src/main/java/co/rsk/mine/BlockToMineBuilder.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/core/BlockFactory.java, rskj-core/src/main/java/org/ethereum/core/BlockHeader.java, rskj-core/src/main/java/org/ethereum/core/BlockHeaderBuilder.java, rskj-core/src/main/java/org/ethereum/core/GenesisHeader.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java, rskj-core/src/test/java/co/rsk/core/BlockFactoryTest.java, rskj-core/src/test/java/co/rsk/core/BlockFactoryTest.java.rej, rskj-core/src/test/java/co/rsk/core/BlockHeaderTest.java, rskj-core/src/test/java/co/rsk/core/BlockTest.java, rskj-core/src/test/java/co/rsk/mine/BlockToMineBuilderTest.java, rskj-core/src/test/java/co/rsk/net/messages/MessageTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascTestRunner.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/core/BlockHeaderBuilderTest.java
Introduce consensus changes to pave down the road for future UMM changes.
This PR decouples the UMM changes from https://github.com/rsksmart/rskj/pull/1171
=> UMM Upgrade

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/eth/LightClientHandler.java, rskj-core/src/main/java/co/rsk/net/light/LightClientMessageCodes.java, rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockHeaderMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockHeaderMessage.java, rskj-core/src/main/java/co/rsk/net/rlpx/LCMessageFactory.java, rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java, rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java, rskj-core/src/test/java/co/rsk/net/light/message/BlockHeaderMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/BlockReceiptsMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetBlockHeaderMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetBlockReceiptsMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetTransactionIndexMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/TransactionIndexMessageTest.java, rskj-core/src/test/java/org/ethereum/net/rlpx/MessageCodecTest.java
Added GetBlockHeader and BlockHeader messages.
=> GetBlockHeader and BlockHeader messages

rskj-core/src/main/java/co/rsk/net/eth/LightClientHandler.java, rskj-core/src/main/java/co/rsk/net/light/LightClientMessageCodes.java, rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockBodyMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockBodyMessage.java, rskj-core/src/main/java/co/rsk/net/rlpx/LCMessageFactory.java, rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java, rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java, rskj-core/src/test/java/co/rsk/net/light/message/BlockBodyMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetBlockBodyMessageTest.java
Request::BlockBody {
ID: 4
Inputs:
Loose(H256) // block hash
Outputs:
[Transaction] // txs
[Header] // uncles
}
=> Light client block body message

rskj-core/src/main/java/co/rsk/validators/BlockCompositeRule.java, rskj-core/src/main/java/co/rsk/validators/BlockHeaderCompositeRule.java, rskj-core/src/main/java/co/rsk/validators/BlockHeaderParentCompositeRule.java, rskj-core/src/main/java/co/rsk/validators/BlockParentCompositeRule.java
To have a better block validation performance in logs (related to issue #1067)
=> Adding logs to block validation process

rskj-core/src/main/java/co/rsk/net/eth/LightClientHandler.java, rskj-core/src/main/java/co/rsk/net/light/LightClientMessageCodes.java, rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java, rskj-core/src/main/java/co/rsk/net/light/message/GetStorageMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/StorageMessage.java, rskj-core/src/main/java/co/rsk/net/rlpx/LCMessageFactory.java, rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java, rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetStorageMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/StorageMessageTest.java
// Request for a proof of contract storage.
Request::Storage {
ID: 6
Inputs:
Loose(H256) // block hash
Loose(H256) // address hash
Loose(H256) // storage key hash
Outputs:
[U8](U8) // merkle inclusion proof from storage trie
H256 reusable_as(0) // storage value
}
=> GetStorage and Storage Messages

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/light/LightPeer.java, rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java, rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java, rskj-core/src/main/java/co/rsk/net/light/MessageVisitor.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockHeadersMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockHeadersMessage.java, rskj-core/src/main/java/co/rsk/net/rlpx/LCMessageFactory.java, rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java, rskj-core/src/test/java/co/rsk/net/LightSyncProcessorTest.java, rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java, rskj-core/src/test/java/co/rsk/net/light/message/BlockHeadersMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetBlockHeadersMessageTest.java
=> Changes in blockheader processing

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/light/LightPeer.java, rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java, rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java, rskj-core/src/main/java/co/rsk/net/light/MessageVisitor.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockHeadersMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockHeadersMessage.java, rskj-core/src/main/java/co/rsk/net/rlpx/LCMessageFactory.java, rskj-core/src/test/java/co/rsk/net/LightProcessorTest.java, rskj-core/src/test/java/co/rsk/net/LightSyncProcessorTest.java, rskj-core/src/test/java/co/rsk/net/eth/LightClientHandlerTest.java, rskj-core/src/test/java/co/rsk/net/light/message/BlockHeadersMessageTest.java, rskj-core/src/test/java/co/rsk/net/light/message/GetBlockHeadersMessageTest.java
Added the proof of work rule as verification when Block Header arrives, also instead of storing a list of block header's list a merge between the old list and the new ones is performed
=> Minor changes for block header processing and block header store

rskj-core/src/main/java/co/rsk/net/light/LightStatus.java, rskj-core/src/main/java/co/rsk/net/light/message/AccountsMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockBodyMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockHeaderMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/BlockReceiptsMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/CodeMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetAccountsMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockBodyMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockHeaderMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetBlockReceiptsMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetCodeMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetStorageMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/GetTransactionIndexMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/StatusMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/StorageMessage.java, rskj-core/src/main/java/co/rsk/net/light/message/TransactionIndexMessage.java
Filled all the "toString" methods
=> To string messages

rskj-core/src/main/java/co/rsk/net/light/LightProcessor.java
- Delete     // keep tabs on which nodes know which blocks.	comment
- Change the variable name requestId to id.
=> Light processor fixes

rskj-core/src/main/java/co/rsk/net/light/LightSyncProcessor.java
Refactor of the checking of compatibilty within the protocol
=> Lc lightsync refactor

rskj-core/src/main/java/co/rsk/rpc/Web3DebugModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/debug/DebugModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/debug/DebugModuleImpl.java, rskj-core/src/test/java/co/rsk/rpc/modules/debug/DebugModuleImplTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceModuleImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3Mocks.java
=> Add optional traceOptions param to debug_traceTransaction JSON-RPC api call

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/main/java/co/rsk/peg/utils/BtcTransactionFormatUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
Create method validationsForRegisterBtcTransaction
Add validation methods on BridgeUtils
Add unit tests on BridgeSupportTest and BridgeUtilTest
=> Refactor registerBtcTransaction

rskj-core/src/main/java/co/rsk/Start.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/main/resources/logback.xml, rskj-core/src/test/resources/logback.xml
Added mdc & thread to log output.
Added mdc keys to BlockChainImpl (blockHash & blockHeight)
Added names to various threads
Added logging around BlockChainImpl calls to transactionPool
=> Add thread names & mdc to log

rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java, rskj-core/src/main/java/co/rsk/metrics/profilers/Profiler.java
The change adds additional metric - `BLOCKCHAIN_FLUSH` - for tracking time that's being taken by the`BlockChainFlusher.flushAll()` method.
=> Added BLOCKCHAIN_FLUSH metric

rskj-core/src/main/resources/version.properties
*ci: begin_2.2.0*
*fed: begin_2.2.0.0*
*fit: begin_2.2.0.0*
=> Changing version 2.1.0 to 2.2.0, SNAPSHOT

rskj-core/src/main/java/co/rsk/rpc/netty/JsonRpcWeb3ServerHandler.java, rskj-core/src/main/resources/logback.xml
- Improvement in log level, no need to log so deep.
=> Change log level jsonrpc4j

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
Create RSKIP 176 activation code for Fast Bridge.
=> Create RSKIP 176 code

rskj-core/build.gradle, rskj-core/src/main/java/co/rsk/config/RemascConfigFactory.java, rskj-core/src/test/java/co/rsk/config/RemascConfigFactoryTest.java
Original PR had some trouble with the dependencies and it was importing more than necessary. The aim of this change is to reduce risk and fix all dependency issues related with this.
Import org.web3j:core/utils:4.6.4
Add all missing checksums
EIP712 uses web3j implementation to easily solve all encoding/decoding problems. Originally it was imported the "core" which included many libraries that are not required.
Unit testing and building.
Important note: 'org.bouncycastle:bcprov-jdk15on' was excluded in order to avoid conflicts with our current implementation -> 'org.bouncycastle:bclcrypto-jdk15on'.
=> Refine dependencies for EIP712

rskj-core/build.gradle, rskj-core/src/main/java/co/rsk/peg/BridgeBtcWallet.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/main/java/co/rsk/peg/FastBridgeCompatibleBtcWallet.java, rskj-core/src/main/java/co/rsk/peg/fastbridge/FastBridgeFederationInformation.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/FastBridgeCompatibleBtcWalletTest.java
- Refactor RegisterBtcWallet class
- Refactor BridgeUtils methods involving spendWallet and noSpendWallet as boolean parameter is added to check if wallet is compatible with fast bridge
- Refactored all the tests that made use of these methods and add test for FastBridgeCompatibleBtcWallet class
=> Create FastBridgeCompatibleBtcWallet class in order to support fast BTC feature

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
- Update BridgeMethods and Bridge classes to cast BTC addresses as bytes
- Update tests
=> Update registerBtcTransfer signature

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainFlusher.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloom.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomBuilder.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomProcessor.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomService.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomStore.java, rskj-core/src/main/java/org/ethereum/db/BlockStore.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/logback.xml, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/core/bc/BlockChainFlusherTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomBuilderTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomProcessorTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomServiceTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomStoreTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomTest.java, rskj-core/src/test/java/org/ethereum/db/BlockStoreDummy.java, rskj-core/src/test/resources/logback.xml
Using a new configuration option, the build and save of block blooms data could be executed within the normal operation of the node. This data is used to retrieve log information efficiently.
Usually, this block blooms information is used only in nodes that has JSON RPC open, and log query operation enabled. And with the first query, the data is build and saved. But even with this feature, the operation could take many minutes and resources from the node.
So, this new code allow the build of the same data along the blockchain node normal processing, ie, during long synchronization or normal synchronization. To do this, a new internal service was added, and it is activated by configuration (the default value is not activated),
It has code tests, and also was tested running a long sync …
=> Build Block Blooms Database

rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
A mocked `ReversibleTransactionExecutor` was removed from `Web3ImplTest`, being replaced by a concrete instance.
The motivation is to improve those tests. Before this change, many test could run in green, even without running all the preconditions.
Now, writing `eth_call` with real contracts is feasible. Before this change, you could call `eth_call` with wrong data, and the result was OK.
Some tests were rewritten, to use a real `Greeter` contract. Previous tests used the runtime bytes to deploy the contract, instead of the full bytecode.
Gas provided was also wrong, it was not enough for some tests.
I recommend to review `TestContract.greeter` because its use in other tests could also be polluted by mocks, that give a false sense of security
=> Removing mocked transaction executor from Web3ImplTest

rskj-core/src/main/java/co/rsk/core/TransactionExecutorFactory.java, rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/core/TransactionExecutorTest.java
Remove configuration option `vm.play`
The only current use is with its value in true.
Reruning tests
=> Remove vm.play option and usage

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/core/bc/BlockHeaderValidatorImpl.java, rskj-core/src/main/java/co/rsk/core/bc/BlockValidatorImpl.java, rskj-core/src/main/java/co/rsk/net/BlockSyncService.java, rskj-core/src/test/java/co/rsk/net/simples/SimpleAsyncNode.java, rskj-core/src/test/java/co/rsk/test/World.java
This adds some optimizations to block processing
*fit: 2.2-rc*
=> [PAPYRUS-2.2.0-rc] Block processing optimizations

rskj-core/build.gradle
=> Remove tests classes from build.gradle

rskj-core/src/main/resources/version.properties
This changes version modifier from `SNAPSHOT` to `PAPYRUS`
*fed: PAPYRUS-2.2.0.0*
*fit: 2.2-rc*
=> Created release version 2.2.0-PAPYRUS

rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
- Update constant maxDepthBlockchainAccepted to 25
- Fix unit test
=> Fixes on receiveHeader

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/RejectedPeginReason.java, rskj-core/src/main/java/co/rsk/peg/utils/UnrefundablePeginReason.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
This adds changes to the Bridge peg-in protocol in order to register evidence on-chain when a peg-in was rejected and why it happened.
These changes will improve the user experience of the peg-in.
*fit:add-pegin-rejection-events*
=> Added Peg-in rejection events

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/RejectedPegoutReason.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/solidity/SolidityType.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
Implementation of:
https://github.com/rsksmart/RSKIPs/blob/release-refund/IPs/RSKIP185.md
Unit testing only.
*fit:add-release-events-tests*
=> RSKIP-185: Peg-out refund and new events 

rskj-core/src/main/java/org/ethereum/vm/program/InternalTransaction.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/main/java/org/ethereum/vm/program/ProgramResult.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/org/ethereum/vm/program/ProgramResultTest.java, rskj-core/src/test/java/org/ethereum/vm/program/ProgramTest.java
This field is only to be used in memory, doesn't change the encoded internal Transaction.
- originHash: will be the tx hash of the first transaction that initiated a chain of internal transactions.
Add log support for precompiled contracts when executing internal transaction
Allow execution internal transactions in precompiled contracts
Unit tests provided
=> Program changes

rskj-core/src/main/resources/reference.conf
Quick fix, quotes by double quotes in config file.
Didn't work on Ubuntu.
Unit testing.
=> fix native configs

rskj-core/src/main/java/org/ethereum/vm/trace/Op.java
Removing LGTM unused container warning in **OP** class
As described in LGTM [documentation](https://lgtm.com/rules/890083/): "If the contents of a collection or map are never accessed in any way, then it is useless and the code that updates it is effectively dead code. Often, such objects are left over from an incomplete refactoring, or they indicate an underlying logic error."
But in this case, this properties are being serialized on JSON RPC requests... Since this is the case, this warning can be seen as a false positive for us... so we are removing them.
In a future we could refactor the OP class and start serializing through the use of getters instead of fields, but it requires time and testing for it to go well.
=> Removing unused container warning

README.md
Adding LGTM Java code quality grade tag
LGTM code quality grade is an important indicator, it "provides useful insights and code quality information for all sorts of people participating in software development". More [info here](https://lgtm.com/help/lgtm/getting-started).
Tests not required
=> Adding LGTM shield tag

rskj-core/src/main/resources/version.properties
This change bumps version of rskj to `3.0.0`
=> Bumped version to 3.0.0

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/ErpFederation.java, rskj-core/src/main/java/co/rsk/peg/FastBridgeCompatibleBtcWallet.java, rskj-core/src/main/java/co/rsk/peg/Federation.java, rskj-core/src/main/java/co/rsk/peg/PendingFederation.java, rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionBuilder.java, rskj-core/src/main/java/co/rsk/peg/utils/EcKeyUtils.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/peg/ErpFederationTest.java, rskj-core/src/test/java/co/rsk/peg/FastBridgeCompatibleBtcWalletWithSingleScriptTest.java, rskj-core/src/test/java/co/rsk/peg/FastBridgeCompatibleBtcWalletWithStorageTest.java, rskj-core/src/test/java/co/rsk/peg/FederationTest.java, rskj-core/src/test/java/co/rsk/peg/PendingFederationTest.java, rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java, rskj-core/src/test/java/co/rsk/peg/utils/EcKeyUtilsTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
- Update FastBridgeCompatibleBtcWallet to support ERP Federation
- Add unit tests
=> Update fast bridge compatible wallet

rskj-core/src/main/java/co/rsk/cli/tools/RewindBlocks.java, rskj-core/src/main/java/org/ethereum/db/BlockStore.java, rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java, rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java, rskj-core/src/test/java/org/ethereum/db/BlockStoreDummy.java
Sometimes, a RSK node have processed blocks that are corrupted or invalid, after a hard fork. To remove such blocks and start from a previous one state, this tool removes the blocks with number higher than X (a parameter).
Example:
```
java -cp <rsk.jar> co.rsk.cli.tools.RewindBlocks 1000000 --testnet
```
It removes the blocks with number 1000001 or higher
It was tested manually, and also with code tests.
- [X ] New feature (non-breaking change which adds functionality)
=> Rewind Blocks CLI Tool

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
*fit:add-receive-header-tests*
=> Receive headers limits integration

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
=> Consider case when hash has a leading 0 when deserializing

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/vm/OpCode.java, rskj-core/src/main/java/org/ethereum/vm/OpCodes.java, rskj-core/src/main/java/org/ethereum/vm/VM.java, rskj-core/src/main/java/org/ethereum/vm/program/Program.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/vm/VMExecutionTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
This PR removes three opcodes:
- BEGINSUB
- RETURNSUB
- JUMPSUB
NOTE: I've created a [backup branch](https://github.com/rsksmart/rskj/tree/subroutines-backup), so if we want to addd them we can just rebase the branch.
Previously, we [added](https://github.com/rsksmart/rskj/pull/1302/files) three opcodes in order to maintain EVM compatibility. Since they are not included anymore in Berlin hardfork, we've decided to remove them.
Run the entire test-suite
=> Subroutines removal

rskj-core/src/main/java/co/rsk/config/RemascConfig.java, rskj-core/src/main/java/co/rsk/remasc/Remasc.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/main/resources/remasc.json, rskj-core/src/test/java/co/rsk/remasc/RemascRskAddressActivationTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
Implementing [RSKIP218](https://github.com/rsksmart/RSKIPs/pull/218): New fee rewards address for the RSK Core Developers Fund
Filling the missing gaps from this [old PR](https://github.com/rsksmart/rskj/pull/1317)
Run the entire test suite, and also added a unit test for REMASC.
=> [RSKIP218] - New fee rewards address for the RSK Core Developers Fund

rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java
Updated minSecondsBetweenCallsReceiveHeader constants from 10 to 5 minutes (In Seconds)
=> Updated receive header constants

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/BridgeTestPowerMock.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
*fed:fb-burning-utxos-fix*
*fit:update-minimum-peg-out*
=> Minimum peg in rskj

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/org/ethereum/solidity/SolidityType.java
- Refactored Solidity Type Constants
- Refactored Fields Constants
=> Refactored Bridge events fields

rskj-core/build.gradle
This change removes `stripJar` gradle task. Also it includes refactoring of dependency references.
Files with the names like `LICENSE/LICENSE.*`, `NOTICE/NOTICE.*` in the `META-INF/` folder are renamed to include a lib’s name as prefix just to prevent their clashing
=> Get rid of stripJar task

rskj-core/src/main/java/org/ethereum/config/SystemProperties.java
Adding explicit array to string conversion
As described in LGTM [documentation](https://lgtm.com/rules/7860080/): "When converting an array to a readable string, use Arrays.toString for one-dimensional arrays, or Arrays.deepToString for multi-dimensional arrays. These functions iterate over the contents of the array and produce human-readable output."
=> Fixing implicit array to string conversion

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/FederationTestUtils.java
Remove useless null check already covered by "equals null" check.
As described in LGTM [documentation](https://lgtm.com/rules/1883950275/): "Sometimes you can guarantee that a particular variable will never be null. For example when that variable has just been assigned a newly created object or is the exception caught by a catch clause. A null check on such a variable is misleading, and can potentially indicate a logic error."
Using Unit Test
=> Fixing useless null check

rskj-core/src/main/java/org/ethereum/rpc/PendingTransactionFilter.java
=> fix sonar quality gate, useless import

rskj-core/src/main/java/co/rsk/core/bc/MiningMainchainViewImpl.java, rskj-core/src/main/java/co/rsk/rpc/modules/txpool/TxPoolModuleImpl.java, rskj-core/src/main/java/org/ethereum/net/p2p/P2pHandler.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/txpool/TxPoolModuleImplTest.java, rskj-core/src/test/java/org/ethereum/net/p2p/P2pHandlerTest.java
Updating log messages to use parameters as expected.
As described in LGTM [documentation](https://lgtm.com/rules/1930000368/): "When formatting strings using printf-style format strings, one must ensure that the number of supplied arguments matches the number of arguments referenced by the format string. Additional arguments will be thrown away silently, which may not be the intended behavior, and too few arguments will cause an IllegalFormatException."
=> Fixing parameters on log messages

rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
Missing 
- btcHeightWhenBlockIndexActivates (BTC height when Iris activates in RSK)
*fed:3.0.0.0*
*fit:fix-flyove-test*
*ci:iris-update*
=> Iris constants definition

rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
*fed:3.0.0.0*
*fit:fix-flyove-test*
*ci:iris-update*
=> Check a tx input does not have script op codes before checking the script

rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingBodiesSyncState.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/util/CacheElement.java, rskj-core/src/test/java/co/rsk/util/CacheElementTest.java
- Changing variable types from Boxed to primitive
- Added a new test class "CacheElementTest" to test that the behavior of the method "hasExpired" remains unchanged.
As described in LGTM [documentation](https://lgtm.com/rules/1813633265/): "If a variable is never assigned null it should use the primitive type, as this both directly shows the impossibility of null and also avoids unnecessary boxing and unboxing conversions."
=> Changing boxed for primitive types

rskj-core/src/main/resources/reference.conf
Increase cache size
Mr. Angel Lopez recommended this value to be upgraded to improve node execution times, a few tests where made to confirm that.
Profiling Tool
=> Update cache size

rskj-core/src/main/resources/version.properties
*fed:rskj-dependency-update*
*ci:rskj-version-update*
=> Update version number to 3.1.0

rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransaction.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionDisabled.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionInstant.java, rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletDisabled.java, rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java, rskj-core/src/main/java/org/ethereum/rpc/BlockInformationResult.java, rskj-core/src/main/java/org/ethereum/rpc/CallArguments.java, rskj-core/src/main/java/org/ethereum/rpc/FilterRequest.java, rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java, rskj-core/src/main/java/org/ethereum/rpc/SyncingResult.java, rskj-core/src/main/java/org/ethereum/rpc/Web3.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/main/java/org/ethereum/rpc/converters/CallArgumentsToByteArray.java, rskj-core/src/main/java/org/ethereum/util/TransactionArgumentsUtil.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3RskImplTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleDLSTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/converters/CallArgumentsToByteArrayTest.java, rskj-core/src/test/java/org/ethereum/util/TransactionArgumentsUtilTest.java, rskj-core/src/test/java/org/ethereum/util/TransactionTestHelper.java, rskj-core/src/test/java/org/ethereum/vm/program/NestedContractsTest.java
Completing [this other PR](https://github.com/rsksmart/rskj/pull/1571) and finally fixing this one https://github.com/rsksmart/rskj/issues/1572
=> Adding accesors

rskj-core/src/main/java/co/rsk/remasc/RemascTransaction.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionDisabled.java
Adding missing **synchronized** modifier to overridden method.
As described in LGTM [documentation](https://lgtm.com/rules/5990064/): "If a synchronized method is overridden in a subclass, the compiler does not require the overriding method to be synchronized. However, if the overriding method is not synchronized, the thread-safety of the subclass may be broken."
=> Fixing non-synchronized override

rskj-core/src/main/java/co/rsk/config/ConfigLoader.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java
Fix the properties name used by code
Originated from https://github.com/rsksmart/rskj/pull/1535
Fix issue #1533
=> Fix system properties name

rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/org/ethereum/db/ReceiptStore.java, rskj-core/src/main/java/org/ethereum/db/ReceiptStoreImpl.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorBuilder.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorTest.java, rskj-core/src/test/java/co/rsk/test/DslFilesTest.java, rskj-core/src/test/java/co/rsk/test/World.java, rskj-core/src/test/java/org/ethereum/db/ReceiptStoreImplTest.java
This fixes #1600 when appropriate values in responses from the `eth_getLogs` and `eth_getTransactionReceipt` JSON-RPC endpoints sometimes do not match.
=> Iris getlogs fix

rskj-core/src/main/java/co/rsk/net/AsyncNodeBlockProcessor.java
This PR adds extra logging in async block processor
To make logs more informative
=> Added extra logging in async block processor

rskj-core/src/main/java/co/rsk/trie/NodeReference.java, rskj-core/src/main/java/co/rsk/trie/Trie.java
closes https://github.com/rsksmart/rskj/issues/1550
=> Fix sub-optimal retrieval

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/NodeID.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoringManager.java, rskj-core/src/main/java/org/ethereum/config/SystemProperties.java, rskj-core/src/main/java/org/ethereum/net/server/EthereumChannelInitializer.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/NodeChallengeManagerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/UDPServerTest.java, rskj-core/src/test/java/co/rsk/scoring/PeerScoringManagerTest.java, rskj-core/src/test/java/org/ethereum/net/server/EthereumChannelInitializerTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java
This allows to specify banned peers / miners in configs.
=> Blocked peers

rskj-core/src/main/java/co/rsk/db/importer/BootstrapImporter.java, rskj-core/src/main/java/co/rsk/trie/Trie.java
This change reduces amount of RAM required for the `--import sync` feature.
The idea is to release memory that's not needed anymore during the importing process as soon as possible. The idea also is to use `LinkedList`'s instead of `ArrayList`'s during the process to free already processed items (cause some lists may hold millions of entries).
Right now, while starting the node with the `--import` flag, it crashes with OoM error. Java option `-Xmx8g` can be used to mitigate this issue a bit (this simply increases available ram for a java process to 8GBs).
With the change in this PR, min required RAM can be decreased to 4GBs, so the node can import data with the help of the `-Xmx4g` flag.
By running the node via the following commands:
- `java -Xmx4g -jar …
=> Memory management improvements in import sync

rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java, rskj-core/src/main/java/co/rsk/cli/tools/ConnectBlocks.java, rskj-core/src/main/java/co/rsk/cli/tools/ExecuteBlocks.java, rskj-core/src/main/java/co/rsk/cli/tools/ExportBlocks.java, rskj-core/src/main/java/co/rsk/cli/tools/ExportState.java, rskj-core/src/main/java/co/rsk/cli/tools/ImportBlocks.java, rskj-core/src/main/java/co/rsk/cli/tools/ImportState.java, rskj-core/src/main/java/co/rsk/cli/tools/RewindBlocks.java, rskj-core/src/main/java/co/rsk/cli/tools/ShowStateInfo.java, rskj-core/src/main/java/co/rsk/util/Factory.java, rskj-core/src/main/resources/logback.xml, rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
This improves logging for cli tools (a.k.a developer tools), which should be distinguished from the `RskJ` node and mostly are intended for development purposes.
This also adds a capability to specify a log level in command line (via JVM args) for the `logs/rsk.log` file (the primary logs output), stdout (console output) and separately for stdout of the cli tools. For instance, in the command bellow the log level for the file is `DEBUG`(`-Dlogging=DEBUG`), for `stdout` - `ERROR`(`-Dlogging.stdout=ERROR`), and for `stdout.clitools` - `INFO`(`-Dlogging.stdout.clitools=INFO`):
```bash
java -Dlogging=DEBUG -Dlogging.stdout=ERROR -Dlogging.stdout.clitools=INFO -cp ./rskj-core-3.1.0-SNAPSHOT-all.jar co.rsk.cli.tools.RewindBlocks 1000000 --testnet
```
If not specified, the following are default …
=> Improved logging for cli tools

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java, rskj-core/src/main/java/org/ethereum/util/TransactionArgumentsUtil.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java
Generic exception is thrown on invalid sender address.
While executing a simple `tRBTC` transfer transaction from a `web3js app` a `NPE` is thrown, instead of a clear message to the user informing of the problem.
If the node does not find the sender address, a `NPE` will be thrown, so a fix is needed to clearly inform the users of what really happened.
Unit Tests
QA
N/A
=> SendTransaction Fix

rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java
=> Fixed resending

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/MiningConfig.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java, rskj-core/src/main/java/co/rsk/mine/SubmissionRateLimitHandler.java, rskj-core/src/main/resources/config/testnet.conf, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/config/ConfigUtils.java, rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java, rskj-core/src/test/java/co/rsk/mine/SubmissionRateLimitHandlerTest.java
This change introduces rate limit for miner submissions. By default, it's only enabled for `testnet`
=> Miner rate limit

rskj-core/src/main/java/co/rsk/util/HexUtils.java, rskj-core/src/main/java/org/ethereum/rpc/TypeConverter.java, rskj-core/src/main/java/org/ethereum/rpc/Web3.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/test/java/co/rsk/util/HexUtilsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
Improve compatibility with accepting only hexa encoded inputs for the sha3 hash
https://github.com/rsksmart/rskj/issues/1607
compatibility with web3.js
unit tests
=> Web3 sha3 handling input

rskj-core/src/main/java/co/rsk/core/DifficultyCalculator.java, rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/main/java/org/ethereum/config/SystemProperties.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/NetworkUpgrade.java, rskj-core/src/main/resources/config/devnet.conf, rskj-core/src/main/resources/config/main.conf, rskj-core/src/main/resources/config/regtest.conf, rskj-core/src/main/resources/config/testnet.conf, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/RskContextTest.java, rskj-core/src/test/java/co/rsk/jsontestsuite/LocalBasicTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/resources/json/BasicTests/difficulty1.json
=> Changed difficulty min value for testnet (r3.2.0)

rskj-core/src/main/resources/version.properties
*ci:3.3.0*
*fit:3.3.0*
*fed:version-bump*
=> Update version to 3.3.0-SANPSHOT

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java, rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceModuleImpl.java, rskj-core/src/main/java/org/ethereum/core/Transaction.java, rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
Just some code formatting before opening the actual PR to ease review
=> Code formatting

rskj-core/src/main/java/co/rsk/rpc/modules/debug/DebugModuleImpl.java, rskj-core/src/main/java/co/rsk/rpc/modules/debug/DisableOption.java, rskj-core/src/main/java/co/rsk/rpc/modules/debug/TraceOptions.java, rskj-core/src/main/java/org/ethereum/crypto/signature/Secp256k1ServiceBC.java, rskj-core/src/main/java/org/ethereum/crypto/signature/Secp256k1ServiceNative.java, rskj-core/src/main/java/org/ethereum/vm/trace/Op.java, rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTraceProcessor.java, rskj-core/src/main/resources/version.properties, rskj-core/src/test/java/co/rsk/rpc/modules/debug/DebugModuleImplTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/debug/TraceOptionsTest.java, rskj-core/src/test/java/org/ethereum/crypto/signature/Secp256k1ServiceTest.java
=> Merge Iris330 into master

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionBuilderTest.java
- [Fixed Infinite Loop When Max Transaction Size is Exceeded](https://github.com/rsksmart/rskj/commit/7d076a8d92271ae58684f3c38d1716395490ee2b)
=> Security review

rskj-core/src/main/java/co/rsk/net/eth/RskWireProtocol.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoring.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoringInformation.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoringManager.java, rskj-core/src/main/java/co/rsk/scoring/ScoringCalculator.java, rskj-core/src/test/java/co/rsk/scoring/PeerScoringManagerTest.java, rskj-core/src/test/java/co/rsk/scoring/PeerScoringTest.java, rskj-core/src/test/java/co/rsk/scoring/ScoringCalculatorTest.java
Node was not forgiven after Peer Scoring punishment under certain circumstances
Fix node forgiveness by correctly handling order of operations
Node was not forgiven after Peer Scoring punishment under certain circumstances
- manual testing
- RSKj unit testing
=> Forgive punishment fix

rskj-core/src/main/java/co/rsk/scoring/PeerScoringManager.java, rskj-core/src/main/java/org/ethereum/rpc/Web3.java, rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/scoring/PeerScoringManagerTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java
Added RPC method to clear peer scoring by `nodeId` or `inetAddress`
Added RPC method to clear peer scoring by `nodeId` or `inetAddress`
=> Added RPC method to clear Peer Scoring (by nodeId or address)

rskj-core/src/main/java/co/rsk/net/SyncProcessor.java, rskj-core/src/main/java/co/rsk/net/sync/CheckingBestHeaderSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/ChunkDescriptor.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingBackwardsBodiesSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingBackwardsHeadersSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingBodiesSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingHeadersSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingSkeletonSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/FindingConnectionPointSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/PeersInformation.java, rskj-core/src/main/java/co/rsk/net/sync/SyncEventsHandler.java, rskj-core/src/test/java/co/rsk/net/sync/CheckingBestHeaderSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/DownloadingBackwardsBodiesSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/DownloadingBackwardsHeadersSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/DownloadingBodiesSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/DownloadingSkeletonSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/FindingConnectionPointSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/SimpleSyncEventsHandler.java
Record bad messages by `inetAddress` for those message types that were missing and just recording by `nodeId`
Unit testing and manual testing
=> Register missing bad events by address

rskj-core/src/main/resources/version.properties
=> Bumped version to 4.1.0

rskj-core/src/main/resources/config/devnet.conf, rskj-core/src/main/resources/config/regtest.conf
This fixes umm activation height for `devnet` and `regtest`
See #1525
=> Fix UMM activation height for devnet and regtest

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTest.java, rskj-core/src/test/java/co/rsk/peg/performance/PowpegRedeemScriptTest.java
Add performance test for getPowpegRedeemScript method
=> Powpeg redeemscript perfomance tests

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java, rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorBuilder.java, rskj-core/src/test/java/co/rsk/validators/BlockTimeStampValidationRuleTest.java, rskj-core/src/test/java/org/ethereum/config/ConstantsTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
This change increases (for `testnet` only) max allowed timestamp difference between btc merged mining and rsk headers
*ci: rskj-400-rc-ver*
=> Increased max timestamp diff for testnet

rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java
Increase accountSlots config to 16, same value as Ethereum
Increase accountSlots config to 16, same value as Ethereum
*ci: rskj-400-rc-ver*
=> Increased accountSlots config

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java, rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/config/RskSystemPropertiesTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockValidatorBuilder.java, rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java, rskj-core/src/test/java/co/rsk/validators/BlockTimeStampValidationRuleTest.java, rskj-core/src/test/java/org/ethereum/config/ConstantsTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
#1763, #1754 and #1757 -> master
=> Merge PRs #1763, #1754 and #1757 into master

rskj-core/src/main/java/co/rsk/scoring/PeerScoringInformation.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoringManager.java
=> Fixed log when punishing a node by address

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/ReleaseRequestQueue.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java, rskj-core/src/test/java/co/rsk/peg/ReleaseRequestQueueTest.java
- Implement equals and hash method for ReleaseRequestQueue class.
- Add tests for ReleaseRequestQueue equals method
- Add new tests to ensure release request queue structure
*fed:HOP-4.0.0-rc*
*ci:hop-rc*
*fit:enable-flyover-fixes*
=> Fix pegout batching

rskj-core/src/main/java/co/rsk/core/TransactionListExecutor.java, rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/db/MutableTrieCache.java, rskj-core/src/main/java/org/ethereum/vm/trace/ProgramTraceProcessor.java, rskj-core/src/test/java/co/rsk/blockchain/utils/BlockGenerator.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java
Adds a function to execute transactions in parallel based on the edges defined in the block header.
=> Added parallel transaction execution

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
Add useful logs on funds migration methods
=> Add useful logs on funds migration methods

rskj-core/src/test/java/co/rsk/peg/performance/BridgePerformanceTest.java, rskj-core/src/test/java/co/rsk/peg/performance/PegoutBatchingBridgeMethodsTest.java, rskj-core/src/test/java/co/rsk/peg/performance/RegisterFastBridgeBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/performance/UpdateCollectionsTest.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java
Implemented Performance Test Cases For Pegout Batching Methods; getQueuedPegoutsCount, getNextPegoutCreationBlockNumber, getEstimatedFeesForNextPegOutEvent
=> Implemented Performance Test Cases For Pegout Batching Methods

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
- Improve logs of flyover pegin rejection
- Rearrange some conditions and logs on `processFundsMigration` method to improve the trace of logs.
=> Improve logs for flyover pegin rejection and funds migration

rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java
Set gas price for hop new bridge methods
=> Set gas price for hop new bridge methods

rskj-core/src/main/java/co/rsk/core/bc/BlockChainStatus.java, rskj-core/src/main/java/co/rsk/net/SyncProcessor.java, rskj-core/src/main/java/co/rsk/net/sync/DecidingSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/DownloadingSkeletonSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/PeersInformation.java, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java, rskj-core/src/test/java/co/rsk/net/SyncProcessorTest.java, rskj-core/src/test/java/co/rsk/net/sync/DecidingSyncStateTest.java
… not possible
Allow a peer with same tip to be selected for backward syncing and small refactor on related codebase.
=> Allow a peer with same tip to be selected for backward syncing

rskj-core/src/main/java/co/rsk/net/MessageCounter.java, rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
Fixed race condition that caused decrement() to be called before increment() on MessageCounter
=> Fixed race condition on MessageCounter

rskj-core/src/main/java/co/rsk/net/handler/quota/TxQuota.java, rskj-core/src/main/java/co/rsk/net/handler/quota/TxQuotaChecker.java, rskj-core/src/main/java/co/rsk/net/handler/quota/TxVirtualGasCalculator.java, rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java, rskj-core/src/test/java/co/rsk/net/handler/quota/TxQuotaCheckerIntegrationTest.java, rskj-core/src/test/java/co/rsk/net/handler/quota/TxQuotaTest.java, rskj-core/src/test/java/co/rsk/net/handler/quota/TxVirtualGasCalculatorTest.java, rskj-core/src/test/java/org/ethereum/listener/GasPriceTrackerTest.java
Improvements:
- Improved rejected tx logging
- Take into account market status in order to activate `gasPrice` factor: blocks should have at least a 90% completion for market to be considered active
- Allow propagation of the first transaction of an account regardless consumed gas, otherwise its propagation could take very long, or not occur at all, depending on some conditions: if the tx consumes more than the initial granted Virtual Gas, it will be rejected, therefore not being propagated. It would only be propagated if it is re-tried again when enough was was accumulated. But the nodes receiving it after this broadcast would behave in the same way the previous node initially did, causing a delay or a break in the broadcasting. This problem affects only to first transaction, as for the …
=> Account tx rate limit algorithm iter 2

rskj-core/src/main/java/co/rsk/scoring/PeerScoring.java, rskj-core/src/main/java/co/rsk/scoring/PeerScoringManager.java, rskj-core/src/test/java/co/rsk/scoring/PeerScoringTest.java
Just log when actually punished
=> Fixed misleading PeerScoring log

rskj-core/src/main/resources/version.properties
=> Bumped version to 4.2.0

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/rpc/netty/JsonRpcWeb3FilterHandler.java, rskj-core/src/main/resources/config/main.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/rpc/netty/Web3HttpServerTest.java
Allow wildcard to hosts config in order to accept all hosts
Skipping host check coming from headers when wildcard is found in the host list.
Context: https://github.com/rsksmart/rskj/issues/1439
=> Allow wildcard to hosts config in order to accept all hosts

rskj-core/src/main/resources/expected.conf
This adds missing "expected" configs in `expected.conf`.
*ci:rskj-400-rc-ver*
=> Added missing expected configs

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
This pr includes the changes of pr: https://github.com/rsksmart/rskj/pull/1827
=> Use new event logging method

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/mine/MinerServer.java, rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java, rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceModuleImpl.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/config/ConfigUtils.java, rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java
include more transactions in the block pre-mine
https://github.com/rsksmart/rskj/issues/1150
unit tests and JSON-RPC
=> Minerserver tx per block

rskj-core/src/main/java/co/rsk/rpc/netty/Web3ResultHttpResponseHandler.java, rskj-core/src/test/java/co/rsk/rpc/netty/Web3HttpServerTest.java
=> HOP-4.1.0-rc -> master merge

rskj-core/src/main/resources/version.properties
*fed:HOP-4.1.0-rc*
*fit:HOP-4.1.0-rc*
*ci:rskj-410-ver*
=> Changed version modifier from rc to hop

rskj-core/src/main/java/co/rsk/RskContext.java
Update method visibility in order to make the node compatible with [benchmarking tool](https://github.com/rootstock/rskj-benchmarking-tool/pull/38).
Benchmarking tool must work for last release
Unit Tests
=> Benchmarking Tool compatibility changes

rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
Added warning messages in a javadoc of `getBlockHashByNumber()` and `getBlockAtDepthStartingAt()`
=> Added warning messages in IndexedBlockStore

rskj-core/src/main/java/org/ethereum/config/SystemProperties.java, rskj-core/src/main/resources/reference.conf
=> Added fallback dummy IP to Public IP discovery service

rskj-core/src/main/java/co/rsk/config/ConfigLoader.java, rskj-core/src/main/resources/expected.conf
Log WARN instead of ERROR in case of unexpected configs & fill up reference.conf with missing configs
=> Syncing expected.conf

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java
Adds new pegout_confirmed definition
=> Adds new pegout_confirmed definition

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java
This pr includes the changes of https://github.com/rsksmart/rskj/pull/1882
=> Rskip326 emit pegout confirmed event

rskj-core/src/main/resources/version.properties
=> Bumped rskj version to 4.3.0

rskj-core/src/main/java/co/rsk/peg/ErpFederation.java, rskj-core/src/main/java/co/rsk/peg/P2shErpFederation.java, rskj-core/src/test/java/co/rsk/peg/P2shErpFederationTest.java
=> Fix P2shErpFederation standard redeemscript fetching

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java, rskj-core/src/main/java/co/rsk/mine/BlockToMineBuilder.java, rskj-core/src/main/java/co/rsk/rpc/ExecutionBlockRetriever.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceModuleImpl.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/ExecutionFoundBlockRetrieverTest.java, rskj-core/src/test/java/co/rsk/rpc/Web3InformationRetrieverTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleTest.java, rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceModuleImplTest.java, rskj-core/src/test/java/co/rsk/test/World.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplScoringTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/util/EthModuleTestUtils.java, rskj-core/src/test/java/org/ethereum/vm/program/NestedContractsTest.java
=> 4.2.0-rc -> master merge

rskj-core/src/main/java/co/rsk/net/handler/quota/TxQuota.java
Updated Virtual Gas first transaction acceptance to ease monitoring rule set up
=> Updated log for forced virtual gas subtraction

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java, rskj-core/src/main/java/org/ethereum/db/MutableRepository.java, rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java
=> Experiment metrics boton collisions

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/Start.java, rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java, rskj-core/src/main/java/co/rsk/cli/tools/IndexBlooms.java, rskj-core/src/main/java/co/rsk/cli/tools/StartBootstrap.java, rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java, rskj-core/src/main/java/org/ethereum/db/MutableRepository.java, rskj-core/src/test/java/co/rsk/RskContextTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java, rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/net/SyncProcessorTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascTestRunner.java, rskj-core/src/test/java/co/rsk/test/World.java, rskj-core/src/test/java/co/rsk/test/builders/BlockBuilder.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/co/rsk/test/dsl/WorldDslProcessor.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java, rskj-core/src/test/java/org/ethereum/util/RskTestContext.java
=> Experiment metrics boton

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/Start.java, rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java, rskj-core/src/main/java/co/rsk/cli/tools/IndexBlooms.java, rskj-core/src/main/java/co/rsk/cli/tools/StartBootstrap.java, rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java, rskj-core/src/main/java/co/rsk/core/bc/ReadWrittenKeysTracker.java, rskj-core/src/main/java/org/ethereum/db/MutableRepository.java, rskj-core/src/test/java/co/rsk/RskContextTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java, rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/net/SyncProcessorTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascProcessMinerFeesTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascStorageProviderTest.java, rskj-core/src/test/java/co/rsk/remasc/RemascTestRunner.java, rskj-core/src/test/java/co/rsk/test/World.java, rskj-core/src/test/java/co/rsk/test/builders/BlockBuilder.java, rskj-core/src/test/java/co/rsk/test/builders/BlockChainBuilder.java, rskj-core/src/test/java/co/rsk/test/dsl/WorldDslProcessor.java, rskj-core/src/test/java/org/ethereum/core/ImportLightTest.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/TestRunner.java, rskj-core/src/test/java/org/ethereum/jsontestsuite/runners/StateTestRunner.java, rskj-core/src/test/java/org/ethereum/util/RskTestContext.java
=> Experiment metrics

rskj-core/src/main/resources/config/devnet.conf, rskj-core/src/main/resources/config/regtest.conf
TestSystemProperties is using config/regtest as base config. 
This rolls back the value changed in https://github.com/rsksmart/rskj/commit/f91b455e66125dec5e880ef964bab9fa4046afb6
Run tests locally
=> Activate fingerroot500 for testing networks

rskj-core/src/main/resources/config/main.conf, rskj-core/src/main/resources/version.properties
*fed:HOP-4.0.1.0-rc*
*ci:new-erp-script*
*fit:new-erp-script*
=> Merge hop401 into hop411

rskj-core/src/main/resources/config/main.conf
*fed:HOP-4.2.0-rc*
*fit:4.2.0-rc*
*ci:rskj-420-rc-ver*
=> HOP-4.1.1 -> HOP-4.2.0-rc merge

rskj-core/src/main/resources/config/main.conf
=> HOP-4.2.0-rc -> master merge

rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java, rskj-core/src/main/java/co/rsk/cli/tools/RewindBlocks.java
Fixed some issues with Rewind functionality:
- not properly closing RskContext (this applies to all `CliToolRskContextAware` implementations)
- avoid edge case when rewinding to a block that does not exist on block store (i.e. after import functionality, when the first consistent block in snapshot is not present yet in block store). This was leaving the index in an "corrupt" state (throwing exception due to empty index basically)
=> Rewind fixes

rskj-core/src/main/java/co/rsk/core/bc/BlockHeaderValidatorImpl.java, rskj-core/src/main/java/co/rsk/core/bc/BlockRelayValidatorImpl.java, rskj-core/src/main/java/co/rsk/core/bc/BlockValidatorImpl.java, rskj-core/src/main/java/co/rsk/net/AsyncNodeBlockProcessor.java, rskj-core/src/main/java/co/rsk/validators/BlockHeaderParentCompositeRule.java, rskj-core/src/main/java/co/rsk/validators/BlockTimeStampValidationRule.java
Just adding some missing logs to blocksync validations
=> Added missing logs to blocksync

rskj-core/src/main/resources/version.properties
=> Bumped version to 4.4.0

rskj-core/src/main/resources/version.properties
=> Changed version modifier from RC to HOP for v4.3.0

rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceModuleImpl.java
Improves `TraceModuleImpl.java` by applying some sonar suggestions
Code Cleanup
- Unit Tests
- QA
N/A
=> Improving Trace Module

rskj-core/src/test/java/co/rsk/core/parallel/ParallelExecutionStateTest.java
=> RSKIP 144 tests

rskj-core/src/main/java/co/rsk/cli/CliToolRskContextAware.java, rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
Ignoring unmatched args from RSK context when using cli tools
Right now CLI tools crash with the following:
```
Exception in thread "main" java.util.NoSuchElementException: -t is not a valid option
at co.rsk.cli.CliArgs$Parser.getOptionByName(CliArgs.java:177)
at co.rsk.cli.CliArgs$Parser.parseArguments(CliArgs.java:147)
at co.rsk.cli.CliArgs$Parser.parse(CliArgs.java:101)
at co.rsk.RskContext.<init>(RskContext.java:269)
at co.rsk.RskContext.<init>(RskContext.java:261)
at co.rsk.cli.CliToolRskContextAware.lambda$execute$0(CliToolRskContextAware.java:57)
at co.rsk.cli.CliToolRskContextAware.execute(CliToolRskContextAware.java:71)
at co.rsk.cli.CliToolRskContextAware.execute(CliToolRskContextAware.java:57)
at co.rsk.cli.tools.DbMigrate.main(DbMigrate.java:103)
```
=> Ignore unmatched args from rsk context

rskj-core/src/main/java/co/rsk/rpc/Web3RskModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/rsk/RskModule.java, rskj-core/src/main/java/co/rsk/rpc/modules/rsk/RskModuleImpl.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3Mocks.java
This PR add a new RPC method "rsk_shutdown" to shutdown the node.
A new RPC method named rsk_shutdown is added. This method performs System.exit(0), which smoothly and safely shutsdown the running threads. 
There are several reasons why one may need to shutdown a node by RPC:
* When running rskj node in Intellij, Intellij refuses to send CTRL+C (SIGTERM == terminate) signals to the running process. The only way to terminate a process is by pressing the stop button, which sends a SIGKILL signal, which terminates all threads immediately potentially leaving databases in a broken state.  This prevents the use of the IDE from debugging live nodes.
*  Sometimes it is important to be able to remotely shutdown a node asap. For example, if a remote execution vulnerability is found.
I sent …
=> Shutdown node by RPC feature

doc/rpc/components/schemas/IPAddress.json, doc/rpc/components/schemas/IPAddresses.json, doc/rpc/components/schemas/NodeId.json, doc/rpc/components/schemas/PeerScoring.json, doc/rpc/components/schemas/ReputationSummary.json, doc/rpc/components/schemas/ScoringPeerListExampleResult.json, doc/rpc/methods/eth_getFilterChanges.json, doc/rpc/methods/eth_getFilterLogs.json, doc/rpc/methods/eth_getLogs.json, doc/rpc/methods/eth_getTransactionReceipt.json, doc/rpc/methods/sco_banAddress.json, doc/rpc/methods/sco_bannedAddresses.json, doc/rpc/methods/sco_clearPeerScoring.json, doc/rpc/methods/sco_peerList.json, doc/rpc/methods/sco_reputationSummary.json, doc/rpc/methods/sco_unbanAddress.json
Adding OpenRPC doc for Peer Scoring methods
=> Openrpc doc sco methods

rskj-core/src/main/java/co/rsk/cli/tools/IndexBlooms.java, rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloom.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomEncoder.java, rskj-core/src/main/java/co/rsk/logfilter/BlocksBloomProcessor.java, rskj-core/src/main/java/org/ethereum/core/Blockchain.java, rskj-core/src/main/java/org/ethereum/rpc/Filter.java, rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomEncoderTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomStoreTest.java, rskj-core/src/test/java/co/rsk/logfilter/BlocksBloomTest.java, rskj-core/src/test/java/org/ethereum/rpc/LogFilterTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/util/RskTestContext.java
=> eth_getLogs remove redundant queries

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/ReleaseTransactionSet.java, rskj-core/src/test/java/co/rsk/peg/ReleaseTransactionSetTest.java
Add methods getNextPegoutWithEnoughConfirmations and removeEntry
=> Refactor ReleaseTransactionSet

rskj-core/src/main/resources/version.properties
=> Bumped version to 4.5.0

rskj-core/src/main/java/co/rsk/cli/tools/StartBootstrap.java, rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
This fix prevents node from stopping right after its launch
*ci:rskj-4.4.0-rc*
=> Fixed Bootstrap cli tool

rskj-core/src/main/java/co/rsk/cli/tools/StartBootstrap.java, rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java
=> HOP-4.4.0-rc -> master merge

rskj-core/src/main/resources/version.properties
=> Bumped version to 5.1.0

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/validators/ValidTxExecutionSublistsEdgesRule.java, rskj-core/src/test/java/co/rsk/validators/ValidTxExecutionSublistsEdgesTest.java
Apart from testing, when RSKIP144 is deactivated, the txExecutionSubl…istsEdges is null, otherwise is initially an empty array or it has the correct content.
=> Changes in RSKIP144 activation config verification

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
- Cleanup registerBtcTransaction method
- Add logs to registerBtcTransaction. Log btc tx hash without witness
*fed:FINGERROOT-5.0.0-rc*
*fit:FINGERROOT-5.0.0-rc*
*ci:FINGERROOT-5.0.0-rc*
=> Register btc transaction logs

rskj-core/src/main/resources/config/main.conf, rskj-core/src/main/resources/config/testnet.conf
Update testnet and mainnet config with new endpoints and signer keys for db import.
=> New endpoint and signers keys for db import

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/PowpegMigrationTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java
*fed:FINGERROOT-5.0.0-rc*
*fit:FINGERROOT-5.0.0-rc*
*ci:FINGERROOT-5.0.0-rc*
=> Changed logic to store standardP2shScript for the last retired fed instead of the full p2shScript

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/Web3Connector.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/RskWeb3j.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java, rskj-core/src/jmh/resources/conf/regtest.conf
=> Implemented debug methods benchmark

rskj-core/src/test/java/co/rsk/NodeRunnerSmokeTest.java, rskj-core/src/test/java/co/rsk/RskContextTest.java, rskj-core/src/test/java/co/rsk/cli/tools/CliToolsTest.java, rskj-core/src/test/java/co/rsk/core/ReversibleTransactionExecutorTest.java, rskj-core/src/test/java/co/rsk/core/SnapshotManagerTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplInvalidTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockChainImplTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java, rskj-core/src/test/java/co/rsk/core/bc/SelectionRuleTest.java, rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java, rskj-core/src/test/java/co/rsk/mine/MainNetMinerTest.java, rskj-core/src/test/java/co/rsk/mine/MinerManagerTest.java, rskj-core/src/test/java/co/rsk/mine/MinerServerTest.java, rskj-core/src/test/java/co/rsk/util/PreflightChecksUtilsTest.java, rskj-core/src/test/java/co/rsk/util/TestContract.java, rskj-core/src/test/java/org/ethereum/core/genesis/BlockchainLoaderTest.java, rskj-core/src/test/java/org/ethereum/core/genesis/GenesisHashesTest.java, rskj-core/src/test/java/org/ethereum/rpc/LogFilterTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplSnapshotTest.java, rskj-core/src/test/java/org/ethereum/rpc/dto/BlockResultDTOTest.java, rskj-core/src/test/java/org/ethereum/util/ContractRunner.java, rskj-core/src/test/java/org/ethereum/util/RskTestContext.java, rskj-core/src/test/java/org/ethereum/util/RskTestFactory.java, rskj-core/src/test/java/org/ethereum/vm/ProgramTest.java
This PR updates unit tests in a way that user's home directory is not being used in tests anymore
=> Using temp directories in unit tests instead of user home directory

rskj-core/src/jmh/java/co/rsk/jmh/runners/BenchmarkWeb3E2ERunner.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3Exception.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/BlocksAndTx.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/Web3Connector.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/RskModuleWeb3j.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/BlocksPlan.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/DebugPlan.java, rskj-core/src/jmh/resources/conf/testnet-3_860_000.conf
=> Json rpc benchmarking blocks and tx

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/EthMethodsConfig.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/Web3Connector.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/BasePlan.java, rskj-core/src/jmh/resources/conf/testnet-3_860_000.conf
=> Adding extra calls

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/Web3Connector.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/RskModuleWeb3j.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java
=> adding empty parameters methods

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/EthMethodsConfig.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/Web3Connector.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/BlocksPlan.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/TransactionPlan.java, rskj-core/src/jmh/resources/conf/regtest.conf, rskj-core/src/jmh/resources/conf/testnet-3_860_000.conf
=> adding new config data

README.md
=> Replace lgtm badge with CodeQL

rskj-core/build.gradle, rskj-core/src/test/java/co/rsk/rpc/netty/Web3WebSocketServerTest.java
* Add gradle task to run tests in parallel
* Updated tests in order to allow them run in parallel
Even though our tests are not properly designed to run in parallel, sometimes it’s worth doing that during development to speed the process up. This should be treated as a dev tool and should not be used in our ci/cd pipelines.
=> Add gradle task to run tests in parallel

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkLocalWalletWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/EthMethodsConfig.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/BasePlan.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/LocaWalletlPlan.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/LocalPlan.java, rskj-core/src/jmh/resources/conf/testnet-3_860_000.conf
=> Moving ethSign benchmark to local runner

rskj-core/src/jmh/java/co/rsk/jmh/helpers/OptionsHelper.java, rskj-core/src/jmh/java/co/rsk/jmh/runners/BenchmarkWeb3E2ELocalWalletRunner.java, rskj-core/src/jmh/java/co/rsk/jmh/runners/BenchmarkWeb3E2ERunner.java, rskj-core/src/jmh/java/co/rsk/jmh/runners/BenchmarkWeb3E2ETestRunner.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkLocalWalletWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/BlocksAndTx.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/GetLogsPlan.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/TracePlan.java
=> Json rpc benchmarking framework improvements

rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/main/java/org/ethereum/vm/VM.java, rskj-core/src/main/java/org/ethereum/vm/program/ProgramResult.java, rskj-core/src/test/java/co/rsk/rpc/modules/eth/EthModuleGasEstimationDSLTest.java, rskj-core/src/test/resources/dsl/eth_module/estimateGas/firstCallMoveAllRemainingSecondNot.txt
=> Prevent movedRemainingGasToChild flag from being reverted to false on contracts with multiple CALL op codes

rskj-core/src/jmh/java/co/rsk/jmh/web3/BenchmarkWeb3.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/Web3Connector.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/BasePlan.java, rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/GetLogsPlan.java, rskj-core/src/jmh/resources/conf/regtest.conf, rskj-core/src/jmh/resources/conf/testnet-3_860_000.conf
=> Improved eth_getLogs benchmarking

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
=> Update test to consider that pegoutsWaitingForConfirmations set has no insertion order

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
=> Added RSKIP379 activation code

rskj-core/src/main/java/org/ethereum/net/rlpx/Node.java, rskj-core/src/test/java/org/ethereum/net/rlpx/NodeTest.java
take into account host and port when comparing nodes and properly calculate hashcode of a node (by adding the calculation of the id internally)
=> Fix hashcode and equals

rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
=> Making TransactionPool.getPendingState synchronised

rskj-core/src/main/resources/version.properties
=> Bumped version to 5.2.0

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java, rskj-core/src/main/java/co/rsk/net/SyncProcessor.java, rskj-core/src/main/java/co/rsk/net/messages/MessageVisitor.java, rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/SnapSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/SyncConfiguration.java, rskj-core/src/main/java/co/rsk/net/sync/SyncEventsHandler.java, rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java, rskj-core/src/test/java/co/rsk/net/ThreeAsyncNodeUsingSyncProcessorTest.java, rskj-core/src/test/java/co/rsk/net/sync/PeerAndModeDecidingSyncStateTest.java, rskj-core/src/test/java/co/rsk/net/sync/SimpleSyncEventsHandler.java, rskj-core/src/test/java/org/ethereum/net/server/ChannelManagerImplTest.java
=> Snapshot sync jmh snapsyncstate

rskj-core/src/test/java/co/rsk/peg/FederationTestUtils.java, rskj-core/src/test/java/co/rsk/peg/P2shErpFederationTest.java
Add functions to spend funds using emergency keys from p2sh-p2wsh erp fed
=> Spend funds using emergency keys

rskj-core/src/main/resources/version.properties
*ci:fingerroot510-modifier*
*fed:FINGERROOT-5.1.0-rc*
*fit:510-rc*
=> Changed modifier to FINGERROOT for v5.1.0

rskj-core/src/test/java/co/rsk/peg/FederationErpP2shP2wshTestUtils.java
Change the logic of tx base size calculation: instead of substract witness size (that was not giving right results) from total size, it calculates the base size directly from the tx.
=> Tx size calculation

.circleci/config.yml
=> Update config.yml to use java 17 for Sonarqube analysis

rskj-core/src/main/resources/version.properties
=> Changed modifier to FINGERROOT for v5.2.0

rskj-core/src/main/resources/version.properties
=> Bumped version to 5.3.0

rskj-core/src/main/java/org/ethereum/util/RLP.java, rskj-core/src/test/java/co/rsk/util/RLPTest.java
=> FINGERROOT-5.2.0 -> master merge

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportSigHashTest.java, rskj-core/src/test/java/co/rsk/peg/PowpegMigrationTest.java
=> Store sighash on pegout creation

rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsTest.java
=> Add get transaction type method

.circleci/config.yml
Before this change unit and integration tests were running sequentially one after another, which apparently was delaying entire process.
=> Refactored circleci config to run unit and int. tests in parallel

rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java, rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java, rskj-core/src/test/java/org/ethereum/util/EthModuleTestUtils.java
Fixed a bug in the `eth_estimateGas` RPC method when the `pending` block tag is provided
=> Fixed estimateGas call with pending arg

rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java
Check null as input for newAccount method and return proper error. 
=> Check null value in newAccount method

rskj-core/src/main/java/org/ethereum/rpc/parameters/HexDurationParam.java, rskj-core/src/main/java/org/ethereum/rpc/parameters/HexIndexParam.java, rskj-core/src/test/java/org/ethereum/rpc/parameters/HexDurationParamTest.java, rskj-core/src/test/java/org/ethereum/rpc/parameters/HexIndexParamTest.java
=> Added proper handling of number parsing

rskj-core/src/main/resources/reference.conf
Increase receipts cache size from 4k to 100k and reduce blooms block size from 64 to 16.
Improve performance of the `eth_getLogs` RPC method
=> Increased receipts cache size and reduced blooms block size

rskj-core/src/main/resources/version.properties
=> Bumped version to 5.4.0

rskj-core/src/main/resources/version.properties
=> Changed modifier to FINGERROOT for v5.3.0

rskj-core/src/main/java/co/rsk/cli/RskCli.java, rskj-core/src/test/java/co/rsk/cli/RskCliTest.java
=> FINGERROOT-5.3.0 -> master merge

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java
Added new Environment contract address and consensus rule.
=> Add Environment contract address

rskj-core/src/main/java/co/rsk/pcc/NativeContract.java, rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/remasc/RemascContract.java, rskj-core/src/main/java/org/ethereum/vm/PrecompiledContractArgs.java, rskj-core/src/main/java/org/ethereum/vm/PrecompiledContractArgsBuilder.java, rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java, rskj-core/src/test/java/co/rsk/vm/precompiles/PrecompiledContractsCallErrorHandlingTests.java, rskj-core/src/test/java/org/ethereum/vm/PrecompiledContractTest.java, rskj-core/src/test/resources/dsl/contract_call/precompiled_error_handling.txt
Added Environment class to PrecompiledContracts.
=> Add environment contract

rskj-core/src/main/resources/config/testnet.conf
Added 2 new bootstrap-only nodes to testnet configuration file
To improve connectivity at the peer discovery level.
=> Add new bootstrap-only nodes to testnet configuration file

rskj-core/src/main/java/org/ethereum/crypto/HashUtil.java
=> Synchronized access to sha256digest

rskj-core/src/main/java/co/rsk/pcc/environment/Environment.java, rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java, rskj-core/src/test/java/co/rsk/vm/precompiles/PrecompiledContractsCallErrorHandlingTests.java, rskj-core/src/test/java/org/ethereum/vm/PrecompiledContractTest.java, rskj-core/src/test/resources/dsl/contract_call/precompiled_error_handling.txt
Moved Environment class to its own file and had it extend from NativeContract.
=> Move Environment class to its own file and extend from NativeContract

rskj-core/src/main/java/co/rsk/pcc/environment/Environment.java, rskj-core/src/main/java/co/rsk/pcc/environment/GetCallStackDepth.java, rskj-core/src/main/java/org/ethereum/vm/PrecompiledContracts.java, rskj-core/src/test/java/co/rsk/pcc/environment/EnvironmentTest.java, rskj-core/src/test/java/co/rsk/pcc/environment/GetCallStackDepthTest.java, rskj-core/src/test/java/co/rsk/vm/precompiles/PrecompiledContractsCallErrorHandlingTests.java, rskj-core/src/test/resources/dsl/contract_call/precompiled_error_handling.txt
Created the GetCallStackDepth class and added it to Environment class methods list.
=> Create GetCallStackDepth class and add it to Environment

rskj-core/src/main/java/co/rsk/config/BridgeConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/main/java/co/rsk/peg/pegin/PeginEvaluationResult.java, rskj-core/src/main/java/co/rsk/peg/utils/UnrefundablePeginReason.java, rskj-core/src/test/java/co/rsk/config/BridgeConstantsTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsGetTransactionTypeTest.java
- Add pegoutTxIndexGracePeriodInBtcBlocks as a Bridge constant
- Emmit event when a peg-in below the minimum is registered in the Bridge
=> New grace period and event when peg-in below the minimum

rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java
=> - Fix wrong rejected pegout reason when peg-out cannot be processed.

rskj-core/src/test/java/co/rsk/peg/PegUtilsEvaluatePeginTest.java
=> Fix wrong rejected pegout reason when peg-out cannot be processed.

rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/main/java/co/rsk/peg/PeginInformation.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsAllUTXOsToFedAreAboveMinimumPeginValueTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsEvaluatePeginTest.java, rskj-core/src/test/java/co/rsk/peg/PeginInformationTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java
=> Add new peg-in tests for registerBtcTransaction

rskj-core/src/main/resources/version.properties
=> Bumped version to 6.1.0

rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/resources/logback.xml
=> Excluded by default debug logs generated in PeerExplorer and NodeChallengeManager

rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/resources/logback.xml
=> RC-600 -> master merge

rskj-core/src/main/resources/version.properties
*ci:rc540-modifier*
*fed:FINGERROOT-5.4.0-rc*
*rit:FINGERROOT-5.4.0-rc*
=> Changed modifier to FINGERROOT for v5.4.0

rskj-core/src/main/java/co/rsk/rpc/netty/JsonRpcWeb3ServerHandler.java
=> FINGERROOT-5.4.0 -> master merge

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/resources/expected.conf
=> Made bucketSize value configurable

rskj-core/src/main/java/co/rsk/net/discovery/UDPServer.java
This change replaces UDP channel buffer allocator `AdaptiveRecvByteBufAllocator`, which is used by default, onto `FixedRecvByteBufAllocator`, which is more predictable in terms of what buffer size is gonna be used
=> Used fixed buffer allocator for udp channel

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/co/rsk/net/discovery/PeerExplorer.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/net/discovery/NodeChallengeManagerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/PeerExplorerTest.java, rskj-core/src/test/java/co/rsk/net/discovery/UDPServerTest.java
=> Retry connection to bootstrap nodes in discovery after failed attempt

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/core/bc/BlockUtils.java, rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java, rskj-core/src/main/java/co/rsk/net/handler/TxPendingValidator.java, rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java, rskj-core/src/test/java/co/rsk/core/bc/BlockUtilsTest.java, rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java, rskj-core/src/test/java/co/rsk/net/handler/TxPendingValidatorTest.java
Refactored the method `getSublistGasLimit` to either return the smallest between the block gas limit and 6.8M or the additional gas divided between the number of execution threads. This will depend on the value of the new argument added to `getSublistGasLimit`.
=> Refactor PTE gas distribution logic

Dockerfile
=> Update Dockerfile to properly handle SIGTERM signal

rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/test/java/co/rsk/core/bc/BlockExecutorTest.java, rskj-core/src/test/java/co/rsk/core/bc/ParallelizeTransactionHandlerTest.java, rskj-core/src/test/java/co/rsk/validators/ValidTxExecutionSublistsEdgesTest.java
Change the value of `TX_EXECUTION_THREADS` in Constants form 4 to 2 and updated the tests affected by the change.
=> Update tx execution threads constant value

rskj-core/src/test/java/co/rsk/net/messages/MessageVisitorTest.java
=> fix snapshot unit tests

rskj-core/src/main/java/co/rsk/config/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java, rskj-core/src/main/resources/config/main.conf, rskj-core/src/main/resources/config/testnet.conf, rskj-core/src/main/resources/version.properties, rskj-core/src/test/java/co/rsk/config/BridgeConstantsTest.java
*ci:arrowhead-600*
*fed:ARROWHEAD-6.0.0-rc*
*rit:ARROWHEAD-6.0.0-rc*
=> Set Arrowhead activation heights for testnet and mainnet. Version modifier to ARROWHEAD

rskj-core/src/main/java/co/rsk/trie/TrieDTO.java, rskj-core/src/main/java/co/rsk/trie/TrieDTOInOrderIterator.java, rskj-core/src/test/java/co/rsk/trie/TrieDTOTest.java
=> Fixing sonar issues and adding unit test

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/sync/SnapSyncState.java, rskj-core/src/main/java/co/rsk/rpc/modules/rsk/RskModuleImpl.java, rskj-core/src/main/java/co/rsk/trie/TrieDTOInOrderIterator.java, rskj-core/src/main/java/co/rsk/trie/TrieDTOInOrderRecoverer.java, rskj-core/src/test/java/co/rsk/trie/TrieDTOInOrderIteratorTest.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
=> Fixing sonar issues and adding unit tests

rskj-core/src/main/java/co/rsk/trie/TrieDTOInOrderRecoverer.java, rskj-core/src/test/java/co/rsk/trie/TrieDTOTest.java, rskj-core/src/test/java/co/rsk/trie/TrieStoreImplTest.java
=> Fixing sonar issue and adding unit test

rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java, rskj-core/src/test/java/co/rsk/trie/TrieDTOInOrderIteratorTest.java
In order to solve the quality gates issues from sonar analysis for the snapshot synch processor, we are step by step, adding tests.
This PR aims to add test coverage for the SnapshotProcessor class.
=> Adding some tests for SnapshotProcessor class

rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java
=> Removing unused import

SECURITY.md
Change the Bug Bounty Program references.
Change the bug bounty program URL, the website domains, and the program response times.
The changes are aligned with iovlabs rebranding to rootstocklabs.
The change in the response times is to adjust them with our bug bounty program.
N/A
N/A
N/A
=> Change Bug Bounty Program references

rskj-core/src/main/resources/version.properties
=> Changed modifier to ARROWHEAD for v6.1.0

rskj-core/src/main/resources/version.properties
=> Bumped version to 6.2.0

rskj-core/src/main/java/org/ethereum/core/genesis/GenesisLoaderException.java, rskj-core/src/main/java/org/ethereum/core/genesis/GenesisLoaderImpl.java, rskj-core/src/test/java/org/ethereum/core/genesis/GenesisLoaderImplTest.java
First checks for files inside the resources folder to provide default backward compatibility and if not found it tries the file system.
( in favor of #2265 )
Documented on devportal in [PR-1004](https://github.com/rsksmart/devportal/pull/1004).
=> feat(genesis): allows external genesis file

rskj-core/src/main/java/co/rsk/peg/federation/FederationMember.java
Recreates https://github.com/rsksmart/rskj/pull/2304
=> Make Value field In KeyType Enum Final

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationMember.java
Recreates https://github.com/rsksmart/rskj/pull/2306
=> Fix log message in bridgesupport releasebtc

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationMember.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsGetTransactionTypeTest.java
Recreates https://github.com/rsksmart/rskj/pull/2307
=> Rename minimum pegout constants from bridgeconstants

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/feeperkb/constants/FeePerKbConstantsTest.java, rskj-core/src/test/java/co/rsk/peg/performance/VoteFeePerKbChangeTest.java
- Adding Unit Tests For FeePerKbConstants using parameterized tests to consider the different possible networks.
- Refactoring some calls to variables that were moved from BridgeConstant to FeePerKbConstants.
Add test coverage to our project.
=> Unit Tests For FeePerKbConstants

rskj-core/src/main/java/co/rsk/peg/federation/FederationStorageProvider.java
Copy federation-related methods from BridgeStorageProvider to new FederationStorageProvider interface.
=> Create federation storage provider interface

rskj-core/src/main/java/co/rsk/peg/federation/FederationChangeFunction.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationChangeFunctions.java
Create an enum to hold FEDERATION_CHANGE_FUNCTIONS from BridgeSupport.
_Disclaimer:_ this pr just creates the enum.
=> Create federation change functions enum inside /federation package

rskj-core/src/test/java/co/rsk/peg/vote/ABICallElectionTest.java
=> Sonar fix: removed unused import

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/federation/PendingFederation.java
Create FederationSupport implementation to implement FederationSupport interface
=> Create fed support implementation

rskj-core/src/main/resources/version.properties
=> Bumped version to 6.3.0

rskj-core/src/main/java/co/rsk/peg/BridgeStorageIndexKey.java, rskj-core/src/main/java/co/rsk/peg/storage/FederationStorageIndexKey.java
Move federation storage index keys from `BridgeStorageIndexKey` to new `FederationStorageIndexKey` enum
=> Create FederationStorageIndexKey enum 

rskj-core/src/main/java/co/rsk/peg/bitcoin/InvalidOutpointValueException.java, rskj-core/src/main/java/co/rsk/peg/bitcoin/UtxoUtils.java, rskj-core/src/test/java/co/rsk/peg/bitcoin/UtxoUtilsTest.java
Create a UtxoUtils class and two new methods, one for encoding a list of outpoint values and another for decoding byte array outpoint values.
=> Create utils methods to decode and encode outpoint values list

rskj-core/src/test/java/co/rsk/peg/feeperkb/FeePerKbStorageProviderImplTest.java
Add the necessary UTs to cover the functionality exposed by FeePerKbStorageProvider.
**Test Coverage:** 87%
Increase test coverage working on the Bridge Refactor.
=> Unit Tests for FeePerKbStorageProvider

rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
- Removing UTs related to FeePerKb since all FeePerKb test methods must be on FeePerKbStorageProviderImplTest.
- Adding some improvements suggested by IntelliJ and making sure the coverage is not being affected.
Fix some issues related to FeePerKb/Bridge refactor.
=> Fixing UTs for BridgeStorageProviderTest

rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderPegoutTxIndexTests.java, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportProcessFundsMigrationTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportRSKIP220NewMethodsTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportSigHashTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderTests.java
Rename it to FederationStorageProviderTests and move it into /federation package.
=> Fix BridgeStorageProviderFederationTests

rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java, rskj-core/src/test/java/co/rsk/peg/PegTestUtils.java, rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
Uncomment and fix failing tests in BridgeSupportFlyoverTest class
=> Fix flyover tests

rskj-core/src/test/java/co/rsk/peg/feeperkb/FeePerKbSupportImplTest.java
- Increasing coverage for FeePerKbSupport.
Increase UT's coverage.
=> Add Coverage For FeePerKbSupport

rskj-core/src/integrationTest/README.md, rskj-core/src/integrationTest/java/co/rsk/util/OkHttpClientTestFixture.java, rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleChannelManager.java
=> master -> snap-v4-final merge

rskj-core/src/test/java/co/rsk/peg/feeperkb/FeePerKbSupportImplTest.java
- Removed some tests that were redundant after the new test cases added
- Create a function to return an AbiCallElection object with a pre-existing vote
=> Fee per kb tests improvements

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java, rskj-core/src/main/java/org/ethereum/datasource/RocksDbDataSource.java, rskj-core/src/main/resources/logback.xml, rskj-core/src/test/resources/test-rskj.conf
=> chore: cleanup; add missing logger to logback.xml

rskj-core/src/test/java/co/rsk/peg/performance/ActiveFederationTest.java, rskj-core/src/test/java/co/rsk/peg/performance/FederationChangeTest.java, rskj-core/src/test/java/co/rsk/peg/performance/PendingFederationTest.java, rskj-core/src/test/java/co/rsk/peg/performance/RetiringFederationTest.java, rskj-core/src/test/java/co/rsk/peg/performance/StateForBtcReleaseClientTest.java, rskj-core/src/test/java/co/rsk/peg/performance/UpdateCollectionsTest.java, rskj-core/src/test/java/co/rsk/peg/performance/VoteFeePerKbChangeTest.java
- Comment out lines in performance tests that require the use of FederationStorageProvider. Leave a TODO comment for future rework
=> Performance tests fix

rskj-core/src/main/java/co/rsk/peg/storage/StorageAccessor.java, rskj-core/src/test/java/co/rsk/peg/InMemoryStorage.java, rskj-core/src/test/java/co/rsk/peg/InMemoryStorageSimulator.java
- Create a specific implementation to be used in Unit Tests, simulating the In-Memory Storage, and reducing the use of mocks.
To reduce the use of mocks, thus improving the Unit Tests reliability.
=> In-Memory Storage Simulator

rskj-core/src/test/java/co/rsk/peg/BridgeCostsTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java, rskj-core/src/test/java/co/rsk/peg/BridgeTestIntegration.java, rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java, rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java
The hardcoded regtest priv keys were wrong.
=> Modify wrong regtest federation private keys

rskj-core/src/integrationTest/java/co/rsk/snapshotsync/SnapshotSyncIntegrationTest.java, rskj-core/src/integrationTest/java/co/rsk/util/cli/ConnectBlocksCommandLine.java, rskj-core/src/integrationTest/java/co/rsk/util/cli/RskjCommandLineBase.java, rskj-core/src/main/java/co/rsk/net/messages/MessageType.java, rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java
=> chore(snap): refactor PeerAndModeDecidingSyncState and SnapshotSyncIntegrationTest

rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistStorageProvider.java
Create an interface WhitelistStorageProvider under co.rsk.peg.whitelist package. Include the signature of the 2 methods Whitelist-related from BridgeStorageProvider.
This is related to the Bridge Refactor to decouple some objects that are tied closely to the Bridge.
=> Whitelist Storage Provider

rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupport.java
Create an interface called WhitelistSupport, and put all the method signatures Whitelist-related on it. Take these methods from BridgeSupport. The plan is to remove all of them from BridgeSupport into their own WhitelistSupport class.
=> Whitelist Support Interface

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationTestUtils.java
Refactor existing getActiveFederation tests to use InMemoryStorage and FederationSupportBuilder
Add a test case to check for null new fed but existing old fed
=> Test getActiveFederation method from FederationSupportImpl

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeDevNetConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistTestNetConstants.java
- Following the Bridge refactors tasks, it is time to refactor and remove whitelisting logic from the BridgeConstants class.
This is related to the Bridge Refactor to decouple some objects that are tied closely to the Bridge.
=> Whitelist Constants

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupportFactory.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistStorageProviderImpl.java
Create an implementation of WhitelistStorageProvider under co.rsk.peg.whitelist package. Include the implementation of the 2 methods Whitelist-related from BridgeStorageProvider that save the Whitelist to the storage and the method that get the lock Whitelist.
=> Whitelist Storage Provider Implementation

rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/whitelist/constants/WhitelistConstantsTest.java
Following the Bridge refactors, we already migrated the WhitelistConstants to their classes to break the high coupling Whitelist had with the Bridge objects, however, it’s missing add coverage, so we need to create Unit Tests to get reliability your new code doesn't break existing functionality when a change is made to the application.
Create Test Cases for all Networks such as MainNet, TestNet, and RegTest.
Get coverage and reliability for our project.
Unit Tests.
=> Unit Tests for WhitelistConstants

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistResponseCode.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupport.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupportImpl.java
Create the implementation of the WhitelistSupport interface, and put all the method Whitelist-related on it. Take these methods from BridgeSupport. The plan is to remove all of them from BridgeSupport into their own WhitelistSupport class. This implementation class must contain all the business logic related to Whitelist.
=> Whitelist Support Implementation

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupportFactory.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistResponseCode.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistStorageProviderImpl.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/whitelist/constants/WhitelistTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/whitelist/constants/WhitelistConstantsTest.java, rskj-core/src/test/java/co/rsk/test/builders/BridgeSupportBuilder.java
- Use WhitelistResponseCode in Bridge class
- Add network parameters to WhitelistConstants. Remove network parameters from WhitelistSupport, get the value from WhitelistConstants
- Update BridgeSupportFactory to build WhitelistSupport
- Include WhitelistConstants tests
=> Whitelist support creation

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/federation/PendingFederationBuilder.java
- Add getPendingFederationSize tests
- Create PendingFederationBuilder
- Rename tags to be more accurate
=> Add getPendingFederationSize tests

rskj-core/src/test/java/co/rsk/net/utils/TransactionUtils.java, rskj-core/src/test/java/co/rsk/peg/whitelist/WhitelistCaller.java, rskj-core/src/test/java/co/rsk/peg/whitelist/WhitelistSupportImplTest.java
Add Unit Tests for WhitelistSupportImpl making sure we are simulating real scenarios.
Add coverage to the Whitelist process.
Unit Tests
=> Whitelist Support Test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
-Add `getActiveFederationBtcUTXOs` tests
-Rename other tests to be more accurate
_Disclaimer:_
The values had to be saved directly in the repository because there are no `setFederationUTXOs` methods in the implementation
=> Add getActiveFederationBtcUTXOs tests

rskj-core/src/main/resources/version.properties
=> Bumped version to 6.4.0

rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java, rskj-core/src/test/java/co/rsk/peg/whitelist/WhitelistStorageProviderImplTest.java, rskj-core/src/test/java/org/ethereum/TestUtils.java
Create a new class WhitelistStorageProviderImplTest, look for test cases that use Whitelist related methods in BridgeStorageProviderTest, and move those tests to the new class.
Get Coverage.
Unit Tests
=> Whitelist Storage Provider Test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
-Add `getNewFederationBtcUTXOs` tests
=> Add getNewFederationBtcUTXOs tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
-Add getLastRetiredFederationP2SHScript tests
-Refactor to use global setUp
-Add tags to keep related-tests organized
=> Add getLastRetiredFederationP2SHScript tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
-Add clearRetiredFederation test
=> Add clearRetiredFederation test

rskj-core/src/integrationTest/java/co/rsk/util/OkHttpClientTestFixture.java, rskj-core/src/integrationTest/java/misc/PteIntegrationTest.java, rskj-core/src/integrationTest/java/pte/PteIntegrationTest.java, rskj-core/src/integrationTest/resources/pte-integration-test-rskj.conf, rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java, rskj-core/src/test/java/org/ethereum/rpc/dto/BlockResultDTOTest.java
Adding integration test
Test the blackbox behavior and confirm the feature works as expected
This is only, a test. 😛 
N/A
=> Add integration test

rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java, rskj-core/src/main/java/co/rsk/net/messages/MessageType.java, rskj-core/src/main/java/co/rsk/net/messages/SnapStateChunkRequestMessage.java, rskj-core/src/main/java/co/rsk/net/messages/SnapStateChunkResponseMessage.java, rskj-core/src/main/java/org/ethereum/net/server/Stats.java, rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java, rskj-core/src/test/java/co/rsk/net/messages/MessageTest.java, rskj-core/src/test/java/co/rsk/net/messages/SnapStateChunkRequestMessageTest.java, rskj-core/src/test/java/co/rsk/net/messages/SnapStateChunkResponseMessageTest.java, rskj-core/src/test/java/org/ethereum/net/server/StatsTest.java
Right now, the Snapshot Sync messages don't have a clear priority. This could cause them to get in the way of other important messages on the network. To fix this, we need to update how we prioritize Snapshot Sync messages. This update will create a clear system for managing these messages so they don't disrupt other important functions of the network and are handled efficiently.
By giving Snapshot Sync messages clear priorities, we can make sure they don't slow down or interrupt other important communications. This will keep the network running smoothly and ensure that all the data stays synced properly across all the nodes.
**Added 2 tests:**
- **TestSnapshotMessageTypes()**: This test makes sure that the Stats class uses the right priority for the snap messages.
- …
=> Configure the priority for the message types for Snapshot sync

.github/workflows/build_and_test.yml, build.gradle
=> fix(ci): [master->ARROWHEAD-6.3.0-rc] persist test reports for sonar

rskj-core/src/main/java/org/ethereum/util/RLP.java, rskj-core/src/test/java/org/ethereum/util/RLPTest.java
- decode - index check
- decodeInt improvement
- removing unnecessary methods
*ci:rc630-modifier*
=> RLP Refactor

rskj-core/src/main/resources/version.properties
=> Changed modifier to ARROWHEAD for v6.3.0

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
Whitelist-related logic has now been moved to its classes, however, those methods are still being called through BridgeSupport. We need to add some coverage for those methods.
Create tests in BridgeSupportTest, to give coverage for the whitelist related methods that call WhitelistSupport. There’s not much logic to test there, simply mock the WhitelistSupport class response and give coverage to those methods.
Unit Tests.
=> Add Tests In BridgeSupport For Whitelist

rskj-core/src/test/java/co/rsk/peg/BridgeSupportAddSignatureTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java, rskj-core/src/test/java/co/rsk/peg/whitelist/WhitelistCaller.java
Whitelist-related logic has now been moved to its classes, however, this refactor broke some classes that we need to fix.
Create a branch from the Integration Whitelist branch and fix all the test classes broken with issues related to Whitelist.
Unit Tests.
=> Second Part Fix Issues Related To Whitelist Refactor

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupport.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupportImpl.java
Bug Fix related to Whitelist `save` Method.
=> Fixing Issue Related to Whitelist save Method.

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTestIntegration.java
Whitelist-related logic has now been moved to its classes, however, this refactor broke some classes that we need to fix.
Fix all the test classes broken with issues related to Whitelist in `BridgeSupportTestIntegration`, and remove all tests that were already covered in `WhitelistSupportImplTest` and `BridgeSupportTest`.
Unit Tests.
=> Third Part Fix Issues Related To Whitelist Refactor

rskj-core/src/main/java/co/rsk/peg/feeperkb/FeePerKbSupport.java, rskj-core/src/main/java/co/rsk/peg/feeperkb/FeePerKbSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/whitelist/WhitelistSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportIT.java
- Rename variables in FeePerKbSupportImpl and WhitelistSupportImpl
=> Variables renaming

rskj-core/src/integrationTest/resources/snap-sync-client-rskj.conf, rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java, rskj-core/src/main/java/co/rsk/net/sync/PeerAndModeDecidingSyncState.java, rskj-core/src/main/java/co/rsk/net/sync/PeersInformation.java, rskj-core/src/main/java/co/rsk/net/sync/SnapshotPeersInformation.java, rskj-core/src/main/java/co/rsk/net/sync/SyncConfiguration.java, rskj-core/src/main/java/org/ethereum/config/SystemProperties.java, rskj-core/src/main/java/org/ethereum/net/NodeManager.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java, rskj-core/src/test/java/co/rsk/net/ThreeAsyncNodeUsingSyncProcessorTest.java, rskj-core/src/test/java/co/rsk/net/sync/PeersInformationTest.java, rskj-core/src/test/java/co/rsk/net/sync/SnapSyncStateTest.java, rskj-core/src/test/java/org/ethereum/net/NodeManagerTest.java
Adding new configuration feature to specify in config a list of snap boot nodes to sync against.
This new feature will be under a snapshot configuration section named _trustedPeers_:
```
trustedPeers = [
{
nodeId = <id>
ip = <ip>
port = <port>
}
]
```
I added a new `SnapshotPeersInformation` interface to distinctly define and specify all methods related to managing peers in the Snapshot Sync process. I've also modified the `RskContext` to include the _snapshotTrustedPeers_ in the `SyncConfiguration`.
There's a filter in the Snapshot methods of the PeersInformation class that verifies if the peers are specified in the configuration list. When they are, the behavior operates as intended.
We want to enhance how well and how smoothly nodes sync using the SNAP protocol. By adding a list where …
=> Config list of snapboot nodes to sync against

rskj-core/src/test/java/co/rsk/peg/whitelist/constants/WhitelistConstantsTest.java
Fix an issue in the `getBtcParams` test comparing in the `assertion` the `BtcParams` related to different networks.
Unit Tests.
=> Fix WhitelistConstantsTest

rskj-core/src/test/java/co/rsk/peg/whitelist/WhitelistSupportImplTest.java
A new `save` method was added to WhitelistSupport, so we must add coverage.
Unit Tests.
=> Add Coverage For Save Method In WhitelistSupportImplTest

rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Add save new federation btc utxo tests
=> Add save new federation btc utxo tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Add save old federation btc utxo tests
=> Add save old federation btc utxo tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
=> Adds saveNewFederation tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Add save for save new federation
=> Add save for save new federation

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
=> Adds saveOldFederation tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Adds getPendingFederation tests
=> Adds getPendingFederation tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Add save for save active federation creation block height
=> Add save for save active federation creation block height

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Add save for save next federation creation block height
=> Add save for save next federation creation block height

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Adds saveLastRetiredFederationP2SHScript test
=> Adds saveLastRetiredFederationP2SHScript test

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Add save for save federation election
=> Add save for save federation election

rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapStorageProvider.java
Create an interface `LockingCapStorageProvider` under the `co.rsk.peg.lockingcap` package. Include the signature of the methods mentioned above. Rename `saveLockingCap` to simply `save`.
=> Locking Cap Storage Provider Interface

rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupport.java
Create a new interface `LockingCapSupport` under the `co.rsk.peg.lockingcap` package. Copy the signature and javadoc for the methods: `getLockingCap` and `increaseLockingCap`.
=> LockingCapSupport Interface

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java
=> Add rskip419 config to lovell

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapStorageProviderImpl.java
Move the following methods from `BridgeStorageProvider` to `LockingCapStorageProviderImpl`:
- `getLockingCap`
- `setLockingCap`
- `saveLockingCap`
Create a new class `LockingCapStorageProviderImpl` under the `co.rsk.peg.lockingcap` package that implements the methods defined in the `LockingCapStorageProvider` interface
=> LockingCapStorageProvider Implementation

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupport.java, rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupportImpl.java
After the `LockingCapSupport` interface has been created, it is time to implement it. Create a new class, `LockingCapSupportImpl`, under the `co.rsk.peg.lockingcap` package that implements the methods defined in the `LockingCapSupport` interface. Please take the implementation from the `BridgeSupport` class, and move to this new class.
=> LockingCapSupport Implementation

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Add non existing function test
=> Adds non existing function called test

rskj-core/src/test/java/co/rsk/peg/performance/LockingCapTest.java
Fix the LockingCapTest class, and improve it if possible.
Unit Tests.
=> Fix LockingCapTest after LockingCap refactor

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
Fix the BridgeSupportTest class.
Unit Tests.
=> Fix BridgeSupportTest after LockingCap refactor

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
=> Adds create call twice by same authorizer test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds commit empty federation test
=> Adds commit empty federation test

rskj-core/src/test/java/co/rsk/peg/federation/FederationStorageProviderImplTests.java
Remove null activations from tests
=> Removes null activations from tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds add federator with less than m of n votes test
=> Adds add federator with less than m of n votes test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Add same fed twice with same authorizer test
=> Add same fed twice with same authorizer test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds multi key, 2 feds but with different mst key test
=> Adds multi key, 2 feds but with different mst key test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
=> Add 100 members test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Commit federation with 15 members
=> Commit federation with 10 members test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds voteToCreateFederation utility method
=> Adds voteToCreateFederation utility method

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds multi key with wrong keys tests
=> Adds multi key with wrong keys tests

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds add invalid btc public key test
=> Adds add invalid btc public key test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Adds add valid federator multi keys test
=> Adds add valid federator multi keys test

rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Use add multi for vote federation change tests
=> Using ADD_MULTI for voteTo?CreateFederation tests

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java
Avoid printing artibrary or long data
=> Avoid printing artibrary or long data on logs and exceptions

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/lockingcap/LockingCapCaller.java, rskj-core/src/test/java/co/rsk/peg/lockingcap/LockingCapIT.java, rskj-core/src/test/java/co/rsk/peg/lockingcap/LockingCapSupportImplTest.java
Following the Bridge refactors, we already migrated the LockingCapConstants to their classes to break the high coupling LockingCap had with the Bridge objects, however, it’s missing add coverage, so we need to create Unit Tests to get reliability that your new code doesn't break existing functionality when a change is made to the application.
Create the Integration Test for the whole process related to LockingCap.
Integration Tests.
=> LockingCap Integration Test

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
-Add getProposedFederation method in FederationSupport
-Add tests
=> Add getProposedFederation method in FederationSupport

rskj-core/src/main/java/org/ethereum/util/RLP.java, rskj-core/src/main/java/org/ethereum/util/RLPItem.java, rskj-core/src/main/java/org/ethereum/util/RLPList.java, rskj-core/src/test/java/org/ethereum/util/RLPTest.java
=> perf: improve decoding in RLP

rskj-core/src/main/java/co/rsk/peg/BridgeStorageProvider.java, rskj-core/src/test/java/co/rsk/peg/BridgeStorageProviderTest.java
-Add `setSvpFundTxHashSigned` and `saveSvpFundTxHashSigned` methods in `BridgeStorageProvider`
-Add tests
=> Add svpFundTxHashSigned set and save methods

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
-Add methods for creating and processing the svp fund transaction (without signatures)
-Add tests
=> Add svp fund tx creation

rskj-core/src/main/java/co/rsk/config/RskSystemProperties.java, rskj-core/src/main/java/org/ethereum/net/client/ConfigCapabilitiesImpl.java
This pr adds the SNAP capability if the server **or** client have snap sync enabled. Previously, we were only checking if snapshot sync was enabled on the server to decide if we should add the SNAP capability. This meant that if the client had snapshot sync enabled but the server didn’t, the SNAP messages wouldn’t be sent correctly
Basically, I changed the condition in the `ConfigCapabilitiesImpl` class from
```
if (config.isServerSnapshotSyncEnabled() && allCapabilities.stream().anyMatch(Capability::isRSK)) {
allCapabilities.add(new Capability(SNAP, SNAP_VERSION));
}
```
to
```
if (config.isSnapshotSyncEnabled() && allCapabilities.stream().anyMatch(Capability::isRSK)) {
allCapabilities.add(new Capability(SNAP, SNAP_VERSION));
}
```
By adding a helper method in the `RskSystemProperties` …
=> Adding SNAP capability if the client or the server are enabled

rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java, rskj-core/src/test/java/org/ethereum/validator/ProofOfWorkRuleArrowhead600Test.java, rskj-core/src/test/java/org/ethereum/validator/ProofOfWorkRuleBambooTest.java, rskj-core/src/test/java/org/ethereum/validator/ProofOfWorkRuleOrchidTest.java
- removed unused field
- suppressed sonar warning about missing tests. See [this](https://community.sonarsource.com/t/testcases-should-contain-tests/88232) for more info
=> fix(pte): fixing sonar complaints

rskj-core/src/main/java/co/rsk/config/mining/HttpGetStableMinGasSystemConfig.java, rskj-core/src/main/java/co/rsk/config/mining/StableMinGasPriceSystemConfig.java, rskj-core/src/main/java/co/rsk/mine/gas/provider/EthCallMinGasPriceProvider.java, rskj-core/src/main/java/co/rsk/mine/gas/provider/HttpGetMinGasPriceProvider.java, rskj-core/src/main/java/co/rsk/mine/gas/provider/StableMinGasPriceProvider.java, rskj-core/src/main/java/co/rsk/net/http/SimpleHttpClient.java, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/co/rsk/config/mining/HttpGetStableMinGasSystemConfigTest.java, rskj-core/src/test/java/co/rsk/config/mining/StableMinGasPriceSystemConfigTest.java, rskj-core/src/test/java/co/rsk/mine/gas/provider/HttpGetMinGasPriceProviderTest.java, rskj-core/src/test/java/co/rsk/mine/gas/provider/StableMinGasPriceProviderTest.java
=> fix(stableMinGasPrice): fix time units conversion and refreshing alg

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java
=> Emit release_request_rejected event using weis values after rskip427

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/BrigeEventLoggerLegacyImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportReleaseBtcTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerLegacyImplTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerTest.java
- Refactor BridgeEvents class
- Use weis as the value when emitting release_request_received event after RSKIP427
=> Emit release_request_received event using value as weis after RSKIP427

.github/workflows/build_and_test.yml, rskj-core/build.gradle
=> build: increase gradle heap size

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Create getProposedFederationAddress in Federation Support.
=> Create getProposedFederationAddress in Federation Support

.github/workflows/rit.yml
=> build: run rit check overnight; allow plus symbol in branch names

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java
Create getProposedFederationCreationTime in Federation Support.
=> Create getProposedFederationCreationTime in Federation Support

rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java, rskj-core/src/main/java/co/rsk/peg/PegUtilsLegacy.java, rskj-core/src/main/java/co/rsk/peg/bitcoin/FlyoverRedeemScriptBuilderImpl.java, rskj-core/src/test/java/co/rsk/peg/bitcoin/FlyoverRedeemScriptBuilderImplTest.java
Get rid of MultiSigType enum
Unit tests
=> Get rid of MultiSigType enum

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Implements the Bridge method `getProposedFederationAddress`
=> Create getProposedFederationAddress Bridge Method

rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/federation/P2shErpFederationBuilder.java
Create getProposedFederatorPublicKeyOfType in Federation Support.
=> Create getProposedFederatorPublicKeyOfType in Federation Support

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Implements the Bridge method `getProposedFederationCreationTime`
=> Create getProposedFederationCreationTime Bridge Method

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Implements the Bridge method `getProposedFederationSize`
=> Create getProposedFederationSize Bridge Method

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java
Implements the Bridge method `getProposedFederatorPublicKeyOfType `
=> Create getProposedFederatorPublicKeyOfType Bridge Method

rskj-core/src/main/resources/version.properties
=> release(ARROWHEAD-6.4.0): change modifier to RC

README.md
=> chore: update status badges

Dockerfile
Builds were failing due to an extra quote on the Dockerfile
This PR fixes the aforementioned issue
By using automated tests
N/A
=> Fix label on Dockerfile

rskj-core/src/main/java/co/rsk/peg/Bridge.java
Add function constants to Bridge for proposed federation
=> Add function constants to Bridge for proposed federation

rskj-core/src/main/resources/version.properties
`fed:ARROWHEAD-6.4.0-rc`
`rit:feature/adding_repo_owner_input`
=> build(ARROWHEAD-6.4.0): change modifier to ARROWHEAD

rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/mine/BlockGasPriceRange.java, rskj-core/src/main/java/co/rsk/mine/MinimumGasPriceCalculator.java, rskj-core/src/main/java/co/rsk/mine/gas/provider/MinGasPriceProviderFactory.java, rskj-core/src/main/java/co/rsk/mine/gas/provider/StableMinGasPriceProvider.java
=> arrowhead-6.4.0 -> master merge

.github/workflows/rit.yml
=> Fixing typos in branch config

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationRegTestConstants.java, rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationConstantsTest.java
Added some fixes to the SVP protocol:
1. Enhance logging to make it more visible when SVP is going on.
2. Save the svp spend tx waiting for signatures back in storage to not loose the signature.
3. Increment regtest svp period timeframe.
In regtest.
=> Some fixes to the SVP protocol

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
- Refactoring methods to improve clarity and consistency.
- Removing global variables from test classes to enhance test isolation and reliability.
- Adding new methods to assert SVP (Simple Verification Protocol) success.
=> Svp updates

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/PegTxType.java, rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/main/java/co/rsk/peg/PegUtilsLegacy.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationContext.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupport.java, rskj-core/src/main/java/co/rsk/peg/federation/FederationSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationRegTestConstants.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportFlyoverTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsGetTransactionTypeTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyGetTransactionTypeTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsLegacyTest.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationContextTest.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/federation/VoteFederationChangeTest.java, rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationConstantsTest.java
- Create a `FederationContext` class, to hold information about active and retiring federations
- Refactor `PegUtils` methods to receive a `FederationContext` object instead of each element separately
- Update `getTransactionType` method to detect SVP related transactions
- Update `PegTxType` enum to add SVP types
- Update `registerBtcTransaction` to detect and process SVP related transactions
=> Include SVP transactions as possible transaction types to be used by the Bridge

rskj-core/src/main/resources/version.properties
=> build(ARROWHEAD-6.5.0): change modifier to ARROWHEAD

rskj-core/src/main/java/co/rsk/peg/federation/constants/FederationMainNetConstants.java, rskj-core/src/test/java/co/rsk/peg/federation/constants/FederationConstantsTest.java
=> Increase mainnet svp validation period

rskj-core/src/main/java/co/rsk/validators/BlockHeaderParentCompositeRule.java
=> feat(snap): imports cleanup

.github/dependabot.yml, .github/workflows/docker-release.yml, .github/workflows/docker-verification.yml, .github/workflows/docker.yml
Adding steps to run and check container built
=> Adding step to run and check docker container

rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinUtilsTest.java
Add tests passing a too-short witness commitment and witness output using no_op
=> Add test cases for findWitnessCommitment method

rskj-core/src/main/resources/version.properties
=> build(LOVELL-7.0.0): change modifier to RC

rskj-core/src/main/resources/version.properties
=> build: bump version to 7.1.0

rskj-core/src/main/java/co/rsk/peg/PegUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportSvpTest.java
=> Handle exception when removing signatures from a tx with non p2sh-legacy-multisig inputs

.github/workflows/rit.yml, rskj-core/src/main/resources/version.properties
=> build(LOVELL-7.0.1): change version to 7.0.1

Dockerfile
Cherry picking commits from master to add the docker user fix.
=> config docker user

Dockerfile
=> Revert "Fixing Docker permission issues"

rskj-core/src/main/java/co/rsk/cli/RskCli.java, rskj-core/src/main/java/co/rsk/config/ConfigLoader.java, rskj-core/src/main/java/co/rsk/config/NodeCliFlags.java, rskj-core/src/main/java/org/ethereum/config/Constants.java, rskj-core/src/main/java/org/ethereum/config/SystemProperties.java, rskj-core/src/main/resources/config/testnet2.conf, rskj-core/src/main/resources/remasc.json, rskj-core/src/test/java/co/rsk/NodeRunnerSmokeTest.java, rskj-core/src/test/java/co/rsk/cli/RskCliTest.java, rskj-core/src/test/java/co/rsk/config/ConfigLoaderTest.java, rskj-core/src/test/java/co/rsk/config/RemascConfigFactoryTest.java
This PR introduces the initial configuration for the newly proposed Testnet2 mode for the RSKj node. The changes include:
- **CLI and Configuration Updates:** Modified the CLI and configuration files to support Testnet2, following the structure of the existing Testnet mode. This includes adding a provisional network ID of **34** for Testnet2
- **Testnet2 Constants**: Added the method to define Testnet2 constants, initially borrowing configurations from Testnet (e.g., chain ID, TESTNET2_RESOURCE_PATH, and testnet2 constant).
- **BridgeTestNetConstants**: The configuration uses the BridgeTestNetConstants instance, which handles the parameters related to the RSK-Bitcoin bridge in test networks. These include transaction fee settings, whitelisting rules, federation details, and locking …
=> Adding Rootstock Testnet2 config mode to the RSKj node

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/NetworkUpgrade.java, rskj-core/src/main/resources/config/devnet.conf, rskj-core/src/main/resources/config/main.conf, rskj-core/src/main/resources/config/regtest.conf, rskj-core/src/main/resources/config/testnet.conf, rskj-core/src/main/resources/expected.conf, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java
Add the next hard fork, tbd800 is a placeholder.
=> Added tbd800 hardfork

rskj-core/src/test/java/co/rsk/peg/federation/PendingFederationTest.java
=> fix: parameterize the tests

rskj-core/src/main/java/co/rsk/peg/federation/PendingFederation.java, rskj-core/src/test/java/co/rsk/peg/federation/FederationChangeIT.java, rskj-core/src/test/java/co/rsk/peg/federation/PendingFederationTest.java, rskj-core/src/test/java/co/rsk/peg/federation/VoteFederationChangeTest.java
=> feat: Added that if rskip305 is active the federation built is p2sh-p2wsh

rskj-core/src/test/java/co/rsk/peg/BridgeSupportRegisterBtcTransactionTest.java, rskj-core/src/test/java/co/rsk/peg/PegUtilsGetTransactionTypeTest.java, rskj-core/src/test/java/co/rsk/peg/bitcoin/BitcoinTestUtils.java
=> Transaction witness extraction method

rskj-core/src/main/java/co/rsk/peg/bitcoin/BitcoinUtils.java
This makes the code more rebust by customizing the "equals" between TransactionWitness objects.
=> Changed == for equals implemented in bitcoinj-thin branch txWitness-equals

docs/03-node-operators/04-setup/experimental-features.md
Updating the doc on snap sync.
Adding some clarification and organizing the doc in order to add more experimental features in the future.
Locally.
N/A
=> Updating snap doc

rskj-core/src/main/java/org/ethereum/config/blockchain/upgrades/ConsensusRule.java, rskj-core/src/main/resources/config/testnet2.conf, rskj-core/src/main/resources/expected.conf, rskj-core/src/main/resources/reference.conf, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigTest.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java
Add RSKIP502 activation code
Unit tests
=> Add RSKIP502 activation code

rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/union/constants/UnionBridgeConstantsTest.java
Add UnionBridgeConstants for each network
Unit tests
- [ x Tests for the changes have been added (for bug fixes / features)
=> Add UnionBridgeConstants for each network

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
Create serialize/deserialize util methods to store unionBridgeContractAddress
Unit tests
=> Create serialize/deserialize util methods to store unionBridgeContractAddress

rskj-core/src/main/java/co/rsk/peg/union/UnionResponseCode.java, rskj-core/src/test/java/co/rsk/peg/union/UnionResponseCodeTest.java
Add Union Responses codes
Unit tests
=> Add Union Responses codes

rskj-core/src/integrationTest/java/co/rsk/snap/SnapshotSyncIntegrationTest.java, rskj-core/src/integrationTest/resources/snap-sync-client-rskj.conf, rskj-core/src/integrationTest/resources/snap-sync-server-rskj.conf, rskj-core/src/main/java/co/rsk/RskContext.java, rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java, rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java
=> feat(snap): fix checkpoint selection to appreciate potential reorgs

.github/workflows/rit.yml
=> Updates rits version hash

rskj-core/src/test/java/co/rsk/net/messages/SnapBlocksRequestMessageTest.java
Fix some sonar issues https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&severities=CRITICAL&sinceLeakPeriod=true&pullRequest=2233&id=rskj
Fix some sonar issues https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&severities=CRITICAL&sinceLeakPeriod=true&pullRequest=2233&id=rskj
Yes by just running the test file updated
=> Fix sonar issues

.github/workflows/build_and_test.yml, .github/workflows/fuzz-test.yml
Apart of moving it out from build_and_test pipeline, because it's a test that takes long hours to be executed.
We are making it run only in master or -rc branches
Also, we are validating the branch name to avoid exploitation
- Because fuzzing test takes long time and should be executed only in master and rc branches
- It will also offer the possibility to run manually for when someone wants to validate a branch
In the actions pipeline
=> Moving fuzztest part to separate pipeline

rskj-core/src/main/java/co/rsk/peg/constants/BridgeConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/constants/BridgeTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/constants/BridgeConstantsTest.java
Use union bridge constants
Unit tests
=> Use union bridge constants

rskj-core/src/fuzzTest/java/co/rsk/util/RLPFuzzTest.java, rskj-core/src/fuzzTest/java/co/rsk/vm/VMFuzzTest.java, rskj-core/src/fuzzTest/java/org/ethereum/vm/PrecompiledContractFuzzTest.java, rskj-core/src/fuzzTest/java/org/ethereum/vm/VMFuzzTest.java
A fixes for fuzz tests.
These tests are failing and need to be fixed: fuzzDecodeList, testFuzzVM, modxpRandomFuzzTest and fuzzNativeContractInputSize.
=> Fix fuzzing tests

.github/workflows/build_and_test.yml
Added a step to upload the test results as artifacts in github actions, so dev can take a look to them for further reviews
Also we added retention days of one week to these artifacts
Sometimes it is difficult to use Gtihub Actions UI to look for test failures.
Right now the possible options we have to see test failures are:
1. We can look for the keyword `FAILED` in the logs:
2. We can click on Explain Error
https://github.com/user-attachments/assets/da03d968-27ba-4d49-8928-b6f70269da80
Yes, we made some tests fail in purpose, in order to see the reports generated
=> Add step to download test results from pipeline

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Use BridgeSupport.setUnionBridgeContractForTestnet
Unit tests
- [] Requires Activation Code (Hard Fork)
=> Use BridgeSupport.setUnionBridgeContractForTestnet

rskj-core/src/main/resources/version.properties
=> build(master): bump version to 7.2.0

.github/workflows/rit.yml
=> Updates rits hash

.github/workflows/rit.yml
Run RIT using the `main` branch in [RIT repo](https://github.com/rsksmart/rootstock-integration-tests) to ensure tests are always run against the latest version
=> Update rit.yml to use `main` branch of the RIT repo

.github/workflows/scripts/devportal-update/doc_config.yaml, docs/03-node-operators/04-setup/03-configuration/metrics.md
This adds a doc page that provides instructions for exposing metrics from an RSKj node to be consumed by monitoring tools like JConsole and Prometheus
=> doc(metrics): add doc for exposing RSKj metrics

.github/workflows/rit.yml, rskj-core/src/main/resources/version.properties
=> build(LOVELL-7.1.0): change modifier to LOVELL

rskj-core/src/main/java/org/ethereum/rpc/dto/BlockResultDTO.java, rskj-core/src/test/java/org/ethereum/rpc/dto/BlockResultDTOTest.java
=> rc710 -> master merge

docs/03-node-operators/04-setup/experimental-features.md
Adding Snap-Bootstrap nodes to the devPortal documentation.
They're missing from the doc
With a markdown visualizator
- [] Tests for the changes have been added (for bug fixes / features)
N/A
=> Adding snap capable nodes to dev portal doc

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Use bridgeSupport.getUnionBridgeLockingCap method in Bridge 
Unit tests
=> Use BridgeSupport.getUnionBridgeLockingCap in Bridge

.github/workflows/scripts/devportal-update/doc_config.yaml, docs/03-node-operators/04-setup/experimental-features.md
Fixing paths in devportal automation config
=> Fixing path from node-runner in docs

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/lockingcap/LockingCapSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeConstants.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
- Create increaseLockingCap method
- Add MAX RBTC constant to UnionBridgeConstants
- Add unit tests for increaseLockingCap method
Unit Tests
=> Create increaseLockingCap method

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
- Use union increaseLockingCap method in BridgeSupport
- Added unit tests for increaseUnionBridgeLockingCap method
Unit tests
=> Use union increaseLockingCap method in BridgeSupport

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
Add serialization and deserialization methods for co.rsk.core.Coin
Unit Tests
- [] New feature (non-breaking change which adds functionality)
=> Add serialization and deserialization methods for co.rsk.core.Coin

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageIndexKey.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java
- Add get/set/save method for weiTransferredToUnionBridge
- Update save method to store weiTransferredToUnionBridge when value exists
- Add tests for get/set weiTransferredToUnionBridge methods
Unit tests
=> Add get/set/save method for weiTransferredToUnionBridge

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
Add support for logging UNION_RBTC_RELEASED events
Unit tests
=> Add support for logging UNION_RBTC_RELEASED events

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Add method to retrieve Union Bridge contract address
Unit tests
=> Add method to retrieve Union Bridge contract address

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupport.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportIT.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java, rskj-core/src/test/java/co/rsk/test/builders/UnionBridgeSupportBuilder.java
Add `requestUnionRbtc` method to `UnionBridgeSupport`
Unit tests
=> Add `requestUnionRbtc` method to `UnionBridgeSupport`

rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Add isolated tests for saving union bridge contract address, union locking cap and weis transferred value
Unit tests
=> Add isolated tests for saving union bridge contract address, union locking cap and weis transferred value

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Get rid of increaseLockingCap_preRSKIP502 tests
Unit tests
=> Get rid of increaseLockingCap_preRSKIP502 tests

rskj-core/src/main/java/co/rsk/peg/BridgeSupportFactory.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportIT.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java, rskj-core/src/test/java/co/rsk/test/builders/UnionBridgeSupportBuilder.java
Get rid of used of activations from UnionBridgeSupport
Unit tests
=> Get rid of used of activations from UnionBridgeSupport

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
- Get rid of the existing set weisTransferredToUnionBridge storage provider method.
- Create decrease weisTransferredToUnionBridge methods
- Add tests
Unit tests
=> Create increaseWeisTransferredToUnionBridge method

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/constants/UnionBridgeConstantsTest.java
Refactor Union Bridge contract address authorizer naming
Unit tests
=> Refactor Union Bridge contract address authorizer naming

rskj-core/src/main/java/co/rsk/peg/BridgeEvents.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLogger.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
Add `union_bridge_locking_cap_increased` event, implementation and tests
Unit tests
=> Add `union_bridge_locking_cap_increased` event, implementation and tests

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Create GET_UNION_BRIDGE_CONTRACT_ADDRESS bridge method
Unit tests
=> Create GET_UNION_BRIDGE_CONTRACT_ADDRESS bridge method

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageIndexKey.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java
Add storage support for UnionBridgeRequestEnabled state
Unit tests
=> Add storage support for UnionBridgeRequestEnabled state

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Refactor setUnionBridgeContractAddressForTestnet to allow current address as a valid value and update assertions in tests
Unit tests
=> Refactor setUnionBridgeContractAddressForTestnet to remove unneeded check

rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
Use `releaseUnionRbtc` method in BridgeSupport
Unit tests
=> Use `releaseUnionRbtc` method in BridgeSupport

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Create releaseUnionBridgeRbtc bridge method
Unit tests
=> Create releaseUnionBridgeRbtc bridge method

rskj-core/src/main/java/co/rsk/peg/Bridge.java, rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
Rename `requestUnionRbtc` to `requestUnionBridgeRbtc`
Unit tests
=> Rename `requestUnionRbtc` to `requestUnionBridgeRbtc`

rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
Remove unused UnionBridgeSupportBuilder setup in test
Unit tests
=> Remove unused UnionBridgeSupportBuilder setup in test

rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java, rskj-core/src/test/java/co/rsk/peg/BridgeSerializationUtilsTest.java
Add boolean serialization/deserialization support
Unit tests
=> Add boolean serialization/deserialization support

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java
Use boolean serialization/deserialization bridge util method
Unit tests
=> Use boolean serialization/deserialization bridge util method

rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
Refactor null checks to use requireNonNull
Unit tests
=> Refactor null checks to use requireNonNull

rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/utils/BridgeEventLoggerImplTest.java
Rename test method to reflect expected successful outcome
Uni tests
Unit tests
=> Rename test method to reflect expected successful outcome

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java
Refactor save method to improve readability and modularity by extracting save operations into separate methods
Unit tests
=> Refactor save method to improve readability and modularity

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/utils/BridgeEventLoggerImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Refactor requestUnionRbtc method to check authorization first
Unit tests
=> Refactor requestUnionRbtc method to check authorization first

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Refactor releaseUnionRbtc method to check authorization first.
Unit tests
=> Refactor releaseUnionRbtc method to check authorization first.

rskj-core/src/main/resources/version.properties
=> build(master): bump version to 7.3.0

rskj-core/src/main/java/co/rsk/peg/bitcoin/P2shErpRedeemScriptBuilder.java, rskj-core/src/test/java/co/rsk/peg/federation/PendingFederationTest.java
=> Pending federation test fix

rskj-core/src/main/resources/version.properties
=> build(LOVELL-7.2.0): change modifier to LOVELL

rskj-core/src/integrationTest/java/co/rsk/pte/PteIntegrationTest.java, rskj-core/src/integrationTest/java/co/rsk/snap/SnapshotSyncIntegrationTest.java, rskj-core/src/main/java/co/rsk/net/SnapshotProcessor.java, rskj-core/src/main/java/co/rsk/net/messages/CachedSnapStatusData.java, rskj-core/src/test/java/co/rsk/net/SnapshotProcessorTest.java
=> feat(snap): add caching for status request messages

rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java, rskj-core/src/main/java/co/rsk/core/bc/FamilyUtils.java, rskj-core/src/main/java/co/rsk/core/bc/SuperBlockFields.java, rskj-core/src/main/java/co/rsk/net/messages/MessageType.java, rskj-core/src/main/java/co/rsk/validators/SuperBlockRule.java, rskj-core/src/main/java/org/ethereum/core/BlockFactory.java, rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
1. Get rid of uncleList from `SuperBlockFields`
2. Remove logic that populates the `uncleList` in the miner server
3. Rremove logic from consensus rules related to `uncleList`
Due to recent changes in the Superchain spec, we don’t need `uncleList` to be part of super block fields any more, so it should be removed and everything else should be cleared up of it
It matters because of new requirements
Just running the node and updating existing tests
=> Remove unclelist

rskj-core/src/test/java/co/rsk/vm/precompiles/PrecompiledContractAddressTests.java, rskj-core/src/test/java/co/rsk/vm/precompiles/PrecompiledContractsCallErrorHandlingTests.java, rskj-core/src/test/java/org/ethereum/config/blockchain/upgrades/ActivationConfigsForTest.java, rskj-core/src/test/resources/dsl/contract_call/precompiled_error_handling.txt
=> Update tests to account for the precompiled contracts

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
Fix misleading function naming for request and release validation amount
Unit tests
=> Fix misleading function naming for request and release validation amount

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageIndexKey.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProvider.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeStorageProviderImpl.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeMainNetConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeRegTestConstants.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeTestNetConstants.java, rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageIndexKeyTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeStorageProviderImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/constants/UnionBridgeConstantsTest.java
Update union bridge contract address and authorizers to use zero address
Unit tests
=> Update union bridge contract address and authorizers to use zero address

rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java, rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/main/java/co/rsk/peg/union/constants/UnionBridgeRegTestConstants.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java, rskj-core/src/test/java/co/rsk/peg/union/constants/UnionBridgeConstantsTest.java
Improve logging in `UnionBridgeSupportImpl`, update authorizer seeds in `UnionBridgeRegTestConstants`, and allow static calls for `view` union bridge contract methods.
Unit tests
=> Improve logging in UnionBridgeSupportImpl, update union regtest authorizers seeds, and allow static calls

rskj-core/src/main/resources/version.properties
=> Bump version to 8.1.0

.github/workflows/rit.yml
Updated slack api message to use blocks instead of attachments https://docs.slack.dev/messaging/migrating-outmoded-message-compositions-to-blocks/
Remove unused env variables
=> Rit workflow update

rskj-core/src/main/java/co/rsk/peg/union/UnionBridgeSupportImpl.java, rskj-core/src/test/java/co/rsk/peg/union/UnionBridgeSupportImplTest.java
- Removed redundant authorization checks.
- Updated unit tests to reflect these changes.
Unit tests
=> Remove redundant authorization checks in `UnionBridgeSupportImpl`

rskj-core/src/test/java/co/rsk/peg/vote/AddressBasedAuthorizerTest.java
Refactored the `AddressBasedAuthorizerTest` and added missing test cases to ensure coverage of all methods.
Unit tests
=> Refactor and test `AddressBasedAuthorizerTest`
